import type { BatchThreeArticleId, LocalizedArticle } from './types';

const sourceSets: Record<BatchThreeArticleId, Array<{ label: string; url: string }>> = {
  review: [
    { label: 'Bloody Disgusting — análisis publicado de The Skin Stapler', url: 'https://bloody-disgusting.com/video-games/3962809/the-skin-stapler-review-psx-horror-throwback-favors-humor-over-gameplay/' },
    { label: 'Steam — página oficial del juego completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'Steam — demo oficial', url: 'https://store.steampowered.com/app/4343530/The_Skin_Stapler_Demo/' }
  ],
  story: [
    { label: 'Steam — página oficial del juego completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'CaseOh — partida completa', url: 'https://www.youtube.com/watch?v=EcgnRprUU5k' },
    { label: 'GabeHype — partida al 100%', url: 'https://www.youtube.com/watch?v=1kEFUOGxgjE' },
    { label: 'Steam Community — lista oficial de logros', url: 'https://steamcommunity.com/stats/4310610/achievements' }
  ],
  'games-like': [
    { label: 'Bloody Disgusting — análisis con títulos de comparación', url: 'https://bloody-disgusting.com/video-games/3962809/the-skin-stapler-review-psx-horror-throwback-favors-humor-over-gameplay/' },
    { label: 'Steam — página oficial del juego completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'GOG — página oficial de la tienda', url: 'https://www.gog.com/en/game/the_skin_stapler' },
    { label: 'Tainted Pact — página oficial en itch.io', url: 'https://taintedpact88.itch.io/the-skin-stapler' }
  ],
  uncensored: [
    { label: 'Steam — página oficial del juego completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'GOG — página oficial de la tienda', url: 'https://www.gog.com/en/game/the_skin_stapler' },
    { label: 'Steam — demo oficial', url: 'https://store.steampowered.com/app/4343530/The_Skin_Stapler_Demo/' }
  ],
  'donut-shop': [
    { label: 'Steam Community — lista oficial de logros', url: 'https://steamcommunity.com/stats/4310610/achievements' },
    { label: 'GabeHype — partida al 100%', url: 'https://www.youtube.com/watch?v=1kEFUOGxgjE' },
    { label: 'Steam — página oficial del juego completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' }
  ],
  'all-tapes': [
    { label: 'Steam — página oficial del juego completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'Steam Community — lista oficial de logros', url: 'https://steamcommunity.com/stats/4310610/achievements' },
    { label: 'CaseOh — partida completa', url: 'https://www.youtube.com/watch?v=EcgnRprUU5k' }
  ],
  'ai-generated': [
    { label: 'Steam — página oficial con la declaración handmade', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'Tainted Pact — página oficial en itch.io', url: 'https://taintedpact88.itch.io/the-skin-stapler' },
    { label: 'Tainted Pact — canal oficial de YouTube', url: 'https://www.youtube.com/@TaintedPactGames' }
  ],
  developer: [
    { label: 'Tainted Pact — página oficial en itch.io', url: 'https://taintedpact88.itch.io/the-skin-stapler' },
    { label: 'Tainted Pact — canal oficial de YouTube', url: 'https://www.youtube.com/@TaintedPactGames' },
    { label: 'Steam — página oficial del juego completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'GOG — página oficial de la tienda', url: 'https://www.gog.com/en/game/the_skin_stapler' }
  ],
  'janker-edition': [
    { label: 'Steam — DLC The Skin Jankers (App 4919860)', url: 'https://store.steampowered.com/app/4919860/' },
    { label: 'Steam — DLC de la banda sonora (App 4919810)', url: 'https://store.steampowered.com/app/4919810/' },
    { label: 'GOG — página de la tienda con el paquete Skin Jankers', url: 'https://www.gog.com/en/game/the_skin_stapler' }
  ],
  'turkish-patch': [
    { label: 'Steam — tabla de idiomas del juego completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'Steam — tabla de idiomas de la demo', url: 'https://store.steampowered.com/app/4343530/The_Skin_Stapler_Demo/' },
    { label: 'GOG — página oficial de la tienda', url: 'https://www.gog.com/en/game/the_skin_stapler' }
  ],
  'korean-patch': [
    { label: 'Steam — tabla de idiomas del juego completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'Steam — tabla de idiomas de la demo', url: 'https://store.steampowered.com/app/4343530/The_Skin_Stapler_Demo/' },
    { label: 'GOG — página oficial de la tienda', url: 'https://www.gog.com/en/game/the_skin_stapler' }
  ],
  'press-kit': [
    { label: 'Steam — galería oficial de capturas', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'YouTube — tráiler oficial (5tEJiy8FJbY, 27 de enero de 2026)', url: 'https://www.youtube.com/watch?v=5tEJiy8FJbY' },
    { label: 'GOG — galería oficial', url: 'https://www.gog.com/en/game/the_skin_stapler' }
  ],
  'final-aftermath': [
    { label: 'Steam Community — lista oficial de logros', url: 'https://steamcommunity.com/stats/4310610/achievements' },
    { label: 'GabeHype — partida al 100%', url: 'https://www.youtube.com/watch?v=1kEFUOGxgjE' },
    { label: 'Steam — página oficial del juego completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' }
  ],
  'aftermath-3': [
    { label: 'Steam Community — lista oficial de logros', url: 'https://steamcommunity.com/stats/4310610/achievements' },
    { label: 'GabeHype — partida al 100%', url: 'https://www.youtube.com/watch?v=1kEFUOGxgjE' },
    { label: 'Steam — página oficial del juego completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' }
  ]
};

export const batchThreeEs: Record<BatchThreeArticleId, LocalizedArticle> = {
  review: {
    id: 'review', keyword: 'The Skin Stapler análisis',
    title: 'The Skin Stapler análisis: veredicto, aciertos y fallos',
    description: 'El análisis de The Skin Stapler: 2,5 horas de terror grindhouse, capítulos de víctimas que quitan el aliento, mecánica superficial — y para quién compra los 14,99 euros.',
    eyebrow: 'Análisis y decisión de compra',
    directAnswer: 'The Skin Stapler es un terror grindhouse de 2,5 horas en 14 capítulos cortos, cuya fortaleza son los capítulos de víctimas cargados de tensión y cuya debilidad es la mecánica ligera. Bloody Disgusting lo recomienda claramente a los fans de Sniper Killer y Rewind or Die — y desaconseja al resto. Las reseñas de Steam se quedaron cerca del 90% positivas en la ventana de lanzamiento, con alrededor de 340 análisis.',
    date: '2026-09-03',
    sections: [
      { title: 'El veredicto en resumen', paragraphs: ['El análisis publicado por Bloody Disgusting examinó la versión completa y resume el juego como un título grindhouse corto y basto por elección. Estos son los puntos que pesan en tu decisión de compra:'], bullets: ['Duración: cerca de 2,5 horas en 14 capítulos cortos', 'Estructura: los capítulos alternan entre investigación y perspectiva de la caza', 'Mejor momento: los capítulos de víctimas, en especial la apertura con Fefe', 'Punto débil: mecánica superficial y repetitiva en algunos tramos', 'Presentación: secuencias FMV estilo VHS y la Carrion City de 1984 convencen', 'Nota: escala de calaveras en vez de número — a los fans de Sniper Killer y Rewind or Die se suma una calavera, al resto se le resta', 'Clima en Steam: cerca del 90% positivas entre aproximadamente 340 análisis en la ventana de lanzamiento'] },
      { title: '¿Qué juego se está analizando?', paragraphs: ['The Skin Stapler es un juego de terror corto y guiado por la historia, ambientado en la Carrion City de 1984, una ciudad llena de excéntricos absurdos. Alternas entre el detective desgastado Dick Slater en la investigación y la perspectiva del perseguidor en los capítulos de caza. El pitch de la propia editora — cazar a un asesino en serie por una pesadilla de terror corta y narrativa — es el marco del análisis.', 'Catorce capítulos cortos llenan las 2,5 horas. Nueve son capítulos jugables de localizaciones como los Burrows Apartments, el Quick Fix y la Lazar’s Blood Bank; el resto son interludios Aftermath que devuelven cada historia de víctima al expediente de Slater.'] },
      { title: 'Lo que el análisis elogia', paragraphs: ['Los capítulos de víctimas son la cima. El analista llama a la apertura con Fefe en el apartamento el capítulo más tenso del juego, y el resto de jornadas mantiene el nivel: turnos comunes — servir perritos calientes, rellenar donas, rebobinar cintas — mientras una figura enmascarada se acerca. Esa ironía dramática es el mejor truco del diseño.', 'La presentación recibe la segunda ronda de elogios: las secuencias FMV estilo VHS, la banda sonora synthwave retro y el reparto totalmente doblado le dan al juego su identidad grindhouse. El guion también convence — Carrion City está llena de personajes grotescos a propósito, y según el eslogan de la editora todavía hay una última risa antes de la muerte.'] },
      { title: 'Lo que el análisis critica', paragraphs: ['Los dos modos de juego siguen siendo superficiales en mecánica. Los capítulos de investigación se reducen a áreas pequeñas y tareas cortas, y los de caza apuestan por bucles breves de interacción. La frase del analista: la mecánica parece algo repetitiva — a lo largo de 14 capítulos, el vocabulario de interacción casi no crece.', 'Es por eso que el veredicto recae en gusto adquirido, y no en recomendación universal. El análisis trata la mecánica superficial como el precio del humor y del ritmo, sin afirmar que los sistemas sean profundos.'] },
      { title: 'La cuestión de la nota', paragraphs: ['Bloody Disgusting puntúa con calaveras, no con números, y el veredicto sobre The Skin Stapler es una broma con utilidad: a los fans de Sniper Killer o Rewind or Die se les suma una calavera, a todos los demás se les resta una. No existe nota numérica que citar — cualquier nota de otro sitio que veas ligada a este juego merece verificación en la página original del medio.', 'En la traducción práctica: para el público objetivo, el análisis es una recomendación clara; fuera de él, un pase. El analista recibió, según la propia difusión, una copia proporcionada por la editora — práctica común, revelada en el propio análisis.'] },
      { title: 'Lo que añaden los números de los jugadores', paragraphs: ['El público del lanzamiento confirmó el tono del juego. La partida completa de CaseOh superó las 2.102.706 visualizaciones tras el 9 de agosto de 2026, y el vídeo de Joe Bartolozzi rebasó el 1,37 millón en la semana siguiente — el humor en clips llega mucho más allá de las 2,5 horas. Steam registraba en la ventana de lanzamiento cerca del 90% de reseñas positivas entre unos 340 votos.', 'Los números no responden a la cuestión del gusto — un millón de visualizaciones de una escena de perrito caliente no es un análisis —, pero muestran qué momentos abraza el público.'] },
      { title: 'Cómo decidir en tres pasos', paragraphs: [], bullets: ['Juega primero la demo gratuita: tres tramos — comisaría, Quick Fix y Gutters End — muestran tono y ritmo en 30 a 45 minutos', 'Mira un capítulo de víctima: pocos minutos de un turno de trabajo revelan si tensión más comedia funciona para ti; los vídeos de CaseOh y Joe Bart son la muestra más rápida sin spoiler del final', 'Compra por la historia, no por los sistemas: con 2,5 horas y 14,99 euros en Steam, el valor es una historia grindhouse vista de una sentada con doblaje completo — dentro de ese marco, las críticas pesan menos'] }
    ],
    faq: [
      { question: '¿Cuánto dura The Skin Stapler?', answer: 'Cerca de 2,5 horas para la ruta principal de 14 capítulos; las partidas grabadas con exploración quedan entre 2h46 y 3 horas aproximadamente.' },
      { question: '¿The Skin Stapler da miedo o hace reír?', answer: 'Las dos cosas, por decisión de diseño. Los capítulos de víctimas trabajan la tensión mientras los diálogos, cortes FMV y secundarios grotescos entregan las risas — el análisis llama a la mezcla macabra y graciosa a la vez.' },
      { question: '¿Los analistas recibieron copia gratis?', answer: 'Sí. Bloody Disgusting revela que la copia de análisis fue proporcionada por la editora — práctica común, declarada en el propio análisis.' },
      { question: '¿Existe nota numérica?', answer: 'No. El medio puntúa con calaveras: una más para fans de Sniper Killer y Rewind or Die, una menos para todos los demás.' },
      { question: '¿Qué dicen los jugadores en comparación con los críticos?', answer: 'La misma división: cerca del 90% de reseñas positivas en Steam en la ventana de lanzamiento, y la crítica más común repite la del análisis — mecánica ligera y duración corta.' }
    ],
    sources: sourceSets.review
  },
  story: {
    id: 'story', keyword: 'The Skin Stapler historia',
    title: 'The Skin Stapler historia: trama y final explicados',
    description: 'La historia de The Skin Stapler: Dick Slater caza al Skin Stapler por la Carrion City de 1984 — motivo, identidad, cintas y el único final en el Flesh Pit.',
    eyebrow: 'Trama con spoilers',
    directAnswer: 'En 1984, el detective Dick Slater caza a un asesino en serie por la Carrion City mientras el juego alterna entre las víctimas y el propio asesino. El asesino es Elias Crow, dueño de la parrilla Flesh Pit, y el motivo es la venganza: Slater mató a su hermano gemelo, Silus Kain. La historia dura cerca de 2,5 a 4 horas en 14 capítulos cortos y tiene exactamente un final.',
    date: '2026-09-03',
    sections: [
      { title: 'La historia en resumen', paragraphs: ['Estos hechos forman la estructura de la trama — las secciones siguientes detallan cada uno:'], bullets: ['Escenario: Carrion City, 1984', 'Investigador: el detective Dick Slater, junto al novato Robbie Knox', 'Asesino: Elias Crow, dueño de la parrilla Flesh Pit', 'Motivo: venganza por el hermano gemelo Silus Kain, muerto a manos de Slater', 'Estructura: 9 capítulos jugables de localizaciones + 4 partes de Aftermath + el Final Aftermath', 'Duración: cerca de 2,5 horas en línea recta; partidas más largas rozan las 4 horas', 'Finales: un único final de trama principal, sin ramificaciones'] },
      { title: 'La premisa', paragraphs: ['La premisa oficial de la tienda inicia la historia con un patrón oscuro: las víctimas son desolladas, la piel queda grapada en las paredes cercanas, y cintas de audio distorsionadas dejadas en las escenas provocan a la policía. Slater, un detective desgastado, recibe el caso — y el gancho es que no juegas solo la investigación: pasas capítulos dentro de la vida de quien está siendo perseguido.', 'Esa estructura doble es el motor de la historia. Un capítulo te pone en el escritorio de Slater en la comisaría de Carrion City; el siguiente, en un apartamento, una tienda o una bolera, mientras el perseguidor se acerca. Los interludios Aftermath devuelven cada historia de víctima al expediente, hasta que la investigación señala a un sospechoso.'] },
      { title: 'Cómo los 14 capítulos cuentan la historia', paragraphs: ['La ruta jugable: Burrows Apartments con Fefe en la apertura, Carrion City Police Department con Slater, Quick Fix con Hexy, Gutters End con Blair, la donut shop de Luna, Underworld VHS con Scaroline y la Lazar’s Blood Bank con la enfermera Layna. Cuatro interludios Aftermath quedan entre los capítulos de localizaciones, y el Final Aftermath conecta la investigación con el tramo final. Después llega Closing In, y The Flesh Pit cierra la historia.', 'La lista de logros de Steam confirma exactamente esa secuencia de capítulos, y la guía de referencia marca los tiempos: Burrows Apartments a las 00:03:06 hasta The Flesh Pit a las 02:34:00.'] },
      { title: 'La identidad del asesino: Elias Crow', paragraphs: ['La investigación avanza hacia una única revelación: el Skin Stapler es Elias Crow, el dueño público de la Flesh Pit, anunciada en el juego como la mejor barbacoa de la ciudad. El nombre queda escondido a plena vista — el anuncio de la Flesh Pit aparece pronto, y diálogos del final del juego afirman directamente que Elias Crow es el dueño del restaurante.', 'La revelación funciona porque el juego reparte las piezas entre las perspectivas: archivos de sospechosos, el anuncio de la Flesh Pit, cintas de las escenas del crimen y los segmentos Aftermath guardan un fragmento cada uno, y los detectives lo montan todo en pantalla en vez de recibir una exposición única.'] },
      { title: 'El origen de los gemelos y el motivo', paragraphs: ['El motivo es la espina dorsal emocional de la historia: Slater mató al hermano gemelo de Elias, Silus Kain, y Elias construye su cadena de crímenes para infligir a Slater una pérdida equivalente. Un diálogo del final del juego resume: Dick, mataste a su hermano, y ahora Elias quiere venganza.', 'Una grabación del orfanato, con la voz del Padre Omani, explica cómo dos hermanos acabaron en lados opuestos del mismo caso: los gemelos fueron separados al nacer, uno entregado a la familia Ken y llamado Silus, el otro a la familia Crow y llamado Elias. Los subtítulos automáticos escriben el apellido como Kane o Ken en algunos puntos; este sitio estandariza Kain, la grafía usada en las páginas de guía y final.'] },
      { title: 'Cómo las cintas mueven la trama', paragraphs: ['Las cintas de audio distorsionadas son el tejido conjuntivo de la historia. El asesino las deja en las escenas para provocar a la policía, y repararlas y analizarlas se volvió tarea constante de la investigación — el logro Jank Ya Later! de Steam se desbloquea precisamente por reparar las cintas del Skin Stapler. La grabación del orfanato, la pista más profunda de la historia, también llega en cinta.', 'Capítulos individuales alimentan el hilo de las cintas: un VHS recuperado de la escena de Luna entra en el caso, y el capítulo de Scaroline en Underworld VHS transcurre justo en el videoclub donde manipular cintas es el trabajo.'] },
      { title: 'El final: una confrontación en el Flesh Pit', paragraphs: ['La historia tiene un final, y dos partidas completas independientes confirman la misma secuencia. Slater rastrea al asesino hasta la Flesh Pit, el restaurante del propio Elias. Elias gana la ventaja primero: Robbie Knox cae abatido, y Elias presiona a Slater para que tome el arma de Robbie. Slater la toma, dispara a Elias y deja Carrion City.', 'No existe menú moral, diálogo ramificado ni final alternativo. Lo que pasa con Elias después — muerte en el sitio o arresto — queda sin respuesta en las grabaciones verificadas. En cualquier caso, el detective deja la ciudad, y la historia termina donde empezó: Slater, el caso y una ciudad que les quitó todo a los dos hermanos.'] },
      { title: 'Cómo vivir la historia', paragraphs: [], bullets: ['Juega los capítulos de localizaciones en el orden de la ruta: el juego es lineal, y cada giro desemboca directo en el siguiente; la selección de capítulos existe para replays', 'Trata cada interacción con cintas: las cintas reparadas son dispositivos de trama primero y logros después — la grabación del orfanato y las cintas de las escenas son las dos mayores revelaciones', 'No te saltes los interludios Aftermath: las cuatro partes y el Final Aftermath conectan los capítulos de víctimas con el caso de Slater; sin ellos, la línea narrativa se rompe'] }
    ],
    faq: [
      { question: '¿Quién es el Skin Stapler en la historia?', answer: 'Elias Crow, dueño de la parrilla Flesh Pit. La investigación revela su identidad al final del juego, y la confrontación final ocurre en el restaurante.' },
      { question: '¿Por qué mata el Skin Stapler a las víctimas?', answer: 'Venganza. Slater mató a su hermano gemelo Silus Kain, y Elias monta los asesinatos como respuesta — víctimas desolladas, piel grapada en las paredes y cintas provocadoras para la policía.' },
      { question: '¿Cuánto dura la historia?', answer: 'Cerca de 2,5 horas en línea recta por los 14 capítulos; las partidas grabadas con más exploración rozan las 3 horas, y las primeras jugadas más lentas pueden alcanzar las 4.' },
      { question: '¿Slater atrapa al asesino?', answer: 'Sí. La historia termina en la Flesh Pit, donde Slater dispara a Elias después de que Robbie caiga abatido y deja Carrion City.' },
      { question: '¿La historia está conectada con la demo?', answer: 'Los tres tramos de la demo — comisaría, Quick Fix y Gutters End — son el segundo, tercer y cuarto capítulo de la historia en forma resumida. El juego completo empieza desde el principio, en el apartamento de Fefe.' }
    ],
    sources: sourceSets.story
  },
  'games-like': {
    id: 'games-like', keyword: 'juegos como The Skin Stapler',
    title: 'Juegos como The Skin Stapler: los 6 parecidos más cercanos',
    description: 'Sniper Killer, Rewind or Die y los cuatro terrores anteriores de Tainted Pact: los juegos más parecidos a The Skin Stapler y qué comparte cada uno.',
    eyebrow: 'Recomendaciones de juegos',
    directAnswer: 'Los juegos más parecidos a The Skin Stapler son Sniper Killer y Rewind or Die — los dos títulos citados por el análisis de Bloody Disgusting como comparaciones directas — más los cuatro terrores anteriores de la misma desarrolladora, Tainted Pact: Suffer the Night, Terror at Oakheart, Massacre at the Mirage y Flesh Made Fear. Los seis comparten la duración corta, el humor grindhouse y la presentación de terror low-poly que definen The Skin Stapler.',
    date: '2026-09-03',
    sections: [
      { title: 'Los parecidos en resumen', paragraphs: ['Las comparaciones vienen de dos direcciones: el análisis que cita Sniper Killer y Rewind or Die, y el catálogo de la desarrolladora y la editora que lista los cuatro títulos de Tainted Pact:'], bullets: ['Sniper Killer — citado por el análisis como la comparación más cercana: premisa de asesino en serie, ritmo de job-sim, visuales PSX', 'Rewind or Die — la otra comparación directa del análisis: estética VHS, mecánicas de cinta, humor grindhouse', 'Suffer the Night — primer terror publicado de Tainted Pact: analog horror con informática retro inquietante', 'Terror at Oakheart — Tainted Pact: slasher en un campamento con violencia estilizada y tono de serie B', 'Massacre at the Mirage — Tainted Pact: slasher confinado a un hotel con estructura corta por escenas', 'Flesh Made Fear — Tainted Pact: el predecesor directo de The Skin Stapler, historia de asesino en serie con escenas dobladas'] },
      { title: 'Por qué Sniper Killer es el match número 1', paragraphs: ['Sniper Killer combina la caza de un asesino en serie con tareas mundanas de trabajo y una estética PSX deliberadamente fea — el mismo esqueleto sobre el que se construyó The Skin Stapler. Quien analizó The Skin Stapler lo cita por su nombre, lo que lo convierte en la compra más segura para quien quiere lo más cerca de otro caso en Carrion City.', 'El tono también coincide: los dos juegos tratan el material grotesco con seriedad y descaro a la vez, apuestan por diálogos doblados y envuelven una historia corta en interacciones simples. Si tu parte favorita fue la investigación, Sniper Killer es la experiencia más cercana; si fueron los turnos de las víctimas, el catálogo de Tainted Pact es el mejor camino.'] },
      { title: 'Por qué Rewind or Die aparece siempre', paragraphs: ['Rewind or Die comparte el ADN de videoclub retro que The Skin Stapler exhibe sin disfraz — estética VHS, mecánicas de cinta y guion de slasher movido a chistes. El análisis lo cita junto a Sniper Killer como prueba de público: los fans de cualquiera de los dos son el perfil que suma una calavera a la nota de The Skin Stapler.', 'También es el match correcto para quien más disfrutó el capítulo de Scaroline en Underworld VHS: el videoclub, el rebobinado de cintas y el humor de vídeo analógico apuntan en la misma dirección.'] },
      { title: 'Los cuatro terrores anteriores de Tainted Pact', paragraphs: ['Tainted Pact hizo The Skin Stapler en solitario, y el catálogo del estudio lista cuatro títulos anteriores, confirmados por el anuncio de la editora y por el catálogo de GOG:'], bullets: ['Suffer the Night — el debut de analog horror del estudio, construido en torno a un ordenador retro embrujado y una figura que persigue desde dentro de un juego ficticio', 'Terror at Oakheart — un slasher en un campamento, manteniendo la estructura corta y la violencia estilizada en pantalla', 'Massacre at the Mirage — un slasher confinado a un hotel, con el mismo ritmo escena a escena y escritura de comedia negra', 'Flesh Made Fear — el predecesor más directo: historia de asesino en serie con escenas dobladas y puntaza grindhouse que desemboca de forma natural en la Carrion City'] },
      { title: 'Qué comparten estos juegos más allá del tono', paragraphs: ['Las semejanzas son estructurales, no solo visuales:'], bullets: ['Duraciones cortas: The Skin Stapler dura cerca de 2,5 horas en 14 capítulos; los comparables son todos juegos de una sentada', 'Bucles de job-sim e interacciones tipo QTE: servir perritos calientes, rellenar donas, rebobinar cintas — la tarea mundana como motor del terror es la firma del género', 'Repartos totalmente doblados: The Skin Stapler acredita diez intérpretes con nombre, y el grupo de comparación también prefiere doblaje completo a texto', 'Bandas sonoras synth retro: temas de sintetizador estilo Carpenter atraviesan todo el catálogo', 'FMV y rigor de formato de vídeo: secuencias full-motion estilo VHS son la cola de presentación de estos juegos', 'Humor deliberadamente basto: el eslogan de la editora — espera una última risa antes de morir — resume el registro cómico compartido'] },
      { title: 'Cómo elegir el próximo juego en tres pasos', paragraphs: [], bullets: ['Empareja con el capítulo que más te gustó: la investigación apunta a Sniper Killer; el videoclub a Rewind or Die; los turnos de las víctimas a Flesh Made Fear y los juegos anteriores de Tainted Pact', 'Comprueba la duración que buscas: todos son cortos — si quieres otra historia de 2 a 4 horas de una sentada, cualquiera sirve; si quieres inversión larga, ninguno es la estantería correcta', 'Compra en tiendas oficiales: el catálogo de Tainted Pact se vende en Steam y GOG, y la guía de descarga de PC lista las tiendas oficiales del título más nuevo'] }
    ],
    faq: [
      { question: '¿Existe una secuela u otro juego exactamente como The Skin Stapler?', answer: 'No hay secuela directa. Flesh Made Fear es el juego anterior más cercano del mismo estudio, y Sniper Killer es el match más cercano fuera de él.' },
      { question: '¿Los juegos de Tainted Pact están conectados en la historia?', answer: 'No hay universo compartido confirmado entre los cuatro títulos anteriores y The Skin Stapler. La conexión es tono, formato y desarrolladora, no trama.' },
      { question: '¿Qué juego jugar primero después de The Skin Stapler?', answer: 'Sniper Killer: la crítica lo cita como la comparación directa, y su bucle de investigación de asesino en serie refleja de cerca los capítulos de Slater.' },
      { question: '¿Estos juegos tienen el mismo humor?', answer: 'Sí — chistes grindhouse, secundarios grotescos e interpretación de serie B son el registro compartido, resumido por el eslogan de la editora.' },
      { question: '¿Alguno está en Game Pass o en servicios de suscripción?', answer: 'La disponibilidad en suscripción cambia por servicio y región — revisa la página actual de cada juego. Steam y GOG siguen siendo los canales de compra confirmados del catálogo.' }
    ],
    sources: sourceSets['games-like']
  },
  uncensored: {
    id: 'uncensored', keyword: 'The Skin Stapler sin censura',
    title: 'The Skin Stapler sin censura: versiones, contenido y clasificación',
    description: 'The Skin Stapler no tiene versión censurada: Steam y GOG distribuyen un único build sin cortes — mira qué muestra el juego y cómo comprobarlo antes de comprar.',
    eyebrow: 'Contenido y versiones',
    directAnswer: 'The Skin Stapler no se vende en versión censurada. Steam y GOG distribuyen un único build sin cortes — el mismo juego de 14 capítulos con el gore intacto —, y no existe SKU "sin censura" separado, corte regional ni interruptor de contenido en ninguna de las tiendas. La descripción oficial de lo que el asesino hace a las víctimas aparece en las propias páginas de compra, sin endulzar.',
    date: '2026-09-03',
    sections: [
      { title: 'Qué significa una versión única en la práctica', paragraphs: ['Lo que ves en la página de la tienda es lo que viene en el disco. No hay nada que desbloquear, nada que alternar ni ninguna edición más ligera que comprar en su lugar:'], bullets: ['Steam: un juego base (App 4310610) más dos DLC; ninguna versión cortada separada', 'GOG: un juego completo; las skins del DLC vienen incluidas en el build de GOG', 'Interruptor de contenido: ninguno anunciado en ninguna página de tienda', 'Cortes regionales: ninguno ofrecido ni documentado en las páginas oficiales', 'Clasificación por edades: ninguna PEGI o ESRB mostrada en las páginas de las tiendas', 'Intensidad del contenido: víctimas desolladas, piel grapada, cintas distorsionadas, material sexual y personajes grotescos'] },
      { title: 'Qué incluye el contenido sin censura', paragraphs: ['La mecánica que da título al juego es el propio aviso de contenido. Las víctimas son desolladas y tienen la piel grapada en las paredes — el texto oficial de la tienda lo describe como la firma del asesino, y el juego escenifica las escenas del crimen en torno a ese método. Las imágenes de piel cosida de la galería oficial representan lo que el juego muestra en el motor.', 'El análisis de Bloody Disgusting completa el perfil de intensidad: violencia gráfica, material sexual y personajes deliberadamente grotescos. El marketing de la propia editora se sumerge en el mismo registro — el material de prensa promete una última risa antes de morir, y los chistes del juego suenan en la misma frecuencia de comedia enferma que el gore. Quien busca una versión sin censura suele buscar en la dirección equivocada: el juego nunca fue suavizado.'] },
      { title: 'Por qué no existe SKU separado sin censura', paragraphs: ['La estructura de productos de Steam vuelve la respuesta estructural: la tienda lista una aplicación base más dos DLC — un paquete de skins cosméticas y una banda sonora — sin builds alternativos. La página de GOG lo refleja con un único juego que agrega el DLC de skins. Una variante censurada exigiría una segunda entrada en la tienda, un interruptor en el lanzamiento o una nota regional, y nada de eso existe en la distribución oficial del juego.', 'Esa estructura también responde búsquedas como "parche sin censura" o "contenido restaurado": no hay nada eliminado que restaurar. El build único de la desarrolladora es el build completo, y la guía de descarga de PC lista las dos tiendas oficiales que lo venden.'] },
      { title: 'Clasificación por edades y bloqueos de las tiendas', paragraphs: ['Ni Steam ni GOG muestran clasificación PEGI o ESRB para The Skin Stapler — común en lanzamientos indie pequeños que venden por tiendas digitales sin distribución en el comercio. Las tiendas aplican sus propios bloqueos de edad en el momento de la compra. Si la clasificación importa para tu casa o para las reglas de tu región, revisa el listado local antes de comprar — los descriptores de contenido anteriores son la mejor vista previa de lo que el juego contiene.', 'La demo sigue la misma política: es gratuita, contiene la misma violencia estilizada y no lleva clasificación separada en su página. La guía de la demo cubre lo que incluyen los tres tramos.'] },
      { title: 'Cómo comprobar el contenido en tres pasos', paragraphs: [], bullets: ['Abre la galería de Steam: las capturas oficiales muestran el renderizado real del juego — retratos de piel cosida, escenas del crimen y la obra del asesino — sin suavizado editorial', 'Mira un capítulo grabado: las partidas completas de la apertura de Fefe y del tramo de Quick Fix son públicas y muestran cómo se escenifica la violencia y con qué frecuencia aparece', 'Lee la descripción de la tienda en voz alta: víctimas desolladas, piel grapada, cintas provocadoras — el pitch oficial es el aviso de contenido más honesto disponible, y las dos tiendas lo muestran en la página de compra'] }
    ],
    faq: [
      { question: '¿The Skin Stapler está censurado en Steam?', answer: 'No. Steam vende un único build sin cortes, y la propia descripción de la tienda describe la violencia firma del juego sin endulzar.' },
      { question: '¿La versión de GOG es distinta a la de Steam?', answer: 'El lanzamiento en GOG es el mismo juego sin cortes e incluye el DLC cosmético Skin Jankers en la compra. En Steam, ese DLC se vende aparte. Ninguna de las tiendas ofrece corte de contenido diferente.' },
      { question: '¿Existe un interruptor para apagar el gore?', answer: 'Ningún interruptor de contenido está anunciado en las páginas de las tiendas. El juego viene con la violencia como parte central de su identidad.' },
      { question: '¿Por qué no encuentro una clasificación por edades del juego?', answer: 'Ninguna PEGI o ESRB aparece en las páginas de las tiendas. Los lanzamientos indie digitales a menudo prescinden de clasificación formal y dependen de los bloqueos de las tiendas — revisa el listado de tu región antes de comprar.' },
      { question: '¿La demo contiene el mismo contenido?', answer: 'Sí. La demo gratuita muestra la misma violencia estilizada en sus tres tramos jugables — justamente por eso funciona como vista previa de contenido antes de la compra.' }
    ],
    sources: sourceSets.uncensored
  },
  'donut-shop': {
    id: 'donut-shop', keyword: 'The Skin Stapler código de la donut shop',
    title: 'The Skin Stapler código de la donut shop: no existe — y qué hacer',
    description: 'No hay código en la Luna’s Cream Filled Donuts: el capítulo es un turno de atención. Mira lo que existe de verdad, el código 1979 y el logro del capítulo.',
    eyebrow: 'Códigos y capítulos',
    directAnswer: 'No existe código de donut shop en The Skin Stapler. La Luna’s Cream Filled Donuts es un capítulo jugable de trabajo — rellenas pedidos de donas y café paso a paso —, sin caja fuerte, sin teclado numérico y sin contraseña. El juego no trae código de canje, contraseña maestra ni código de salto de capítulo; el único código numérico real es 1979, del cuadro de fotos durante la investigación.',
    date: '2026-09-03',
    sections: [
      { title: 'Lo que el capítulo de la donut shop pide de verdad', paragraphs: ['La lista de logros de Steam confirma el nombre y la posición del capítulo, y las partidas completas confirman el formato: es un bucle de atención con el mismo molde que la secuencia de perritos calientes de Hexy en el Quick Fix, no una caja de puzle:'], bullets: ['Nombre del capítulo: Luna’s Cream Filled Donuts (lista oficial de logros de Steam)', 'Personaje jugable: Luna, dueña de la tienda', 'Posición en la ruta: entre Gutters End y Underworld VHS — el quinto capítulo de localización', 'Tipo de objetivo: trabajo de atención en varios pasos — donas y café en secuencia', 'Código o contraseña: ninguno — el progreso viene de completar los pasos de la atención', 'Logro relacionado: LunaArcana - Glazed and Confused, por completar el capítulo'] },
      { title: 'Por qué los jugadores buscan un código de donut shop', paragraphs: ['Dos juegos distintos se mezclan en las búsquedas. El primero es el propio The Skin Stapler: es un juego de terror lleno de imágenes de códigos — teclados numéricos, evidencias, cajones cerrados —, así que los jugadores asumen que cada localización con nombre esconde una contraseña. El segundo es el hábito del género: los juegos de terror estilo PSX suelen usar códigos numéricos, y los buscadores completan el patrón aunque este juego concreto no tenga ese puzle.', 'El código numérico real de The Skin Stapler vive en otro lugar: el candado del cuadro de fotos en la línea de investigación, cuya solución es 1979. Si llegaste aquí cazando una respuesta de cuatro dígitos, 1979 es el único código que el juego usa de verdad.'] },
      { title: 'Cómo progresa el capítulo', paragraphs: [], bullets: ['Empieza el turno: el capítulo de Luna abre en el mostrador, y el aviso de objetivo te lleva al flujo de atención — los objetivos en pantalla son el único tutorial que necesitas', 'Rellena cada pedido en secuencia: donas y café siguen la preparación en varios pasos que el juego muestra; terminar un pedido libera al siguiente cliente, exactamente como en el bucle del Quick Fix', 'Completa el turno para avanzar la historia: el capítulo termina cuando la atención acaba y la escena de la trama ocurre — no hay código escondido ni candado opcional; el logro cae al final del capítulo'] },
      { title: 'Los códigos que realmente existen en el juego', paragraphs: ['Las respuestas confirmadas de puzles son pocas y documentadas: el código 1979 del cuadro de fotos en los capítulos de investigación, el puzle de la báscula de carne en la Flesh Pit y las interacciones con las cintas dañadas que alimentan la historia y liberan el logro de reparación. Ninguna se conecta con la donut shop de Luna, y ninguna usa un código de texto para canjear.', 'Tampoco existe código universal de salto. La guía completa señala que las afirmaciones de contraseña maestra o salto de capítulo no tienen apoyo en ninguna partida completa — la ruta avanza cumpliendo objetivos, y punto.'] }
    ],
    faq: [
      { question: '¿Cuál es el código de la donut shop en The Skin Stapler?', answer: 'No existe. Luna’s Cream Filled Donuts es un capítulo de atención, y el juego no tiene código para él. El único código de cuatro dígitos es 1979, usado en el candado del cuadro de fotos durante la investigación.' },
      { question: '¿El capítulo de la donut shop está en la demo?', answer: 'No. La demo gratuita incluye tres tramos — comisaría, Quick Fix y Gutters End. La tienda de Luna es contenido del juego completo.' },
      { question: '¿Cómo desbloqueo el logro Glazed and Confused?', answer: 'Completa el capítulo Luna’s Cream Filled Donuts. El logro cae al final del capítulo; no hay condición escondida, orden secreta ni código involucrado.' },
      { question: '¿Quién es Luna?', answer: 'Luna administra la tienda de donas y café y es una de las perspectivas jugables del juego. La guía de personaje de Luna cubre su papel, su actriz de doblaje y su lugar en la historia.' },
      { question: '¿Por qué Google sugiere un código de donut shop?', answer: 'Los buscadores mezclan las imágenes de teclado y códigos del juego con hábitos de otros terrores estilo PSX. El autocompletado no refleja un puzle real de este juego.' }
    ],
    sources: sourceSets['donut-shop']
  },
  'all-tapes': {
    id: 'all-tapes', keyword: 'The Skin Stapler cintas',
    title: 'The Skin Stapler cintas: todas las grabaciones y el logro',
    description: 'Las cintas de The Skin Stapler: provocaciones a la policía, evidencias de la investigación, la cinta del orfanato y el logro Jank Ya Later! de reparación.',
    eyebrow: 'Cintas y evidencias',
    directAnswer: 'Las cintas son la voz del asesino en la historia de The Skin Stapler: grabaciones de audio distorsionadas dejadas en las escenas del crimen para provocar a la policía, más las grabaciones de la investigación que arman el caso. Recoges, reparas y revisas cintas a lo largo de la ruta, y el logro Jank Ya Later! se desbloquea específicamente por arreglar las cintas del Skin Stapler. El juego nunca muestra un contador total, así que la cuenta exacta de cintas reparables es un detalle que verificarás en el juego.',
    date: '2026-09-03',
    sections: [
      { title: 'Qué son las cintas y qué hacen', paragraphs: ['Seis funciones, tres papeles: las cintas son atmósfera, evidencia y dispositivo de trama al mismo tiempo. Las secciones siguientes recorren cada papel y muestran dónde entra el trabajo con cintas en la ruta de capítulos:'], bullets: ['Papel oficial: grabaciones que provocan a la policía en las escenas del crimen (descripción de la tienda)', 'Papel de juego: objetos que reparas y revisas como evidencia de la investigación', 'Papel en la historia: llevan la voz del asesino y la pista del origen de los gemelos', 'Mecánica de reparación: las cintas dañadas se arreglan a lo largo de la ruta; no existe código universal de reparación', 'Logro: Jank Ya Later! — Fix The Skin Stapler Tapes', 'Cuenta total: no mostrada en el juego ni publicada en material oficial'] },
      { title: 'Las cintas de provocación: el asesino habla con la policía', paragraphs: ['La premisa oficial es explícita: las víctimas son desolladas y grapadas en las paredes, y cintas de audio distorsionadas dejadas en las escenas provocan a la policía. Esas grabaciones dan voz al asesino sin mostrarlo nunca — el audio del inicio es grotesco a propósito, y enmarca la investigación como una conversación que el asesino mantiene con Slater por medio de las escenas del crimen.', 'Las cintas de provocación también definen el tono de la historia. La crítica marca la comedia negra como rasgo definitorio, y el audio de las cintas es donde ese registro suena más alto: el asesino actúa para los investigadores, y la entrega distorsionada de era VHS vuelve los chistes más fríos.'] },
      { title: 'Las cintas de la investigación: el expediente en forma de audio', paragraphs: ['Además de las provocaciones, el bucle de reparar y revisar convierte las cintas en evidencia. Cintas dañadas aparecen por los capítulos, y el juego exige arreglarlas o revisarlas antes de que la investigación avance — la lista de logros de Steam nombra la actividad directamente, y las partidas completas muestran a Slater manejando reparaciones en el tramo final, en la radio de DJ Woolz.', 'Ese tramo de reparación es donde el hilo de las cintas se paga en mecánica: arreglar las cintas del Skin Stapler es requisito nombrado de logro, y las grabaciones reparadas alimentan las revelaciones que cierran el caso. Si una interacción de cinta parece atascada, la solución casi siempre es un diálogo sin terminar o un objetivo pendiente en la misma sala — la guía lista las puertas de interacción de la ruta en orden.'] },
      { title: 'La cinta del orfanato: la mayor revelación de la historia', paragraphs: ['Una grabación pesa más que todas. El audio del orfanato, con la voz del Padre Omani, revela que el asesino y su hermano eran gemelos separados al nacer — uno entregado a la familia Ken y llamado Silus, el otro a la familia Crow y llamado Elias. Esa única grabación convierte la historia de asesino en serie provocador en una historia de venganza contra el propio Slater.', 'El hilo de las cintas atraviesa cada beat importante: el VHS recuperado de la escena de Luna, la cinta que Scaroline maneja en Underworld VHS, la grabación de ven a encontrarme del final y la grabación privada del propio Slater alimentan la misma cadena de revelaciones. La guía de la historia presenta la trama completa con spoilers, y la página de identidad rastrea la revelación pista por pista.'] },
      { title: 'Dónde entra el trabajo con cintas en la ruta', paragraphs: [], bullets: ['Capítulos de investigación: los tramos de Slater en la CCPD abren el bucle de cintas — grabaciones de las escenas entran en el expediente y las tareas de reparación empiezan', 'Capítulos de trabajo: la tienda de Luna y el Underworld VHS de Scaroline atan cintas físicas a la historia: una se vuelve evidencia de escena del crimen, la otra convierte manejar cintas en un trabajo jugable', 'La sesión de reparación del final del juego: el tramo de Closing In incluye la visita a la radio donde las cintas dañadas se arreglan — completar ese trabajo satisface la Jank Ya Later! y cierra la cadena de evidencias antes del final'] },
      { title: 'Afirmaciones de la comunidad sobre las cintas', paragraphs: ['Una wiki de fans relata pequeñas diferencias de epílogo según las cintas que escuches — una afirmación que circula en todo juego de terror con audio coleccionable. Partidas completas comparadas mostrando finales distintos nunca aparecieron; dos jugadas completas independientes muestran el mismo final, independientemente del manejo de las cintas. Hasta que alguien publique dos partidas pareadas divergentes, trata la estructura de final único como el hecho operativo.', 'El mismo escepticismo vale para las cuentas. Sin contador en el juego ni número oficial, cualquier total visto por ahí es, como mucho, estimación de jugador — la respuesta honesta es que el juego no presenta una.'] }
    ],
    faq: [
      { question: '¿Cuántas cintas hay en The Skin Stapler?', answer: 'El juego no muestra un total, y el material oficial no publica uno — la cuenta exacta solo se confirma jugando. Lo confirmado es la mecánica: recoger, reparar y revisar según la ruta lo pide.' },
      { question: '¿Cuál es el logro de las cintas?', answer: 'Runebee - Jank Ya Later!, que se desbloquea por arreglar las cintas del Skin Stapler según el texto oficial de requisito de Steam.' },
      { question: '¿Las cintas cambian el final?', answer: 'Una wiki de fans afirma variación en el epílogo, pero ninguna partida pareada lo ha demostrado. Dos jugadas completas confirman el mismo final único.' },
      { question: '¿Dónde reparo las cintas?', answer: 'El tramo final de la ruta lleva las cintas dañadas a la radio de DJ Woolz durante Closing In, según las partidas completas — la guía lo coloca cerca de 02:18:29 en la partida de referencia.' },
      { question: '¿Las cintas son la voz del asesino?', answer: 'Sí — la descripción de la tienda dice que cintas distorsionadas provocan a la policía, y la grabación clave, la del orfanato, expone el origen de los gemelos que explica el motivo del asesino.' }
    ],
    sources: sourceSets['all-tapes']
  },
  'ai-generated': {
    id: 'ai-generated', keyword: '¿The Skin Stapler es generado por IA?',
    title: '¿The Skin Stapler es generado por IA? Lo que muestra la página oficial',
    description: 'No: Steam estampa "A HANDCRAFTED HORROR EXPERIENCE". Evidencias verificables — 10 actores de doblaje con nombre, una desarrolladora en solitario y FMV artesanales.',
    eyebrow: 'Producción y créditos',
    directAnswer: 'No — The Skin Stapler no es generado por IA, y la propia página de Steam lo dice arriba: "A HANDCRAFTED HORROR EXPERIENCE — handmade horror, with no shortcuts". Detrás de la declaración hay trabajo humano verificable: una desarrolladora en solitario que construyó el juego en público durante un año, diez actores de doblaje con nombre en el póster oficial del reparto y secuencias FMV hechas a mano, elogiadas por la crítica.',
    date: '2026-09-03',
    sections: [
      { title: 'Lo que muestra el material oficial', paragraphs: ['Cada línea es comprobable: la página de la tienda exhibe la declaración handmade, el póster del reparto nombra a los intérpretes, y el listado lleva la línea de copyright de la editora. Nada de la producción del juego depende de una afirmación que haya que aceptar a ciegas:'], bullets: ['Titular de la tienda: "A HANDCRAFTED HORROR EXPERIENCE — handmade horror, with no shortcuts"', 'Desarrollo: desarrolladora en solitario Tainted Pact (Estados Unidos)', 'Reparto de voz: 10 intérpretes con nombre en el póster oficial del reparto', 'Presentación: secuencias FMV estilo VHS, elogiadas por la cobertura de crítica', 'Editora en la tienda: Assemble Entertainment GmbH (línea de copyright)', 'Datos de lanzamiento en Steam: 16 logros; cerca del 90% positivas entre aproximadamente 340 análisis'] },
      { title: 'La declaración oficial de handmade', paragraphs: ['La página de Steam abre con "handmade horror, with no shortcuts" como declaración destacada en la primera pantalla. Las frases de marketing no son prueba por sí solas, pero esta es inusualmente específica para una vitrina: compromete a la desarrolladora con assets artesanales y coincide con la huella de producción alrededor del juego — una persona desarrollando, un reparto de creadores y un año de diarios públicos de desarrollo.', 'El material de prensa de la editora repite el marco artesanal en vez de contradecirlo, y ningún canal oficial asociado al juego anuncia arte generado por IA, voces de IA ni escritura por IA. Para un lanzamiento pequeño que se vende por su personalidad grindhouse, esa consistencia entre canales es la señal pública más fuerte disponible.'] },
      { title: 'Diez humanos con nombre hacen las voces', paragraphs: ['El póster oficial del reparto acredita a diez intérpretes: RJ Green como Dick Slater, Daniel Suraci como Robbie Knox, HexyIRL como Hexy y el asesino del título, Layna Lazar como la enfermera Layna, Runebee como Bee, Luna Arcana como Luna, Blairvira como Blair, FeFe como Fefe, Scaroline como Scaroline y KingWoolz como DJ Woolz. Varios son creadores en activo con catálogos públicos — la guía de actores de doblaje mapea cada crédito.', 'Esto importa para la cuestión de la IA porque el doblaje es donde suele caer la sospecha. The Skin Stapler está totalmente doblado al inglés — Steam lista audio completo en inglés —, y cada papel principal corresponde a un intérprete con nombre que difunde el trabajo en sus propios canales. El reparto de creadores es además estrategia de marketing deliberada: la editora señala que el juego se hizo con apoyo de creadores de contenido, lo opuesto a un pipeline anónimo y generado.'] },
      { title: 'Una desarrolladora, construyendo en público', paragraphs: ['Tainted Pact es un estudio en solitario de Estados Unidos, y el desarrollo ocurrió en público: el canal de YouTube publicó Dev Logs en diciembre de 2025, y la presencia en itch.io documenta la senda de proyectos que llevó a The Skin Stapler. El desarrollo en solitario no descarta herramientas auxiliares, pero significa que cada asset pasó por un autor responsable, cuyos cuatro terrores anteriores — Suffer the Night, Terror at Oakheart, Massacre at the Mirage y Flesh Made Fear — muestran un estilo artesanal consistente evolucionando hasta este lanzamiento.', 'Las secuencias FMV vuelven visible el caso artesanal. La crítica elogia el vídeo full-motion estilo VHS como destaca de presentación; esas escenas se escenifican, se interpretan y se montan en el registro grindhouse del juego y llevan la misma estética low-poly de era PSX del resto del build. La guía de la desarrolladora presenta el estudio y la editora en detalle.'] },
      { title: 'Cómo comprobar el estatus de IA de cualquier juego en tres pasos', paragraphs: [], bullets: ['Lee la lista de destacados de la página de la tienda: Steam exige divulgar contenido de IA cuando aplica; la página de The Skin Stapler en cambio estampa la producción handmade — las secciones de divulgación son la señal oficial más rápida', 'Comprueba créditos y reparto: intérpretes con nombre, un póster publicado y canales públicos de creadores — como el póster de diez personas de este juego — son huellas humanas que el contenido generado no falsifica de forma convincente', 'Mira las imágenes reales: la consistencia de estilo en el catálogo de una desarrolladora en solitario es difícil de fingir; compara las escenas FMV con los juegos anteriores y los dev logs del estudio y la historia de la producción se cuenta sola'] },
      { title: '¿Esto importa para cómo se juega?', paragraphs: ['Para The Skin Stapler, la cuestión de lo handmade es sobre todo una cuestión de valores, y la respuesta apoya el propio pitch del juego: la comedia grindhouse de una desarrolladora en solitario con reparto de creadores es exactamente el tipo de producción que los jugadores tienen en mente cuando piden juegos hechos por humanos. El sentimiento del lanzamiento en la tienda — cerca del 90% positivas entre aproximadamente 340 análisis — sugiere que el público leyó lo mismo.', 'Los límites honestos: las listas de papeles en los créditos finales más allá del póster nunca fueron capturadas por completo, y ningún documento oficial detalla cada herramienta usada en el desarrollo. Lo que el registro público sostiene es la propia declaración de la tienda — terror artesanal, sin atajos — aplicada al arte, a las voces y a la historia del juego. La guía de Steam cubre el listado de la tienda por si quieres leer la declaración en su sitio.'] }
    ],
    faq: [
      { question: '¿The Skin Stapler usa arte generado por IA?', answer: 'La página oficial de la tienda vende el juego como terror handmade sin atajos, y el arte low-poly y las escenas FMV coinciden con el catálogo artesanal de una desarrolladora en solitario. Ningún canal oficial anuncia arte de IA para este título.' },
      { question: '¿Las voces son de IA?', answer: 'No. Diez intérpretes con nombre constan en el póster oficial del reparto, Steam lista audio completo en inglés, y los creadores difunden los papeles en sus propios canales — la guía del reparto lista a todos.' },
      { question: '¿Quién hizo The Skin Stapler?', answer: 'La desarrolladora en solitario Tainted Pact, con publicación de Assemble Entertainment. El juego debutó el 6 de agosto de 2026 para Windows PC.' },
      { question: '¿Por qué la página de la tienda dice "handmade horror"?', answer: 'Es la declaración de producción de la desarrolladora — "A HANDCRAFTED HORROR EXPERIENCE — handmade horror, with no shortcuts" —, y coincide con el historial público de desarrollo y el enfoque de reparto de creadores.' },
      { question: '¿El guion es generado por IA?', answer: 'Los diálogos llevan las voces de los intérpretes del póster y el humor grindhouse de la desarrolladora en una historia de autor único; ninguna fuente oficial describe herramientas de escritura por IA. La guía de la historia muestra lo construida que está la trama en torno a una única revelación.' }
    ],
    sources: sourceSets['ai-generated']
  },
  developer: {
    id: 'developer', keyword: 'desarrollador de The Skin Stapler',
    title: 'The Skin Stapler: quién lo hizo — Tainted Pact y Assemble Entertainment',
    description: 'The Skin Stapler es de Tainted Pact, desarrolladora en solitario de EE. UU., con publicación de Assemble Entertainment — quinto terror del estudio, lanzado a 14,99 euros.',
    eyebrow: 'Estudio y publicación',
    directAnswer: 'The Skin Stapler lo hizo Tainted Pact, desarrolladora en solitario de Estados Unidos, y lo publicó Assemble Entertainment, editora alemana detrás de Sticky Business, Roadwarden y la serie Endzone. El juego debutó el 6 de agosto de 2026 en Windows PC por 14,99 euros en Steam y es el quinto título de terror del estudio.',
    date: '2026-09-03',
    sections: [
      { title: 'Estudio y editora en resumen', paragraphs: ['El lado de la editora es inusual de tan establecido para un proyecto de terror en solitario: Assemble Entertainment ha publicado más de 50 juegos desde 2016, en un catálogo que va de éxitos acogedores como Sticky Business a RPG narrativos como Roadwarden y a la serie de supervivencia Endzone:'], bullets: ['Desarrolladora: Tainted Pact — desarrollador en solitario, Estados Unidos (California)', 'Editora: Assemble Entertainment — Alemania, más de 50 juegos publicados', 'Lanzamiento: 6 de agosto de 2026, Windows PC', 'Precio de lanzamiento: 14,99 euros en Steam', 'Catálogo anterior: Suffer the Night, Terror at Oakheart, Massacre at the Mirage, Flesh Made Fear', 'Canales oficiales: itch.io (taintedpact88) y YouTube (@TaintedPactGames)'] },
      { title: '¿Quién es Tainted Pact?', paragraphs: ['Tainted Pact es el estudio en solitario detrás de cinco juegos de terror, y el anuncio de lanzamiento de la editora describe a la desarrolladora como una operación de una sola persona en California. El estudio construye terror grindhouse deliberadamente nichado: duraciones cortas, visuales low-poly de era PSX, repartos doblados de creadores de contenido y guion de slasher movido a chistes.', 'La huella pública del estudio es pequeña: una cuenta de itch.io bajo el nombre taintedpact88 y un canal de YouTube, @TaintedPactGames, que publicó Dev Logs de The Skin Stapler en diciembre de 2025 — Dev Log #1 el 1 de diciembre y Dev Log #2 el 2 de diciembre —, documentando la construcción en público antes del lanzamiento. El estudio no publica nombres de fundadores ni detalles personales; su identidad pública es la marca, los juegos y las colaboraciones con creadores.'] },
      { title: 'Los cuatro juegos anteriores a The Skin Stapler', paragraphs: ['El catálogo anterior está confirmado tanto por el anuncio de la editora como por el catálogo de GOG:'], bullets: ['Suffer the Night — el debut de analog horror del estudio, construido en torno a un ordenador retro embrujado', 'Terror at Oakheart — un slasher en un campamento, con la misma violencia estilizada', 'Massacre at the Mirage — un slasher confinado a un hotel, con ritmo escena a escena', 'Flesh Made Fear — el predecesor directo: historia de asesino en serie con escenas dobladas y puntaza grindhouse'] },
      { title: 'La editora: Assemble Entertainment', paragraphs: ['Assemble Entertainment es una editora alemana fundada en 2016, con más de 50 juegos publicados. Su alcance va más allá del terror: Sticky Business es un éxito acogedor, Roadwarden es un RPG narrativo elogiado por la crítica, y la serie Endzone ancla su lado de estrategia de supervivencia. The Skin Stapler queda en el pasillo grindhouse de la editora, junto a su trabajo con proyectos de terror cortos.', 'Para los jugadores, la editora importa en la práctica: el esfuerzo de prensa del lanzamiento, la presencia de Steam en el evento Tiny Teams durante la ventana de la demo y la presencia en las tiendas Steam y GOG pasan todos por Assemble. El listado de la tienda lleva la línea de copyright Assemble Entertainment GmbH, y el anuncio de la editora es la fuente de los datos de lanzamiento anteriores.'] },
      { title: 'El modelo de reparto de creadores', paragraphs: ['La editora describe el juego como construido con apoyo de algunos de sus creadores de contenido favoritos, y el póster del reparto lo refuerza con diez intérpretes con nombre: RJ Green, Daniel Suraci, HexyIRL, Layna Lazar, Runebee, Luna Arcana, Blairvira, FeFe, Scaroline y KingWoolz. Varios personajes están modelados y doblados por los propios creadores — Scaroline y el Underworld VHS son el ejemplo más claro.', 'Ese modelo es la firma del estudio. Convierte un proyecto en solitario en lanzamiento colaborativo, le da al juego un público integrado por los canales de los creadores y mantiene la presentación totalmente doblada viable para un juego de 2,5 horas. La guía de actores de doblaje mapea cada crédito de personaje a intérprete.'] },
      { title: 'Cómo seguir a la desarrolladora en tres pasos', paragraphs: [], bullets: ['Añade a la lista de deseos y sigue en Steam: la página de la desarrolladora es el canal principal de parches y anuncios futuros, y la página de The Skin Stapler enlaza los otros trabajos del estudio', 'Comprueba el canal de YouTube: @TaintedPactGames es donde aparecen los Dev Logs — dos solo en diciembre de 2025 — y es el lugar más probable para anuncios de proyectos futuros', 'Sigue la cuenta de itch.io: la página taintedpact88 aloja la presencia independiente del estudio y documenta la senda de proyectos que llevó a The Skin Stapler'] }
    ],
    faq: [
      { question: '¿Quién hizo The Skin Stapler?', answer: 'La desarrolladora en solitario Tainted Pact, de Estados Unidos, con publicación de Assemble Entertainment, de Alemania.' },
      { question: '¿Qué juegos ha hecho Tainted Pact?', answer: 'Cuatro títulos anteriores de terror — Suffer the Night, Terror at Oakheart, Massacre at the Mirage y Flesh Made Fear — más The Skin Stapler como el quinto.' },
      { question: '¿Tainted Pact es una sola persona?', answer: 'Sí — el anuncio de lanzamiento de la editora describe un desarrollador en solitario, y el perfil artesanal de producción coincide con un estudio de una persona trabajando con un reparto de creadores.' },
      { question: '¿Quién publica The Skin Stapler?', answer: 'Assemble Entertainment, editora alemana fundada en 2016 con más de 50 juegos, incluidos Sticky Business, Roadwarden y la serie Endzone.' },
      { question: '¿Dónde puedo seguir al estudio?', answer: 'Las listas de deseos en Steam, el canal @TaintedPactGames en YouTube y la página taintedpact88 en itch.io son los canales oficiales.' },
      { question: '¿Cuándo salió el juego?', answer: 'El 6 de agosto de 2026, en Steam y GOG para Windows PC, por 14,99 euros — la guía de fecha de lanzamiento tiene la línea temporal completa, y la guía de Steam cubre el listado de la tienda.' }
    ],
    sources: sourceSets.developer
  },
  'janker-edition': {
    id: 'janker-edition', keyword: 'The Skin Janker Edition',
    title: 'The Skin Janker Edition: el nombre equivocado detrás del DLC real',
    description: 'No existe "The Skin Janker Edition" — el nombre mezcla The Skin Jankers, el DLC de 3 skins. Mira la estructura real de productos en Steam y GOG.',
    eyebrow: 'DLC y ediciones',
    directAnswer: 'No existe un producto llamado The Skin Janker Edition — el nombre es una lectura equivocada de The Skin Jankers, el DLC cosmético de The Skin Stapler. El producto real es The Skin Stapler: The Skin Jankers, un DLC lanzado junto con el juego el 6 de agosto de 2026 con tres skins de superhéroes. No hay bundle de edición especial, versión de coleccionista ni SKU con sufijo "Edition" del juego base en Steam o en GOG.',
    date: '2026-09-03',
    sections: [
      { title: 'La estructura real de productos', paragraphs: ['Tres entradas en la tienda, ninguna edición. Si buscabas una Janker Edition, la segunda línea de la tabla es el producto que en realidad quieres — y las secciones siguientes explican exactamente qué contiene:'], bullets: ['The Skin Stapler (juego base): el juego completo de 14 capítulos, App 4310610 — sin sufijo de edición; Steam y GOG', 'The Skin Jankers DLC: tres skins cosméticas inspiradas en superhéroes, Steam App 4919860, lanzado el 6 de agosto de 2026; DLC aparte en Steam, incluido en la compra de GOG', 'Soundtrack DLC: el audio del juego, Steam App 4919810, lanzado el 6 de agosto de 2026; DLC aparte en Steam'] },
      { title: 'Qué incluye el DLC Skin Jankers', paragraphs: ['La descripción oficial de GOG es específica: el DLC Skin Jankers entrega tres skins cosméticas gloriosamente ridículas inspiradas en superhéroes para los personajes principales del juego. La redacción entrega el tema (parodia de superhéroes), la cuenta (tres) y el alcance (solo cosmético) — nada en el DLC cambia jugabilidad, capítulos ni historia.', 'Los tres diseños individuales de skin no tienen nombre en ninguna página de tienda, así que cualquier nombre específico de skin que veas por ahí va más allá de la descripción oficial. Del mismo modo, el precio suelto del DLC en Steam no aparece en el material que fundamenta esta guía — consulta la página propia del DLC para el precio actual en tu región.'] },
      { title: 'Edition vs. DLC: por qué ocurre la confusión', paragraphs: ['La lectura equivocada sigue un patrón previsible. Los juegos de terror a menudo venden ediciones especiales, y "Jankers" en plural suena a nombre de edición en una barra de búsqueda. Súmale el vocabulario del propio juego — la comunidad usa jank con cariño, y un logro de Steam se llama literalmente Jank Ya Later! — y una ficticia Janker Edition suena lo bastante plausible para que los buscadores la sugieran.', 'La estructura de la tienda zanja la cuestión: una edición real aparecería como SKU de bundle separado en Steam, y la tienda de The Skin Stapler lista solo el juego base más dos DLC. GOG va un paso más allá e incluye el contenido Skin Jankers en la compra base — lo que un producto encerrado detrás de una edición no haría.'] },
      { title: 'Cómo comprar lo correcto en tres pasos', paragraphs: [], bullets: ['Decide primero la tienda: GOG incluye las tres skins con el juego base; Steam vende el juego base y el DLC Skin Jankers por separado — si quieres las skins en Steam, añade el DLC explícitamente', 'Comprueba la página del DLC antes de cerrar: The Skin Stapler: The Skin Jankers es el App 4919860 en Steam — confirma que el título coincide exactamente, porque el DLC de la banda sonora (App 4919810) queda al lado en la tienda', 'Ignora cualquier cosa etiquetada como edición: no existe Janker Edition, Deluxe Edition ni Collector’s Edition de este juego — tienda o web de claves que use esos nombres está etiquetando mal el juego base o revendiendo el DLC bajo un sello inventado'] },
      { title: 'Qué hacen las skins en el juego', paragraphs: ['DLC cosmético en un juego de historia de 2,5 horas hace exactamente lo que dice: cambia la apariencia de los personajes principales mientras cada frase, capítulo y logro permanece idéntico. Los 16 logros del juego base, la historia única y la estructura de capítulos no se tocan por poseer el DLC — la guía de logros lista el conjunto completo, y ningún elemento exige las skins.', 'El tema de parodia de superhéroes encaja con el registro de comedia grindhouse del juego: el marketing de la propia editora promete una última risa antes de morir, y vestir al reparto de Carrion City de superhéroes gloriosamente ridículos es extensión del mismo chiste, no un modo nuevo. La guía de análisis cubre lo central que es ese humor para el atractivo del juego.'] }
    ],
    faq: [
      { question: '¿Existe una The Skin Janker Edition del juego?', answer: 'No. El nombre mezcla The Skin Jankers — el DLC cosmético de tres skins — con una edición del juego base. Ningún SKU de edición existe en Steam o en GOG.' },
      { question: '¿Qué es el DLC Skin Jankers?', answer: 'Tres skins cosméticas inspiradas en superhéroes para los personajes principales, lanzadas el 6 de agosto de 2026. Se vende aparte en Steam y viene incluido en la versión de GOG.' },
      { question: '¿Cuánto cuesta el DLC?', answer: 'El precio suelto no consta en el material que fundamenta esta guía — consulta la página del DLC en Steam para el precio regional actual.' },
      { question: '¿El DLC cambia la historia o añade capítulos?', answer: 'No. Las skins son solo cosméticas; la historia de 14 capítulos y los 16 logros son idénticos con o sin él.' },
      { question: '¿El DLC está en GOG?', answer: 'Sí — GOG agrega las skins Skin Jankers a la compra del juego base, así que los compradores de GOG reciben las skins sin compra separada.' },
      { question: '¿Cuál es el otro DLC?', answer: 'La banda sonora, lanzada el mismo día que el juego y el paquete de skins. Contiene la pista synth que la crítica señaló como parte central de la presentación.' }
    ],
    sources: sourceSets['janker-edition']
  },
  'turkish-patch': {
    id: 'turkish-patch', keyword: 'The Skin Stapler en turco',
    title: 'The Skin Stapler en turco: sin parche oficial Türkçe',
    description: 'Steam y GOG listan solo inglés — hasta septiembre de 2026 no hay parche Türkçe oficial ni anuncio de localización turca para The Skin Stapler.',
    eyebrow: 'Estado del idioma',
    directAnswer: 'The Skin Stapler no tiene opción de idioma turco. Las páginas de Steam de la versión completa (App 4310610) y de la demo (App 4343530) listan inglés como único idioma — interfaz, subtítulos y doblaje —, y la oferta de GOG confirma: inglés en la interfaz, en los subtítulos y en el audio. Como el juego está totalmente doblado, una versión turca exigiría volver a grabar cada frase con un reparto de doblaje — y hasta septiembre de 2026 ni Tainted Pact ni Assemble Entertainment han anunciado localización turca ni un Türkçe yaması oficial.',
    date: '2026-09-03',
    sections: [
      { title: 'Estado del idioma en resumen', paragraphs: ['Tres listados de tienda, un idioma. Cada columna viene directa de las listas oficiales de idioma de las tiendas — la única fuente con autoridad sobre lo que una versión soporta:'], bullets: ['Steam — juego completo (App 4310610): interfaz inglés, subtítulos inglés, audio inglés; parche turco oficial: ninguno anunciado', 'Steam — demo (App 4343530): la misma tabla en inglés de la versión completa', 'GOG — juego completo: el mismo build solo-en-inglés', 'Consejo de la demo: la demo refleja el juego completo — ninguna descarga revela soporte turco escondido'] },
      { title: 'Por qué no hay parche turco oficial', paragraphs: ['The Skin Stapler es un juego de terror FMV totalmente doblado. Cada frase es audio grabado por diez actores de doblaje con nombre, así que localizar no es cambiar texto: una versión turca exigiría subtítulos traducidos y un doblaje completo grabado para cada escena. Es una carga pesada para un desarrollador en solitario — The Skin Stapler es el quinto título de terror de Tainted Pact, construido en cerca de un año y publicado por Assemble Entertainment a 14,99 euros.', 'La combinación de duración corta, reparto totalmente doblado y producción de una persona explica por qué el lanzamiento llegó solo en inglés. Los anuncios de localización para juegos de este tamaño, cuando ocurren, suelen llegar tras el lanzamiento en noticias de la página de la tienda o en notas de parche. Tal anuncio para el turco no existe hasta septiembre de 2026, y nada en los listados de las tiendas sugiere preparación.'] },
      { title: 'Parches turcos de la comunidad', paragraphs: ['Esta guía sigue solo canales oficiales y no enlaza descargas de terceros. La existencia de un Türkçe yaması de fans no está documentada en ningún canal oficial: el juego no tiene página de workshop, sin soporte oficial de modding y sin respaldo de la desarrolladora para archivos de idioma de terceros.', 'Si aún así buscas, sopesa los riesgos de costumbre de los parches no oficiales en un juego comprado en tienda. Los archivos no oficiales pueden romperse con actualizaciones, no pasan por triaje de Steam o GOG, y un archivo malo puede alcanzar más que la carpeta del juego. Eso no prueba que un parche concreto no funcione — pero cada enlace de descarga, post de foro y descripción de vídeo merece desconfianza hasta que sepas exactamente qué modifica el archivo.'] },
      { title: 'Cómo verificar el soporte turco tú mismo', paragraphs: [], bullets: ['Abre la tabla de idiomas de Steam: baja la página del juego completo hasta la sección de idiomas y lee las columnas de interfaz, subtítulos y audio para el turco; la página de la demo (App 4343530) muestra la misma tabla', 'Vigila el feed de noticias: los anuncios de localización o parche de Tainted Pact o Assemble Entertainment aparecen primero en el área de noticias de Steam — ahí se anunciaría un parche turco', 'Cruza con GOG y la página de la desarrolladora: el listado de GOG y la página de itch.io repiten el soporte oficial de idiomas — una contradicción entre las tiendas aparecería ahí'] },
      { title: 'Jugar en inglés mientras esperas', paragraphs: ['El inglés del juego no es prosa densa — es diálogo grindhouse en escenas cortas, objetivos claros en pantalla y clips FMV estilo VHS, y los puzles reales (como el código 1979 del cuadro de fotos) están documentados en la guía de soluciones. Si el inglés es tu segunda lengua, la demo gratuita de Steam es la prueba más barata: envuelve tres tramos jugables — comisaría, Quick Fix y Gutters End — en 30 a 45 minutos, para que evalúes la barrera del idioma antes de los 14,99 euros.', 'El único intercambio que conviene saber de antemano: la historia se entrega casi entera por diálogos hablados y secuencias FMV, no por texto. Subtítulos existen, pero transcriben las interpretaciones en inglés — no hay interruptor de idioma detrás de ellos.'] }
    ],
    faq: [
      { question: '¿Existe parche turco para The Skin Stapler?', answer: 'Ninguno oficial hasta septiembre de 2026. Steam y GOG listan solo inglés para el juego completo y la demo, y no se ha anunciado localización turca.' },
      { question: '¿Llegará el turco después?', answer: 'Nada está anunciado. Si cambia, aparece primero en el feed de noticias de Steam y en los canales de la desarrolladora — nunca en silencio en una actualización aleatoria.' },
      { question: '¿La demo está en turco?', answer: 'No. La demo (App 4343530) lista el mismo idioma único del juego completo: inglés en interfaz, subtítulos y audio.' },
      { question: '¿La versión de GOG tiene subtítulos en turco?', answer: 'No. GOG distribuye el mismo build solo-en-inglés de Steam, sin interruptores de idioma más allá del inglés.' },
      { question: '¿Por qué un doblaje turco es tan improbable?', answer: 'El juego está totalmente doblado. Un doblaje significa volver a grabar cada frase con un reparto turco — un compromiso mucho mayor que traducir subtítulos, y ni los subtítulos están en discusión.' }
    ],
    sources: sourceSets['turkish-patch']
  },
  'korean-patch': {
    id: 'korean-patch', keyword: 'The Skin Stapler en coreano',
    title: 'The Skin Stapler en coreano: sin parche oficial ni traducción',
    description: 'Sin opción de coreano: Steam y GOG listan solo inglés — hasta septiembre de 2026 no hay 패치 oficial ni 한국어 번역 anunciados para The Skin Stapler.',
    eyebrow: 'Estado del idioma',
    directAnswer: 'The Skin Stapler no tiene opción de idioma coreano. Los listados de Steam del juego completo (App 4310610) y de la demo (App 4343530) muestran inglés como único idioma soportado — interfaz, subtítulos y audio —, y el build de GOG es el mismo paquete de idioma único. Si llegaste de una búsqueda coreana de un The Skin Stapler 패치 o una 한국어 번역, esa es toda la respuesta hasta septiembre de 2026: no existe soporte coreano oficial, y nada está anunciado.',
    date: '2026-09-03',
    sections: [
      { title: 'Estado del idioma en resumen', paragraphs: ['Tres listados de tienda, un idioma. Cada línea viene directa de las tablas oficiales de idioma de las tiendas — la única fuente con autoridad sobre lo que una versión soporta:'], bullets: ['Steam — juego completo (App 4310610): interfaz inglés, subtítulos inglés, audio inglés; parche coreano oficial: ninguno anunciado', 'Steam — demo (App 4343530): la misma tabla en inglés de la versión completa', 'GOG — juego completo: el mismo build solo-en-inglés', 'Nota de la demo: la demo refleja el juego completo — la descarga gratuita no esconde soporte de coreano'] },
      { title: 'Por qué no hay parche coreano oficial', paragraphs: ['The Skin Stapler es un juego de terror FMV totalmente doblado, con diez intérpretes con nombre en el póster del reparto. Una versión coreana exigiría las dos cosas a la vez: subtítulos traducidos para cada frase y un doblaje completo en coreano grabado sobre las secuencias de vídeo estilo VHS. Es una carga de localización pesada para un desarrollador en solitario — Tainted Pact construyó el juego en cerca de un año, y la editora Assemble Entertainment lo lanzó el 6 de agosto de 2026 por 14,99 euros con presencia de tienda solo en inglés.', 'Los terrores cortos y cargados de diálogo de equipos pequeños estrenan rutinariamente solo en inglés, y el soporte coreano, cuando llega, típicamente aparece como anuncio post-lanzamiento en el feed de noticias de la tienda. Tal anuncio no existe para este juego hasta septiembre de 2026.'] },
      { title: 'Los términos de búsqueda coreanos, explicados', paragraphs: ['Dos búsquedas coreanas dominan el tema. 패치 significa parche — quien busca un The Skin Stapler 패치 quiere un parche de idioma o una traducción de fans. 번역 significa traducción, generalmente combinado con 한국어 (coreano) para pedir una versión localizada. Ninguna de las búsquedas da resultado oficial porque ninguno de los dos productos existe: los listados de las tiendas son el registro con autoridad, y listan un idioma.', 'Cuidado con lo que esas búsquedas traen en el resto: páginas de parches de fans, builds resubidos y enlaces en descripciones de vídeo son archivos de terceros sin triaje de Steam o GOG. Esta guía no enlaza ninguno.'] },
      { title: 'Parches coreanos de la comunidad', paragraphs: ['Si existe una traducción coreana de fans, no está documentada en ningún canal oficial — el juego no tiene soporte de workshop, no tiene herramientas oficiales de modding y no tiene respaldo de la desarrolladora para archivos de idioma de terceros. Quien evalúe uno igualmente carga los riesgos de costumbre de los parches no oficiales: pueden romperse con actualizaciones del juego, tocar archivos bien más allá de la carpeta del juego y chocar con términos de servicio que las modificaciones no oficiales no siempre respetan.'] },
      { title: 'Cómo verificar el soporte coreano tú mismo', paragraphs: [], bullets: ['Lee la tabla de idiomas de Steam: en la página del juego completo (App 4310610), baja hasta la lista de idiomas y comprueba la fila del coreano en interfaz, subtítulos y audio; la página de la demo muestra la misma tabla', 'Observa el feed de noticias: las noticias de localización aparecen primero en el área de noticias de Steam, de Tainted Pact o de Assemble Entertainment — es el canal a vigilar', 'Cruza con GOG: el listado de GOG refleja el soporte oficial de idiomas, y un anuncio futuro de coreano aparecería ahí también'] },
      { title: 'Jugar en inglés mientras esperas', paragraphs: ['El inglés del juego es diálogo grindhouse, no prosa densa: escenas cortas, frases directas y objetivos claros en pantalla llevan la ruta. Los puzles reales — el código 1979 del cuadro de fotos, la báscula de carne de la Flesh Pit, las cintas dañadas — están documentados paso a paso y quitan a los capítulos de investigación la mayor parte del riesgo del idioma.', 'Quien quiera probar la barrera del idioma gratis: la demo cubre en 30 a 45 minutos exactamente los formatos que encontrarás en el juego completo — diálogos de entrevista, trabajo de atención y una persecución guionizada. La historia en sí llega por interpretaciones habladas en inglés y clips FMV; los subtítulos solos no sostienen una partida en otro idioma.'] }
    ],
    faq: [
      { question: '¿Existe parche coreano para The Skin Stapler?', answer: 'Ninguno oficial hasta septiembre de 2026. Steam y GOG listan solo inglés, y no se ha anunciado localización coreana.' },
      { question: '¿Llegarán subtítulos en coreano después?', answer: 'Nada está anunciado. El soporte futuro aparecería primero en el feed de noticias de Steam y en los canales de la desarrolladora.' },
      { question: '¿La demo está en coreano?', answer: 'No. La demo (App 4343530) trae la misma tabla solo-en-inglés del juego completo.' },
      { question: '¿Steam y GOG difieren en el idioma?', answer: 'No. Las dos tiendas distribuyen el mismo build solo-en-inglés para interfaz, subtítulos y audio.' },
      { question: '¿Por qué un doblaje coreano es improbable?', answer: 'El juego está totalmente doblado con diez intérpretes. Un doblaje significa volver a grabar el juego entero — un compromiso mucho mayor que traducir subtítulos, y ni los subtítulos están anunciados.' }
    ],
    sources: sourceSets['korean-patch']
  },
  'press-kit': {
    id: 'press-kit', keyword: 'The Skin Stapler press kit',
    title: 'The Skin Stapler press kit: assets oficiales y dónde encontrarlos',
    description: 'No hay press kit oficial de The Skin Stapler — en su lugar, nota de lanzamiento, tráiler y galerías de las tiendas. Todos los assets oficiales listados.',
    eyebrow: 'Prensa y creadores',
    directAnswer: 'The Skin Stapler no tiene press kit oficial. Hasta septiembre de 2026, Tainted Pact y Assemble Entertainment no han publicado un ZIP de prensa, un paquete de logos ni un portal de prensa con login. Lo que existe es un conjunto de assets públicos y oficiales que cubre lo que reseñistas, streamers y editores necesitan en la práctica: la nota de lanzamiento en Games Press, el tráiler oficial del 27 de enero de 2026 y las galerías completas de capturas en Steam y GOG.',
    date: '2026-09-03',
    sections: [
      { title: 'Lo que existe en lugar del press kit', paragraphs: ['Esa combinación es el press kit práctico. Todo en la lista es oficial, accesible sin credenciales y seguro para citar o incrustar — exactamente aquello para lo que existe un press kit:'], bullets: ['Nota de lanzamiento: Games Press, titular "The Skin Stapler Is Ready for Its Next Victim" (6 de agosto de 2026) — precio, datos del estudio, clima de la demo, texto citable', 'Tráiler oficial: YouTube, publicado el 27 de enero de 2026 (ID de vídeo 5tEJiy8FJbY) — incrustable desde el original', 'Galería de Steam: página de la tienda (App 4310610) — capturas, portada, descripción de la tienda', 'Galería de GOG: las mismas capturas y el mismo texto de tienda', 'Tienda de la desarrolladora: la página del juego en itch.io'] },
      { title: 'Qué confirma la nota de lanzamiento', paragraphs: ['La nota del 6 de agosto de 2026 en Games Press es el documento más útil del conjunto, porque fija en un solo texto los datos que la mayoría de las coberturas necesita: 14,99 euros en PC; desarrollado por el Tainted Pact en solitario, publicado por Assemble Entertainment bajo el sello Tiny Teams operado por Yogscast; The Skin Stapler como quinto título de terror del estudio; la demo gratuita de Steam con nota Very Positive en el lanzamiento; CaseOh y MoistCr1TiKaL jugando el juego antes del estreno.', 'Las dos descripciones oficiales del juego vienen de la misma nota. La logline: "Enter Carrion City and hunt a serial killer through a short, story-driven horror nightmare". El eslogan: "NO ONE LEAVES CARRION CITY IN ONE PIECE." Quien escribe sobre el juego recurre con seguridad a esas dos líneas, porque vienen del texto de la propia editora en vez de una paráfrasis — y la nota las acompaña de los números concretos anteriores, así que una noticia corta y un análisis largo tienen lo que necesitan.'] },
      { title: 'Por qué un juego pequeño prescinde del press kit', paragraphs: ['Nada falta aquí — así llega normalmente al mercado el terror de equipos pequeños. Un desarrollador en solitario no mantiene portal de prensa, y la nota de lanzamiento de la editora hace el mismo trabajo: datos, citas y posicionamiento llegan a las redacciones de una sola pasada. Las galerías de las tiendas sirven entonces como el hogar permanente y siempre actualizado de los assets visuales — lo que un ZIP estático jamás es.', 'Del lado de los creadores vale lo mismo. Las partidas de CaseOh y MoistCr1TiKaL citadas en la nota son vídeos públicos, y la nota Very Positive de la demo es visible para cualquiera en la página de la tienda — dos señales de reputación citables sin ningún acceso de prensa.'] },
      { title: 'Cómo reunir los assets en tres pasos', paragraphs: [], bullets: ['Tira primero de las galerías de las tiendas: la página de Steam (App 4310610) guarda el conjunto actual de capturas y la portada; el listado de GOG repite el mismo material y te da una segunda fuente oficial', 'Incrusta el tráiler original: el tráiler de YouTube publicado el 27 de enero de 2026 (ID 5tEJiy8FJbY) es el oficial — incrusta la subida original, nunca una resubida, para que créditos y visualizaciones queden en la editora', 'Cita la nota para los datos: la nota de Games Press entrega precio, créditos del equipo, nota de la demo y los dos eslóganes oficiales sin ninguna paráfrasis en medio'] },
      { title: 'Contactos de prensa sin portal', paragraphs: ['No existe contacto de prensa publicado para el juego en sí. Assemble Entertainment es la editora de registro — la web de la editora es el camino sensato para preguntas de prensa. Para todo lo visible, el conjunto público basta: galería, tráiler y nota. Un sistema separado de credenciales no existe y no se exige; los assets listados cubren por completo análisis, noticias y preparación de stream.'] }
    ],
    faq: [
      { question: '¿Existe un press kit oficial de The Skin Stapler?', answer: 'No. Hasta septiembre de 2026 no se ha publicado ningún ZIP de prensa, paquete de logos ni portal de prensa para el juego.' },
      { question: '¿Dónde consigo capturas oficiales?', answer: 'En las galerías de las tiendas Steam y GOG. Llevan las mismas capturas oficiales que la editora usa para vender el juego y siempre están actualizadas.' },
      { question: '¿A quién contacto para acceso de prensa?', answer: 'Ningún contacto de prensa está publicado para el juego. Assemble Entertainment es la editora de registro — la web de la editora es el camino correcto para preguntas de prensa.' },
      { question: '¿Puedo usar el tráiler en mi cobertura?', answer: 'Sí. El tráiler oficial (ID de YouTube 5tEJiy8FJbY) es público y está hecho para compartir — incrusta la subida original, no una resubida.' },
      { question: '¿Cuáles son los eslóganes oficiales del juego?', answer: 'La logline es "Enter Carrion City and hunt a serial killer through a short, story-driven horror nightmare", y el eslogan es "NO ONE LEAVES CARRION CITY IN ONE PIECE." Ambos vienen de la nota de lanzamiento.' }
    ],
    sources: sourceSets['press-kit']
  },
  'final-aftermath': {
    id: 'final-aftermath', keyword: 'The Skin Stapler Final Aftermath',
    title: 'The Skin Stapler Final Aftermath: posición, logro y final',
    description: 'El Final Aftermath explicado: el quinto interludio Aftermath entre Lazar’s Blood Bank y Closing In, con el logro "Nine, Ten, Never Jank Again.".',
    eyebrow: 'Guía de capítulos',
    directAnswer: 'The Final Aftermath es el quinto y último interludio Aftermath de The Skin Stapler — el capítulo que cierra las historias de las víctimas antes del tramo final en dos partes. En la ruta, queda después de Lazar’s Blood Bank, que termina a las 01:58:34 en una partida de referencia, y antes de Closing In, que abre a las 02:18:29. Completarlo desbloquea el logro "Nine, Ten, Never Jank Again." y cierra la cuenta de los 14 capítulos: nueve capítulos de localizaciones, cuatro partes de Aftermath y el propio Final Aftermath.',
    date: '2026-09-03',
    sections: [
      { title: 'Posición en la ruta', paragraphs: ['Estos hitos vienen de la lista oficial de logros y de los tiempos de una partida de referencia — localizan el capítulo con exactitud, aunque no exista documento granular de diseño de niveles:'], bullets: ['Nombre del capítulo: The Final Aftermath', 'Posición: después de Lazar’s Blood Bank (01:58:34 en la partida de referencia), antes de Closing In (02:18:29)', 'Logro: "Nine, Ten, Never Jank Again." — Complete The Final Aftermath Chapter', 'Cuenta de capítulos: 9 capítulos de localizaciones + 4 partes de Aftermath + el Final Aftermath = 14 capítulos', 'Qué viene después: Closing In (02:18:29), y entonces el final en la Flesh Pit (02:34:00)'] },
      { title: 'Por qué importa exactamente la posición', paragraphs: ['Quien sigue la ruta por el reloj necesita esta localización: Lazar’s Blood Bank — el capítulo de Layna y el último de las localizaciones de víctimas — termina cerca del minuto 01:58 de una partida completa de referencia. El Final Aftermath viene después, y Closing In abre a las 02:18:29. Quedan para el interludio unos veinte minutos en la línea temporal, dentro de una partida que termina en la Flesh Pit hacia las 02:34 y se asienta en la duración oficial de aproximadamente dos horas y media.', 'Steam confirma el mismo orden por el otro lado: la lista de logros enumera los interludios en secuencia, y el último elemento, "Nine, Ten, Never Jank Again.", se sienta exactamente en el Final Aftermath. Leer la lista de logros de arriba abajo es leer el orden de la ruta.'] },
      { title: 'El logro detrás del capítulo', paragraphs: ['El logro de Steam se lee "Nine, Ten, Never Jank Again." con el requisito "Complete The Final Aftermath Chapter." No hay condición escondida ni elemento perdible: el logro cae cuando el capítulo termina. El nombre es la resolución de una canción de contar que el juego extiende por los logros de los interludios — Aftermath Part 3 lleva "Five, six, grab your crucifix...", y la secuencia aterriza aquí en el "nine, ten", en el interludio final.', 'Para una lista de logros limpia, este elemento es imposible de perder siempre que termines la ruta. El desbloqueo genuinamente perdible del juego es la nota de agradecimiento en la oficina — elemento propio, cubierto aparte en la guía de logros.'] },
      { title: 'Qué ocurre en el Final Aftermath', paragraphs: ['Los capítulos Aftermath existen para devolver la historia de cada víctima al expediente de Dick Slater. Los capítulos de víctimas son turnos comunes de trabajo — servir perritos calientes, rellenar donas, rebobinar cintas — que acaban en manos del asesino; las partes Aftermath reencuadran esas muertes como evidencias, conexiones y una cuenta que solo sube. El Final Aftermath cierra ese hilo: la última historia de víctima entra en la investigación, y el caso queda lo bastante completo para que Slater vaya a por el asesino.', 'Cómo es el capítulo momento a momento — interludio estilo cutscene o tramo con interacciones propias — es un detalle que verificarás en el juego. El material oficial registra el nombre del capítulo, la posición en el orden de progresión y el logro, y nada más granular que eso.'] },
      { title: 'Cómo prepara el tramo final', paragraphs: ['Después del Final Aftermath quedan dos capítulos, y ambos son investigación. Closing In, abriendo a las 02:18:29 en la partida de referencia, converge el caso sobre un sospechoso. The Flesh Pit — el restaurante de barbacoa de Elias Crow y la respuesta a la pregunta del título — recibe el final a las 02:34:00. A partir del Final Aftermath no existen más capítulos de víctimas ni turnos que trabajar: los últimos veinte minutos son la historia cerrando las mandíbulas. Lo que ocurre en el final lo cubre la página de final explicado; la identidad y el motivo del asesino quedan en la guía de quién es el Skin Stapler, para cuando lo hayas visto.'] }
    ],
    faq: [
      { question: '¿Qué es el Final Aftermath en The Skin Stapler?', answer: 'El quinto y último interludio Aftermath — el capítulo que cierra el hilo de las víctimas antes del tramo final en dos partes, Closing In y Flesh Pit.' },
      { question: '¿Qué logro desbloquea?', answer: '"Nine, Ten, Never Jank Again.", por completar The Final Aftermath Chapter; cae automáticamente al final del capítulo.' },
      { question: '¿El Final Aftermath es un capítulo jugable?', answer: 'El formato exacto — interludio estilo cutscene o sección interactiva — no está documentado por separado. Oficialmente cuenta como uno de los 14 capítulos y queda en la ruta entre Lazar’s Blood Bank y Closing In.' },
      { question: '¿En qué punto del juego ocurre?', answer: 'Cerca de la marca de dos horas: Lazar’s Blood Bank termina cerca de 01:58:34 en la partida de referencia, y Closing In abre a las 02:18:29 — el interludio queda entre ellos.' },
      { question: '¿El juego termina después del Final Aftermath?', answer: 'No. Closing In y el final en la Flesh Pit aún llegan — el interludio cierra las historias de las víctimas, y los dos últimos capítulos entregan el desenlace.' }
    ],
    sources: sourceSets['final-aftermath']
  },
  'aftermath-3': {
    id: 'aftermath-3', keyword: 'The Skin Stapler Aftermath 3',
    title: 'The Skin Stapler Aftermath 3: posición, logro y función',
    description: 'Aftermath Part 3 explicado: el tercer interludio entre la donut shop de Luna y Underworld VHS, con el logro "Five, six, grab your crucifix...".',
    eyebrow: 'Guía de capítulos',
    directAnswer: 'Aftermath 3 — en Steam, The Aftermath Part 3 — es el tercero de los cuatro interludios Aftermath de The Skin Stapler y queda en medio del paso de las víctimas a la investigación: después de Luna’s Cream Filled Donuts, que termina cerca de 01:15:37 en una partida de referencia, y antes de Underworld VHS, que abre a las 01:34:10. Completarlo desbloquea el logro "Five, six, grab your crucifix...", la tercera línea de la canción de contar repartida por los logros de los interludios.',
    date: '2026-09-03',
    sections: [
      { title: 'Posición en la ruta', paragraphs: ['Los dos tiempos enmarcan el interludio con precisión — todo entre ellos es el interludio más el comienzo del capítulo siguiente, dentro de una ruta completa de aproximadamente dos horas y media:'], bullets: ['Nombre del capítulo: The Aftermath Part 3', 'Posición: después de Luna’s Cream Filled Donuts (01:15:37), antes de Underworld VHS (01:34:10)', 'Logro: "Five, six, grab your crucifix..." — Complete The Aftermath Part 3 Chapter', 'Función: devuelve las historias de las víctimas a la investigación de Dick Slater', 'Ventana de tiempo: el tramo 01:15–01:34 de una partida de referencia'] },
      { title: 'Qué hace el capítulo por la historia', paragraphs: ['La fórmula Aftermath es el tejido conjuntivo de la estructura del juego. Cada capítulo de víctima termina igual — un turno común que se derrumba en manos del asesino —, y cada parte Aftermath arrastra esa muerte de vuelta al expediente de Slater: los tableros de evidencias crecen, las conexiones se multiplican, la cuenta sube. La Part 3 es donde el ritmo de la segunda mitad se afianza. Sigue al capítulo de Luna en el orden de progresión, y la escena de Luna lleva el hilo del VHS que el próximo capítulo de localización recoge: Underworld VHS es la tienda de Scaroline, y el vínculo entre la donut shop y el videoclub está documentado en la guía de quién es el Skin Stapler.', 'El contenido escena a escena del capítulo — a qué víctimas toca y cómo el expediente las enmarca — no está documentado por separado en el material oficial. Lo que el registro oficial fija son el nombre del capítulo, la posición en el orden de progresión y el logro, y esos tres datos bastan para localizarlo con exactitud.'] },
      { title: 'El patrón de la canción en los logros', paragraphs: ['La posición explica también la rima. Los interludios llevan los logros de contar del juego en secuencia — el "Five, six, grab your crucifix..." de la Part 3 es la tercera línea, y el conjunto se resuelve con "Nine, Ten, Never Jank Again." en el Final Aftermath. Leer la lista de logros de arriba abajo es leer el propio orden de los interludios; así queda fijada la posición en la ruta anterior: el orden de logros de Steam pone The Aftermath Part 3 directamente entre el desbloqueo del capítulo de Luna y el tramo de Underworld VHS.'] },
      { title: 'Cómo llegar al Aftermath 3', paragraphs: [], bullets: ['Completa Luna’s Cream Filled Donuts: trabaja el turno de atención hasta el final — el capítulo en que Luna y el jefe O’Brien encuentran su destino —, y la historia pasa al interludio automáticamente', 'Deja que el interludio corra: el logro "Five, six, grab your crucifix..." cae cuando el capítulo termina; no hay elección, condición escondida ni coleccionable ligado al desbloqueo', 'Sigue hacia Underworld VHS: el próximo capítulo de localización abre a las 01:34:10 en la partida de referencia — el videoclub de Scaroline, un capítulo de aproximadamente 24 minutos por la línea temporal de la ruta'] },
      { title: 'Contexto en el recorrido total', paragraphs: ['Saber qué rodea al interludio ayuda a situarlo en el mapa: antes de él, la ruta ya jugó cinco capítulos de localizaciones, con Luna’s Cream Filled Donuts como el quinto; después del videoclub, solo queda la Lazar’s Blood Bank antes de que los capítulos finales tomen el mando. Aftermath Part 3 es la bisagra entre el acorde final de la donut shop y el capítulo del videoclub que recoge el hilo del VHS plantado por la escena de Luna — el momento en que el juego deja de presentar víctimas y empieza a cerrar el caso.'] }
    ],
    faq: [
      { question: '¿Qué es el Aftermath 3 en The Skin Stapler?', answer: 'El tercero de los cuatro interludios Aftermath — el capítulo que lleva las historias de las víctimas de vuelta a la investigación de Slater entre la donut shop de Luna y el videoclub Underworld VHS.' },
      { question: '¿Qué logro desbloquea?', answer: '"Five, six, grab your crucifix...", por completar The Aftermath Part 3 Chapter — la tercera línea de la canción de contar de los logros de los interludios.' },
      { question: '¿Dónde cae el Aftermath 3 en la ruta?', answer: 'Entre Luna’s Cream Filled Donuts (fin cerca de 01:15:37) y Underworld VHS (apertura a las 01:34:10) en el orden de progresión.' },
      { question: '¿El Aftermath 3 es jugable?', answer: 'El grado exacto de interacción de los interludios no está documentado por separado. Oficialmente es uno de los 14 capítulos, y el logro cae al completarlo, independientemente del formato.' },
      { question: '¿Cuántos capítulos Aftermath hay?', answer: 'Cuatro partes numeradas más el Final Aftermath — cinco interludios dentro del total de 14 capítulos, cada uno con logro propio de conclusión.' }
    ],
    sources: sourceSets['aftermath-3']
  }
};
