import type { BatchThreeArticleId, LocalizedArticle } from './types';

const sourceSets: Record<BatchThreeArticleId, Array<{ label: string; url: string }>> = {
  review: [
    { label: 'Bloody Disgusting — análise publicada de The Skin Stapler', url: 'https://bloody-disgusting.com/video-games/3962809/the-skin-stapler-review-psx-horror-throwback-favors-humor-over-gameplay/' },
    { label: 'Steam — página oficial do jogo completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'Steam — demo oficial', url: 'https://store.steampowered.com/app/4343530/The_Skin_Stapler_Demo/' }
  ],
  story: [
    { label: 'Steam — página oficial do jogo completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'CaseOh — playthrough completo', url: 'https://www.youtube.com/watch?v=EcgnRprUU5k' },
    { label: 'GabeHype — playthrough 100%', url: 'https://www.youtube.com/watch?v=1kEFUOGxgjE' },
    { label: 'Steam Community — lista oficial de conquistas', url: 'https://steamcommunity.com/stats/4310610/achievements' }
  ],
  'games-like': [
    { label: 'Bloody Disgusting — análise com títulos de comparação', url: 'https://bloody-disgusting.com/video-games/3962809/the-skin-stapler-review-psx-horror-throwback-favors-humor-over-gameplay/' },
    { label: 'Steam — página oficial do jogo completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'GOG — página oficial da loja', url: 'https://www.gog.com/en/game/the_skin_stapler' },
    { label: 'Tainted Pact — página oficial no itch.io', url: 'https://taintedpact88.itch.io/the-skin-stapler' }
  ],
  uncensored: [
    { label: 'Steam — página oficial do jogo completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'GOG — página oficial da loja', url: 'https://www.gog.com/en/game/the_skin_stapler' },
    { label: 'Steam — demo oficial', url: 'https://store.steampowered.com/app/4343530/The_Skin_Stapler_Demo/' }
  ],
  'donut-shop': [
    { label: 'Steam Community — lista oficial de conquistas', url: 'https://steamcommunity.com/stats/4310610/achievements' },
    { label: 'GabeHype — playthrough 100%', url: 'https://www.youtube.com/watch?v=1kEFUOGxgjE' },
    { label: 'Steam — página oficial do jogo completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' }
  ],
  'all-tapes': [
    { label: 'Steam — página oficial do jogo completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'Steam Community — lista oficial de conquistas', url: 'https://steamcommunity.com/stats/4310610/achievements' },
    { label: 'CaseOh — playthrough completo', url: 'https://www.youtube.com/watch?v=EcgnRprUU5k' }
  ],
  'ai-generated': [
    { label: 'Steam — página oficial com a declaração handmade', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'Tainted Pact — página oficial no itch.io', url: 'https://taintedpact88.itch.io/the-skin-stapler' },
    { label: 'Tainted Pact — canal oficial no YouTube', url: 'https://www.youtube.com/@TaintedPactGames' }
  ],
  developer: [
    { label: 'Tainted Pact — página oficial no itch.io', url: 'https://taintedpact88.itch.io/the-skin-stapler' },
    { label: 'Tainted Pact — canal oficial no YouTube', url: 'https://www.youtube.com/@TaintedPactGames' },
    { label: 'Steam — página oficial do jogo completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'GOG — página oficial da loja', url: 'https://www.gog.com/en/game/the_skin_stapler' }
  ],
  'janker-edition': [
    { label: 'Steam — DLC The Skin Jankers (App 4919860)', url: 'https://store.steampowered.com/app/4919860/' },
    { label: 'Steam — DLC da trilha sonora (App 4919810)', url: 'https://store.steampowered.com/app/4919810/' },
    { label: 'GOG — página da loja com o pacote Skin Jankers', url: 'https://www.gog.com/en/game/the_skin_stapler' }
  ],
  'turkish-patch': [
    { label: 'Steam — tabela de idiomas do jogo completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'Steam — tabela de idiomas da demo', url: 'https://store.steampowered.com/app/4343530/The_Skin_Stapler_Demo/' },
    { label: 'GOG — página oficial da loja', url: 'https://www.gog.com/en/game/the_skin_stapler' }
  ],
  'korean-patch': [
    { label: 'Steam — tabela de idiomas do jogo completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'Steam — tabela de idiomas da demo', url: 'https://store.steampowered.com/app/4343530/The_Skin_Stapler_Demo/' },
    { label: 'GOG — página oficial da loja', url: 'https://www.gog.com/en/game/the_skin_stapler' }
  ],
  'press-kit': [
    { label: 'Steam — galeria oficial de capturas de tela', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'YouTube — trailer oficial (5tEJiy8FJbY, 27 de janeiro de 2026)', url: 'https://www.youtube.com/watch?v=5tEJiy8FJbY' },
    { label: 'GOG — galeria oficial', url: 'https://www.gog.com/en/game/the_skin_stapler' }
  ],
  'final-aftermath': [
    { label: 'Steam Community — lista oficial de conquistas', url: 'https://steamcommunity.com/stats/4310610/achievements' },
    { label: 'GabeHype — playthrough 100%', url: 'https://www.youtube.com/watch?v=1kEFUOGxgjE' },
    { label: 'Steam — página oficial do jogo completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' }
  ],
  'aftermath-3': [
    { label: 'Steam Community — lista oficial de conquistas', url: 'https://steamcommunity.com/stats/4310610/achievements' },
    { label: 'GabeHype — playthrough 100%', url: 'https://www.youtube.com/watch?v=1kEFUOGxgjE' },
    { label: 'Steam — página oficial do jogo completo', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' }
  ]
};

export const batchThreePtBr: Record<BatchThreeArticleId, LocalizedArticle> = {
  review: {
    id: 'review', keyword: 'The Skin Stapler análise',
    title: 'The Skin Stapler análise: veredito, acertos e falhas',
    description: 'A análise de The Skin Stapler: 2,5 horas de horror grindhouse, capítulos de vítimas de tirar o fôlego, mecânica rasa — e para quem a compra de 14,99 euros vale a pena.',
    eyebrow: 'Análise e decisão de compra',
    directAnswer: 'The Skin Stapler é um horror grindhouse de 2,5 horas em 14 capítulos curtos, cuja força está nos capítulos de vítimas cheios de tensão e cuja fraqueza é a mecânica leve. A Bloody Disgusting recomenda claramente para fãs de Sniper Killer e Rewind or Die — e desaconselha os demais. As avaliações da Steam ficaram perto de 90% positivas na janela de lançamento, com cerca de 340 análises.',
    date: '2026-09-03',
    sections: [
      { title: 'O veredito em resumo', paragraphs: ['A análise publicada pela Bloody Disgusting examinou a versão completa e resume o jogo como um título grindhouse curto e grosseiro por opção. Estes são os pontos que pesam na sua decisão de compra:'], bullets: ['Duração: cerca de 2,5 horas em 14 capítulos curtos', 'Estrutura: os capítulos alternam entre investigação e perspectiva da caçada', 'Melhor momento: os capítulos de vítimas, em especial a abertura com a Fefe', 'Ponto fraco: mecânica rasa e repetitiva em alguns trechos', 'Apresentação: sequências FMV estilo VHS e a Carrion City de 1984 convencem', 'Nota: escala de caveiras em vez de número — fãs de Sniper Killer e Rewind or Die somam uma caveira, os demais subtraem', 'Clima na Steam: cerca de 90% positivas entre aproximadamente 340 análises na janela de lançamento'] },
      { title: 'Que jogo está sendo analisado?', paragraphs: ['The Skin Stapler é um jogo de horror curto e guiado pela história, ambientado na Carrion City de 1984, uma cidade repleta de excêntricos absurdos. Você alterna entre o detetive desgastado Dick Slater na investigação e a perspectiva do perseguidor nos capítulos de caçada. O pitch da própria editora — caçar um serial killer por um pesadelo de horror curto e guiado pela história — é a moldura da análise.', 'Quatorze capítulos curtos preenchem as 2,5 horas. Nove são capítulos jogáveis de locações como os Burrows Apartments, o Quick Fix e a Lazar’s Blood Bank; o restante são interlúdios Aftermath que devolvem cada história de vítima ao dossiê de Slater.'] },
      { title: 'O que a análise elogia', paragraphs: ['Os capítulos de vítimas são o auge. O analista chama a abertura com a Fefe no apartamento de capítulo mais tenso do jogo, e as demais jornadas de trabalho mantêm o nível: turnos comuns — servir cachorro-quente, rechear donuts, rebobinar fitas — enquanto uma figura mascarada se aproxima. Essa ironia dramática é o melhor truque do design.', 'A apresentação recebe a segunda rodada de elogios: as sequências FMV estilo VHS, a trilha synthwave retrô e o elenco totalmente dublado dão ao jogo sua identidade grindhouse. O roteiro também convence — Carrion City é repleta de tipos grotescos de propósito, e segundo a tagline da editora ainda há um último riso antes da morte.'] },
      { title: 'O que a análise critica', paragraphs: ['Os dois modos de jogo continuam rasos em mecânica. Os capítulos de investigação se reduzem a áreas pequenas e tarefas curtas, e os de caçada apostam em loops curtos de interação. A frase do analista: a mecânica parece um pouco repetitiva — ao longo de 14 capítulos, o vocabulário de interação quase não cresce.', 'É por isso que o veredito recai sobre gosto adquirido, e não em recomendação universal. A análise trata a mecânica rasa como o preço do humor e do ritmo, sem alegar que os sistemas são profundos.'] },
      { title: 'A questão da nota', paragraphs: ['A Bloody Disgusting avalia em caveiras, não em números, e o veredito sobre The Skin Stapler é uma piada com utilidade: fãs de Sniper Killer ou Rewind or Die somam uma caveira, todos os outros subtraem uma. Não existe nota numérica para citar — qualquer nota de outro site que você vir ligada a este jogo merece conferência na página original do veículo.', 'Na tradução prática: para o público-alvo, a análise é uma recomendação clara; fora dele, um passe. O analista recebeu, segundo a própria divulgação, uma cópia fornecida pela editora — prática comum, revelada na própria análise.'] },
      { title: 'O que os números dos jogadores acrescentam', paragraphs: ['O público do lançamento confirmou o tom do jogo. O playthrough completo do CaseOh passou de 2.102.706 visualizações após 9 de agosto de 2026, e o vídeo do Joe Bartolozzi ultrapassou 1,37 milhão na semana seguinte — o humor em clipes alcança muito além das 2,5 horas. A Steam registrava na janela de lançamento perto de 90% de avaliações positivas entre cerca de 340 votos.', 'Números não respondem à questão do gosto — um milhão de visualizações de uma cena de cachorro-quente não é uma análise —, mas mostram quais momentos o público abraça.'] },
      { title: 'Como decidir em três passos', paragraphs: [], bullets: ['Jogue primeiro a demo gratuita: três trechos — delegacia, Quick Fix e Gutters End — mostram tom e ritmo em 30 a 45 minutos', 'Assista a um capítulo de vítima: poucos minutos de um turno de trabalho revelam se tensão mais comédia funciona para você; os vídeos do CaseOh e do Joe Bart são a amostra mais rápida sem spoiler do final', 'Compre pela história, não pelos sistemas: com 2,5 horas e 14,99 euros na Steam, o valor é uma história grindhouse assistida de uma vez com dublagem completa — dentro dessa moldura, as críticas pesam menos'] }
    ],
    faq: [
      { question: 'Quanto dura The Skin Stapler?', answer: 'Cerca de 2,5 horas para a rota principal de 14 capítulos; runs gravadas com exploração ficam entre aproximadamente 2h46 e 3 horas.' },
      { question: 'The Skin Stapler assusta ou faz rir?', answer: 'Os dois, por escolha de design. Os capítulos de vítimas trabalham a tensão enquanto os diálogos, cortes FMV e coadjuvantes grotescos entregam as risadas — a análise chama a mistura de macabra e engraçada ao mesmo tempo.' },
      { question: 'Os analistas ganharam cópia grátis?', answer: 'Sim. A Bloody Disgusting revela que o código de análise foi fornecido pela editora — prática comum, declarada na própria análise.' },
      { question: 'Existe nota numérica?', answer: 'Não. O site avalia em caveiras: uma a mais para fãs de Sniper Killer e Rewind or Die, uma a menos para todos os outros.' },
      { question: 'O que os jogadores dizem em comparação aos críticos?', answer: 'A mesma divisão: cerca de 90% de avaliações positivas na Steam na janela de lançamento, e a crítica mais comum repete a da análise — mecânica leve e duração curta.' }
    ],
    sources: sourceSets.review
  },
  story: {
    id: 'story', keyword: 'The Skin Stapler história',
    title: 'The Skin Stapler história: enredo e final explicados',
    description: 'A história de The Skin Stapler: Dick Slater caça o Skin Stapler pela Carrion City de 1984 — motivo, identidade, fitas e o único final no Flesh Pit.',
    eyebrow: 'Enredo com spoilers',
    directAnswer: 'Em 1984, o detetive Dick Slater caça um serial killer pela Carrion City enquanto o jogo alterna entre as vítimas e o próprio assassino. O assassino é Elias Crow, dono da churrascaria Flesh Pit, e o motivo é vingança: Slater matou seu irmão gêmeo, Silus Kain. A história dura cerca de 2,5 a 4 horas em 14 capítulos curtos e tem exatamente um final.',
    date: '2026-09-03',
    sections: [
      { title: 'A história em resumo', paragraphs: ['Esses fatos formam a estrutura do enredo — as seções abaixo detalham cada um:'], bullets: ['Cenário: Carrion City, 1984', 'Investigador: detetive Dick Slater, com o novato Robbie Knox', 'Assassino: Elias Crow, dono da churrascaria Flesh Pit', 'Motivo: vingança pelo irmão gêmeo Silus Kain, morto por Slater', 'Estrutura: 9 capítulos jogáveis de locações + 4 partes de Aftermath + o Final Aftermath', 'Duração: cerca de 2,5 horas em linha reta; runs mais longas chegam perto de 4 horas', 'Finais: um único final da trama principal, sem ramificações'] },
      { title: 'A premissa', paragraphs: ['A premissa oficial da loja inicia a história com um padrão sombrio: as vítimas são esfoladas, a pele é grampeada nas paredes próximas, e fitas de áudio distorcidas deixadas nas cenas provocam a polícia. Slater, um detetive desgastado, recebe o caso — e o gancho é que você não joga só a investigação: passa capítulos dentro da vida de quem está sendo perseguido.', 'Essa estrutura dupla é o motor da história. Um capítulo te coloca na mesa de Slater na delegacia de Carrion City; o seguinte, num apartamento, numa loja ou num boliche, enquanto o perseguidor se aproxima. Os interlúdios Aftermath devolvem cada história de vítima ao dossiê, até a investigação apontar um suspeito.'] },
      { title: 'Como os 14 capítulos contam a história', paragraphs: ['A rota jogável: Burrows Apartments com a Fefe na abertura, Carrion City Police Department com Slater, Quick Fix com a Hexy, Gutters End com a Blair, a donut shop da Luna, Underworld VHS com a Scaroline e a Lazar’s Blood Bank com a enfermeira Layna. Quatro interlúdios Aftermath ficam entre os capítulos de locações, e o Final Aftermath conecta a investigação ao trecho final. Depois vem Closing In, e The Flesh Pit fecha a história.', 'A lista de conquistas da Steam confirma exatamente essa sequência de capítulos, e o walkthrough de referência marca os horários: Burrows Apartments às 00:03:06 até The Flesh Pit às 02:34:00.'] },
      { title: 'A identidade do assassino: Elias Crow', paragraphs: ['A investigação caminha para uma única revelação: o Skin Stapler é Elias Crow, o dono público da Flesh Pit, anunciada no jogo como o melhor barbecue da cidade. O nome fica escondido à vista de todos — o anúncio da Flesh Pit aparece cedo, e diálogos do fim do jogo afirmam diretamente que Elias Crow é o dono do restaurante.', 'A revelação funciona porque o jogo distribui as peças entre as perspectivas: arquivos de suspeitos, o anúncio da Flesh Pit, fitas das cenas de crime e os segmentos Aftermath guardam um fragmento cada, e os detetives montam tudo na tela em vez de receber uma exposição única.'] },
      { title: 'A origem dos gêmeos e o motivo', paragraphs: ['O motivo é a espinha emocional da história: Slater matou o irmão gêmeo de Elias, Silus Kain, e Elias constrói sua sequência de crimes para infligir a Slater uma perda equivalente. Um diálogo do fim do jogo resume: Dick, você matou o irmão dele, e agora Elias quer vingança.', 'Uma gravação do orfanato, na voz do Padre Omani, explica como dois irmãos pararam em lados opostos do mesmo caso: os gêmeos foram separados no nascimento, um entregue à família Ken e chamado de Silus, o outro à família Crow e chamado de Elias. Legendas automáticas grafam o sobrenome como Kane ou Ken em alguns pontos; este site padroniza Kain, a grafia usada nas páginas de walkthrough e final.'] },
      { title: 'Como as fitas movem o enredo', paragraphs: ['As fitas de áudio distorcidas são o tecido conjuntivo da história. O assassino as deixa nas cenas para provocar a polícia, e consertá-las e analisá-las virou tarefa constante da investigação — a conquista Jank Ya Later! da Steam desbloqueia justamente por reparar as fitas do Skin Stapler. A gravação do orfanato, a pista mais profunda da história, também chega por fita.', 'Capítulos individuais alimentam o fio das fitas: uma VHS recuperada da cena da Luna entra no caso, e o capítulo de Scaroline no Underworld VHS acontece exatamente na locadora onde mexer em fitas é o trabalho.'] },
      { title: 'O final: uma confrontação no Flesh Pit', paragraphs: ['A história tem um final, e duas runs completas independentes confirmam a mesma sequência. Slater rastreia o assassino até a Flesh Pit, o restaurante do próprio Elias. Elias conquista a vantagem primeiro: Robbie Knox é abatido, e Elias pressiona Slater a pegar a arma de Robbie. Slater pega, atira em Elias e deixa Carrion City.', 'Não existe menu moral, diálogo ramificado nem final alternativo. O que acontece com Elias depois — morte no local ou prisão — permanece sem resposta nas gravações verificadas. De todo modo, o detetive deixa a cidade, e a história termina onde começou: Slater, o caso e uma cidade que tirou tudo dos dois irmãos.'] },
      { title: 'Como viver a história', paragraphs: [], bullets: ['Jogue os capítulos de locações na ordem da rota: o jogo é linear, e cada virada desagua direto na próxima; a seleção de capítulos existe para replays', 'Trate cada interação com fitas: as fitas reparadas são dispositivos de enredo primeiro e conquistas depois — a gravação do orfanato e as fitas das cenas são as duas maiores revelações', 'Não pule os interlúdios Aftermath: as quatro partes e o Final Aftermath conectam os capítulos de vítimas ao caso de Slater; sem eles, a linha narrativa quebra'] }
    ],
    faq: [
      { question: 'Quem é o Skin Stapler na história?', answer: 'Elias Crow, dono da churrascaria Flesh Pit. A investigação revela sua identidade no fim do jogo, e o confronto final acontece no restaurante.' },
      { question: 'Por que o Skin Stapler mata as vítimas?', answer: 'Vingança. Slater matou seu irmão gêmeo Silus Kain, e Elias monta os assassinatos como resposta — vítimas esfoladas, pele grampeada nas paredes e fitas provocadoras para a polícia.' },
      { question: 'Quanto dura a história?', answer: 'Cerca de 2,5 horas em linha reta pelos 14 capítulos; runs gravadas com mais exploração chegam perto de 3 horas, e primeiras jogadas mais lentas podem alcançar 4.' },
      { question: 'Slater pega o assassino?', answer: 'Sim. A história termina na Flesh Pit, onde Slater atira em Elias depois de Robbie ser abatido e deixa Carrion City.' },
      { question: 'A história é conectada à demo?', answer: 'Os três trechos da demo — delegacia, Quick Fix e Gutters End — são os segundo, terceiro e quarto capítulos da história em forma resumida. O jogo completo começa do início, no apartamento da Fefe.' }
    ],
    sources: sourceSets.story
  },
  'games-like': {
    id: 'games-like', keyword: 'jogos como The Skin Stapler',
    title: 'Jogos como The Skin Stapler: os 6 parecidos mais próximos',
    description: 'Sniper Killer, Rewind or Die e os quatro horrores anteriores da Tainted Pact: os jogos mais parecidos com The Skin Stapler e o que cada um compartilha.',
    eyebrow: 'Recomendações de jogos',
    directAnswer: 'Os jogos mais parecidos com The Skin Stapler são Sniper Killer e Rewind or Die — os dois títulos citados pela análise da Bloody Disgusting como comparações diretas — mais os quatro horrores anteriores da mesma desenvolvedora, a Tainted Pact: Suffer the Night, Terror at Oakheart, Massacre at the Mirage e Flesh Made Fear. Os seis dividem a duração curta, o humor grindhouse e a apresentação de horror low-poly que definem The Skin Stapler.',
    date: '2026-09-03',
    sections: [
      { title: 'Os parecidos em resumo', paragraphs: ['As comparações vêm de duas direções: a análise que cita Sniper Killer e Rewind or Die, e o catálogo da desenvolvedora e da editora que lista os quatro títulos da Tainted Pact:'], bullets: ['Sniper Killer — citado pela análise como a comparação mais próxima: premissa de serial killer, ritmo de job-sim, visuais PSX', 'Rewind or Die — a outra comparação direta da análise: estética VHS, mecânicas de fita, humor grindhouse', 'Suffer the Night — primeiro horror publicado da Tainted Pact: analog horror com computação retrô assustadora', 'Terror at Oakheart — Tainted Pact: slasher num acampamento com violência estilizada e tom de filme B', 'Massacre at the Mirage — Tainted Pact: slasher confinado a um hotel com estrutura curta por cenas', 'Flesh Made Fear — Tainted Pact: o predecessor direto de The Skin Stapler, história de serial killer com cenas dubladas'] },
      { title: 'Por que Sniper Killer é o match número 1', paragraphs: ['Sniper Killer combina a caça a um serial killer com tarefas mundanas de trabalho e uma estética PSX propositalmente feia — o mesmo esqueleto sobre o qual The Skin Stapler foi construído. Quem analisou The Skin Stapler o cita pelo nome, o que o torna a compra mais segura para quem quer o mais perto de outro caso em Carrion City.', 'O tom também bate: os dois jogos tratam o material grotesco com seriedade e deboche ao mesmo tempo, apostam em diálogos dublados e embrulham uma história curta em interações simples. Se a sua parte favorita foi a investigação, Sniper Killer é a experiência mais próxima; se foram os turnos das vítimas, o catálogo da Tainted Pact é o caminho melhor.'] },
      { title: 'Por que Rewind or Die aparece sempre', paragraphs: ['Rewind or Die compartilha o DNA de locadora retrô que The Skin Stapler exibe sem disfarce — estética VHS, mecânicas de fita e roteiro de slasher movido a piadas. A análise o cita ao lado de Sniper Killer como teste de público: fãs de qualquer um dos dois são o perfil que soma uma caveira à nota de The Skin Stapler.', 'Também é o match certo para quem mais gostou do capítulo de Scaroline no Underworld VHS: a locadora, a rebobinação de fitas e o humor de vídeo analógico apontam na mesma direção.'] },
      { title: 'Os quatro horrores anteriores da Tainted Pact', paragraphs: ['A Tainted Pact fez The Skin Stapler sozinha, e o catálogo do estúdio lista quatro títulos anteriores, confirmados pelo anúncio da editora e pelo catálogo do GOG:'], bullets: ['Suffer the Night — a estreia de analog horror do estúdio, construída em torno de um computador retrô assombrado e uma figura que persegue de dentro de um jogo fictício', 'Terror at Oakheart — um slasher num acampamento, mantendo a estrutura curta e a violência estilizada na tela', 'Massacre at the Mirage — um slasher confinado a um hotel, com o mesmo ritmo cena a cena e escrita de comédia negra', 'Flesh Made Fear — o predecessor mais direto: história de serial killer com cenas dubladas e ponta grindhouse que desemboca naturalmente na Carrion City'] },
      { title: 'O que esses jogos compartilham além do tom', paragraphs: ['As semelhanças são estruturais, não só visuais:'], bullets: ['Durações curtas: The Skin Stapler roda cerca de 2,5 horas em 14 capítulos; os comparáveis são todos jogos de uma sentada', 'Loops de job-sim e interações estilo QTE: servir cachorro-quente, rechear donuts, rebobinar fitas — a tarefa mundana como motor do horror é a assinatura do gênero', 'Elencos totalmente dublados: The Skin Stapler credita dez intérpretes nomeados, e o grupo de comparação também prefere dublagem completa a texto', 'Trilhas synth retrô: temas de sintetizador estilo Carpenter atravessam todo o catálogo', 'FMV e rigor de formato de vídeo: sequências full-motion estilo VHS são a cola de apresentação desses jogos', 'Humor propositalmente grosseiro: a tagline da editora — espere um último riso antes de morrer — resume o registro cômico compartilhado'] },
      { title: 'Como escolher o próximo jogo em três passos', paragraphs: [], bullets: ['Combine com o capítulo que você mais gostou: investigação aponta para Sniper Killer; a locadora para Rewind or Die; os turnos das vítimas para Flesh Made Fear e os jogos anteriores da Tainted Pact', 'Confira a duração desejada: todos são curtos — se você quer outra história de 2 a 4 horas numa sentada, qualquer um serve; se quer investimento longo, nenhum é a prateleira certa', 'Compre nas lojas oficiais: o catálogo da Tainted Pact se vende na Steam e no GOG, e o guia de download de PC lista as lojas oficiais do título mais novo'] }
    ],
    faq: [
      { question: 'Existe sequência ou outro jogo exatamente como The Skin Stapler?', answer: 'Não há sequência direta. Flesh Made Fear é o jogo anterior mais próximo do mesmo estúdio, e Sniper Killer é o match mais próximo fora dele.' },
      { question: 'Os jogos da Tainted Pact são conectados na história?', answer: 'Não há universo compartilhado confirmado entre os quatro títulos anteriores e The Skin Stapler. A conexão é tom, formato e desenvolvedora, não enredo.' },
      { question: 'Qual jogo jogar primeiro depois de The Skin Stapler?', answer: 'Sniper Killer: a crítica o cita como a comparação direta, e seu loop de investigação de serial killer espelha de perto os capítulos de Slater.' },
      { question: 'Esses jogos têm o mesmo humor?', answer: 'Sim — piadas grindhouse, coadjuvantes grotescos e interpretação de filme B são o registro compartilhado, resumido pela tagline da editora.' },
      { question: 'Algum deles está no Game Pass ou em serviços de assinatura?', answer: 'A disponibilidade em assinatura muda por serviço e região — confira a página atual de cada jogo. Steam e GOG seguem sendo os canais de compra confirmados do catálogo.' }
    ],
    sources: sourceSets['games-like']
  },
  uncensored: {
    id: 'uncensored', keyword: 'The Skin Stapler sem censura',
    title: 'The Skin Stapler sem censura: versões, conteúdo e classificação',
    description: 'The Skin Stapler não tem versão censurada: Steam e GOG distribuem um único build sem cortes — veja o que o jogo mostra e como conferir antes de comprar.',
    eyebrow: 'Conteúdo e versões',
    directAnswer: 'The Skin Stapler não é vendido em versão censurada. Steam e GOG distribuem um único build sem cortes — o mesmo jogo de 14 capítulos com o gore intacto —, e não existe SKU "sem censura" separado, corte regional nem interruptor de conteúdo em nenhuma das lojas. A descrição oficial do que o assassino faz às vítimas aparece nas próprias páginas de compra, sem suavização.',
    date: '2026-09-03',
    sections: [
      { title: 'O que uma versão única significa na prática', paragraphs: ['O que você vê na página da loja é o que vem no disco. Não há nada para desbloquear, nada para alternar e nenhuma edição mais leve para comprar no lugar:'], bullets: ['Steam: um jogo base (App 4310610) mais dois DLCs; nenhuma versão cortada separada', 'GOG: um jogo completo; as skins do DLC vêm incluídas no build do GOG', 'Interruptor de conteúdo: nenhum anunciado em nenhuma página de loja', 'Cortes regionais: nenhum oferecido nem documentado nas páginas oficiais', 'Classificação etária: nenhuma PEGI ou ESRB exibida nas páginas das lojas', 'Intensidade do conteúdo: vítimas esfoladas, pele grampeada, fitas distorcidas, material sexual e personagens grotescos'] },
      { title: 'O que o conteúdo sem censura inclui', paragraphs: ['A mecânica que dá título ao jogo é o próprio aviso de conteúdo. As vítimas são esfoladas e têm a pele grampeada nas paredes — o texto oficial da loja descreve isso como a assinatura do assassino, e o jogo encena as cenas de crime em torno desse método. As imagens de pele costurada na galeria oficial representam o que o jogo mostra no motor.', 'A análise da Bloody Disgusting completa o perfil de intensidade: violência gráfica, material sexual e personagens deliberadamente grotescos. O marketing da própria editora mergulha no mesmo registro — o material de imprensa promete um último riso antes de morrer, e as piadas do jogo soam na mesma frequência de comédia doentia do gore. Quem procura uma versão sem censura costuma procurar na direção errada: o jogo nunca foi suavizado.'] },
      { title: 'Por que não existe SKU separado sem censura', paragraphs: ['A estrutura de produtos da Steam torna a resposta estrutural: a loja lista uma aplicação base mais dois DLCs — um pacote de skins cosméticas e uma trilha sonora — sem builds alternativos. A página do GOG espelha isso com um único jogo que agrega o DLC de skins. Uma variante censurada exigiria uma segunda entrada na loja, um interruptor no lançamento ou uma nota regional, e nada disso existe na distribuição oficial do jogo.', 'Essa estrutura também responde buscas como "patch sem censura" ou "conteúdo restaurado": não há nada removido para restaurar. O build único da desenvolvedora é o build completo, e o guia de download de PC lista as duas lojas oficiais que o vendem.'] },
      { title: 'Classificação etária e bloqueios das lojas', paragraphs: ['Nem a Steam nem o GOG exibem classificação PEGI ou ESRB para The Skin Stapler — comum em lançamentos indie pequenos que vendem por lojas digitais sem distribuição no varejo. As lojas aplicam seus próprios bloqueios de idade no momento da compra. Se classificação importa para a sua casa ou para as regras da sua região, confira a listagem local antes de comprar — os descritores de conteúdo acima são a melhor prévia do que o jogo contém.', 'A demo segue a mesma política: é gratuita, contém a mesma violência estilizada e não carrega classificação separada na sua página. O guia da demo cobre o que os três trechos incluem.'] },
      { title: 'Como conferir o conteúdo em três passos', paragraphs: [], bullets: ['Abra a galeria da Steam: as capturas oficiais mostram a renderização real do jogo — retratos de pele costurada, cenas de crime e a obra do assassino — sem suavização editorial', 'Assista a um capítulo gravado: as runs completas da abertura da Fefe e do trecho do Quick Fix são públicas e mostram como a violência é encenada e com que frequência aparece', 'Leia a descrição da loja em voz alta: vítimas esfoladas, pele grampeada, fitas provocadoras — o pitch oficial é o aviso de conteúdo mais honesto disponível, e as duas lojas o exibem na página de compra'] }
    ],
    faq: [
      { question: 'The Skin Stapler é censurado na Steam?', answer: 'Não. A Steam vende um único build sem cortes, e a própria descrição da loja descreve a violência assinatura do jogo sem suavização.' },
      { question: 'A versão do GOG é diferente da da Steam?', answer: 'O lançamento no GOG é o mesmo jogo sem cortes e inclui o DLC cosmético Skin Jankers na compra. Na Steam, esse DLC se vende separado. Nenhuma das lojas oferece corte de conteúdo diferente.' },
      { question: 'Existe um interruptor para desligar o gore?', answer: 'Nenhum interruptor de conteúdo é anunciado nas páginas das lojas. O jogo vem com a violência como parte central de sua identidade.' },
      { question: 'Por que não acho uma classificação etária para o jogo?', answer: 'Nenhuma PEGI ou ESRB aparece nas páginas das lojas. Lançamentos indie digitais frequentemente dispensam classificação formal e dependem dos bloqueios das lojas — confira a listagem da sua região antes de comprar.' },
      { question: 'A demo contém o mesmo conteúdo?', answer: 'Sim. A demo gratuita mostra a mesma violência estilizada nos seus três trechos jogáveis — exatamente por isso funciona como prévia de conteúdo antes da compra.' }
    ],
    sources: sourceSets.uncensored
  },
  'donut-shop': {
    id: 'donut-shop', keyword: 'The Skin Stapler código da donut shop',
    title: 'The Skin Stapler código da donut shop: não existe — e o que fazer',
    description: 'Não há código na Luna’s Cream Filled Donuts: o capítulo é um turno de atendimento. Veja o que realmente existe, o código 1979 e a conquista do capítulo.',
    eyebrow: 'Códigos e capítulos',
    directAnswer: 'Não existe código de donut shop em The Skin Stapler. A Luna’s Cream Filled Donuts é um capítulo jogável de trabalho — você preenche pedidos de donuts e café passo a passo —, sem cofre, sem teclado numérico e sem senha. O jogo não traz código de resgate, senha mestra nem código de pulo de capítulo; o único código numérico real é 1979, do quadro de fotos durante a investigação.',
    date: '2026-09-03',
    sections: [
      { title: 'O que o capítulo da donut shop pede de verdade', paragraphs: ['A lista de conquistas da Steam confirma o nome e a posição do capítulo, e as gravações completas confirmam o formato: é um loop de atendimento no mesmo molde da sequência de cachorro-quente da Hexy no Quick Fix, não uma caixa de quebra-cabeça:'], bullets: ['Nome do capítulo: Luna’s Cream Filled Donuts (lista oficial de conquistas da Steam)', 'Personagem jogável: Luna, dona da loja', 'Posição na rota: entre Gutters End e Underworld VHS — o quinto capítulo de locação', 'Tipo de objetivo: trabalho de atendimento em vários passos — donuts e café em sequência', 'Código ou senha: nenhum — o progresso vem de completar os passos do atendimento', 'Conquista relacionada: LunaArcana - Glazed and Confused, por completar o capítulo'] },
      { title: 'Por que jogadores procuram um código de donut shop', paragraphs: ['Dois jogos diferentes se misturam nas buscas. O primeiro é o próprio The Skin Stapler: é um jogo de horror cheio de imagens de códigos — teclados numéricos, evidências, gavetas trancadas —, então jogadores assumem que cada locação nomeada esconde uma senha. O segundo é o hábito do gênero: jogos de horror estilo PSX costumam usar códigos numéricos, e os buscadores completam o padrão mesmo quando este jogo específico não tem esse quebra-cabeça.', 'O código numérico real de The Skin Stapler mora em outro lugar: a fechadura do quadro de fotos na linha da investigação, cuja solução é 1979. Se você chegou aqui caçando uma resposta de quatro dígitos, 1979 é o único código que o jogo realmente usa.'] },
      { title: 'Como o capítulo progride', paragraphs: [], bullets: ['Comece o turno: o capítulo da Luna abre no balcão, e o aviso de objetivo te leva ao fluxo de atendimento — os objetivos na tela são o único tutorial de que você precisa', 'Preencha cada pedido em sequência: donuts e café seguem o preparo em vários passos que o jogo mostra; terminar um pedido libera o próximo cliente, exatamente como no loop do Quick Fix', 'Complete o turno para avançar a história: o capítulo termina quando o atendimento acaba e a cena do enredo acontece — não há código escondido nem fechadura opcional; a conquista cai no fim do capítulo'] },
      { title: 'Os códigos que realmente existem no jogo', paragraphs: ['As respostas confirmadas de quebra-cabeça são poucas e documentadas: o código 1979 do quadro de fotos nos capítulos de investigação, o quebra-cabeça da balança de carne na Flesh Pit e as interações com as fitas danificadas que alimentam a história e liberam a conquista de reparo. Nenhuma delas se conecta à donut shop da Luna, e nenhuma usa um código de texto para resgatar.', 'Também não existe código universal de pulo. O walkthrough completo nota que alegações de senha mestra ou pulo de capítulo não têm apoio em nenhuma gravação completa — a rota avança cumprindo objetivos, ponto final.'] }
    ],
    faq: [
      { question: 'Qual é o código da donut shop em The Skin Stapler?', answer: 'Não existe. Luna’s Cream Filled Donuts é um capítulo de atendimento, e o jogo não tem código para ele. O único código de quatro dígitos é 1979, usado na fechadura do quadro de fotos durante a investigação.' },
      { question: 'O capítulo da donut shop está na demo?', answer: 'Não. A demo gratuita inclui três trechos — delegacia, Quick Fix e Gutters End. A loja da Luna é conteúdo do jogo completo.' },
      { question: 'Como desbloqueio a conquista Glazed and Confused?', answer: 'Complete o capítulo Luna’s Cream Filled Donuts. A conquista cai no fim do capítulo; não há condição escondida, ordem secreta nem código envolvido.' },
      { question: 'Quem é Luna?', answer: 'Luna administra a loja de donuts e café e é uma das perspectivas jogáveis do jogo. O guia de personagem da Luna cobre seu papel, sua dubladora e seu lugar na história.' },
      { question: 'Por que o Google sugere um código de donut shop?', answer: 'Os buscadores misturam as imagens de teclado e códigos do jogo com hábitos de outros horrores estilo PSX. O preenchimento automático não reflete um quebra-cabeça real deste jogo.' }
    ],
    sources: sourceSets['donut-shop']
  },
  'all-tapes': {
    id: 'all-tapes', keyword: 'The Skin Stapler fitas',
    title: 'The Skin Stapler fitas: todas as gravações e a conquista',
    description: 'As fitas de The Skin Stapler: provocações à polícia, evidências da investigação, a fita do orfanato e a conquista Jank Ya Later! de reparo.',
    eyebrow: 'Fitas e evidências',
    directAnswer: 'As fitas são a voz do assassino na história de The Skin Stapler: gravações de áudio distorcidas deixadas nas cenas de crime para provocar a polícia, mais as gravações da investigação que montam o caso. Você coleta, repara e revisa fitas ao longo da rota, e a conquista Jank Ya Later! desbloqueia especificamente por consertar as fitas do Skin Stapler. O jogo nunca mostra um contador total, então a contagem exata de fitas reparáveis é um detalhe para verificar no jogo.',
    date: '2026-09-03',
    sections: [
      { title: 'O que as fitas são e o que fazem', paragraphs: ['Seis funções, três papéis: as fitas são atmosfera, evidência e dispositivo de enredo ao mesmo tempo. As seções abaixo percorrem cada papel e mostram onde o trabalho com fitas entra na rota de capítulos:'], bullets: ['Papel oficial: gravações que provocam a polícia nas cenas de crime (descrição da loja)', 'Papel de jogo: itens que você repara e revisa como evidência da investigação', 'Papel na história: carregam a voz do assassino e a pista da origem dos gêmeos', 'Mecânica de reparo: fitas danificadas são consertadas ao longo da rota; não existe código universal de reparo', 'Conquista: Jank Ya Later! — Fix The Skin Stapler Tapes', 'Contagem total: não exibida no jogo nem publicada em material oficial'] },
      { title: 'As fitas de provocação: o assassino fala com a polícia', paragraphs: ['A premissa oficial é explícita: as vítimas são esfoladas e grampeadas nas paredes, e fitas de áudio distorcidas deixadas nas cenas provocam a polícia. Essas gravações dão voz ao assassino sem nunca mostrá-lo — o áudio do início é grotesco de propósito, e enquadra a investigação como uma conversa que o assassino mantém com Slater por meio das cenas de crime.', 'As fitas de provocação também definem o tom da história. A crítica marca a comédia negra como traço definidor, e o áudio das fitas é onde esse registro soa mais alto: o assassino faz performance para os investigadores, e a entrega distorcida de era VHS deixa as piadas mais frias.'] },
      { title: 'As fitas da investigação: o dossiê em forma de áudio', paragraphs: ['Além das provocações, o loop de reparar e revisar transforma fitas em evidência. Fitas danificadas aparecem pelos capítulos, e o jogo exige consertá-las ou revisá-las antes de a investigação avançar — a lista de conquistas da Steam nomeia a atividade diretamente, e as gravações completas mostram Slater mexendo em reparos no trecho final, na rádio do DJ Woolz.', 'Esse trecho de reparo é onde o fio das fitas se paga na mecânica: consertar as fitas do Skin Stapler é requisito nomeado de conquista, e as gravações reparadas alimentam as revelações que fecham o caso. Se uma interação de fita parece travada, a solução quase sempre é um diálogo não terminado ou um objetivo pendente na mesma sala — o walkthrough lista os portões de interação da rota em ordem.'] },
      { title: 'A fita do orfanato: a maior revelação da história', paragraphs: ['Uma gravação pesa mais que todas. O áudio do orfanato, na voz do Padre Omani, revela que o assassino e o irmão eram gêmeos separados no nascimento — um entregue à família Ken e chamado de Silus, o outro à família Crow e chamado de Elias. Essa única gravação converte a história de serial killer provocador numa história de vingança contra o próprio Slater.', 'O fio das fitas atravessa cada batida importante: a VHS recuperada da cena da Luna, a fita que Scaroline manuseia no Underworld VHS, a gravação de venha-me-encontrar do fim e a gravação privada do próprio Slater alimentam a mesma corrente de revelações. O guia da história apresenta o enredo completo com spoilers, e a página de identidade rastreia a revelação pista por pista.'] },
      { title: 'Onde o trabalho com fitas entra na rota', paragraphs: [], bullets: ['Capítulos de investigação: os trechos de Slater na CCPD abrem o loop de fitas — gravações das cenas entram no dossiê e as tarefas de reparo começam', 'Capítulos de trabalho: a loja da Luna e o Underworld VHS de Scaroline amarram fitas físicas à história: uma vira evidência de cena de crime, a outra faz do manuseio de fitas um trabalho jogável', 'A sessão de reparo do fim do jogo: o trecho de Closing In inclui a visita à rádio onde as fitas danificadas são consertadas — completar esse trabalho satisfaz a Jank Ya Later! e fecha a corrente de evidências antes do final'] },
      { title: 'Alegações da comunidade sobre as fitas', paragraphs: ['Uma wiki de fãs relata pequenas diferenças de epílogo conforme as fitas que você ouve — uma alegação que circula em todo jogo de horror com áudio colecionável. Runs completas comparadas mostrando finais diferentes nunca apareceram; duas jogadas completas independentes mostram o mesmo final, independentemente do manuseio das fitas. Até alguém publicar duas runs pareadas divergentes, trate a estrutura de final único como o fato operante.', 'O mesmo ceticismo vale para contagens. Sem contador no jogo nem número oficial, qualquer total visto por aí é, no máximo, estimativa de jogador — a resposta honesta é que o jogo não apresenta uma.'] }
    ],
    faq: [
      { question: 'Quantas fitas existem em The Skin Stapler?', answer: 'O jogo não exibe um total, e o material oficial não publica um — a contagem exata só fica clara com o jogo na mão. O que está confirmado é a mecânica: coletar, reparar e revisar conforme a rota pede.' },
      { question: 'Qual é a conquista das fitas?', answer: 'Runebee - Jank Ya Later!, que desbloqueia por consertar as fitas do Skin Stapler conforme o texto oficial de requisito da Steam.' },
      { question: 'As fitas mudam o final?', answer: 'Uma wiki de fãs afirma variação no epílogo, mas nenhuma run pareada demonstrou isso. Duas jogadas completas confirmam o mesmo final único.' },
      { question: 'Onde eu reparo as fitas?', answer: 'O trecho final da rota leva as fitas danificadas à rádio do DJ Woolz durante Closing In, conforme as gravações completas — o walkthrough o coloca perto de 02:18:29 na run de referência.' },
      { question: 'As fitas são a voz do assassino?', answer: 'Sim — a descrição da loja diz que fitas distorcidas provocam a polícia, e a gravação-chave, a do orfanato, expõe a origem dos gêmeos que explica o motivo do assassino.' }
    ],
    sources: sourceSets['all-tapes']
  },
  'ai-generated': {
    id: 'ai-generated', keyword: 'The Skin Stapler é gerado por IA',
    title: 'The Skin Stapler é gerado por IA? O que a página oficial mostra',
    description: 'Não: a Steam estampa "A HANDCRAFTED HORROR EXPERIENCE". Evidências verificáveis — 10 dublês nomeados, um desenvolvedor solo e FMV artesanais.',
    eyebrow: 'Produção e créditos',
    directAnswer: 'Não — The Skin Stapler não é gerado por IA, e a própria página da Steam diz isso no topo: "A HANDCRAFTED HORROR EXPERIENCE — handmade horror, with no shortcuts". Atrás da declaração há trabalho humano verificável: um desenvolvedor solo que construiu o jogo em público durante um ano, dez dublês nomeados no pôster oficial do elenco e sequências FMV feitas à mão, elogiadas pela crítica.',
    date: '2026-09-03',
    sections: [
      { title: 'O que o material oficial mostra', paragraphs: ['Cada linha é checável: a página da loja exibe a declaração handmade, o pôster do elenco nomeia os intérpretes, e a listagem carrega a linha de copyright da editora. Nada da produção do jogo depende de uma alegação que precise ser aceita na fé:'], bullets: ['Manchete da loja: "A HANDCRAFTED HORROR EXPERIENCE — handmade horror, with no shortcuts"', 'Desenvolvimento: desenvolvedora solo Tainted Pact (Estados Unidos)', 'Elenco de voz: 10 intérpretes nomeados no pôster oficial do elenco', 'Apresentação: sequências FMV estilo VHS, elogiadas pela cobertura de crítica', 'Editora na loja: Assemble Entertainment GmbH (linha de copyright)', 'Dados de lançamento na Steam: 16 conquistas; cerca de 90% positivas entre aproximadamente 340 análises'] },
      { title: 'A declaração oficial de handmade', paragraphs: ['A página da Steam abre com "handmade horror, with no shortcuts" como declaração de destaque na primeira tela. Frases de marketing não são prova por si, mas esta é incomumente específica para uma vitrine: compromete a desenvolvedora com assets artesanais e bate com a pegada de produção ao redor do jogo — uma pessoa desenvolvendo, um elenco de criadores e um ano de diários públicos de desenvolvimento.', 'O material de imprensa da editora repete a moldura artesanal em vez de contradizê-la, e nenhum canal oficial associado ao jogo anuncia arte gerada por IA, vozes de IA ou escrita por IA. Para um lançamento pequeno que se vende pela personalidade grindhouse, essa consistência entre canais é o sinal público mais forte disponível.'] },
      { title: 'Dez humanos nomeados fazem as vozes', paragraphs: ['O pôster oficial do elenco credita dez intérpretes: RJ Green como Dick Slater, Daniel Suraci como Robbie Knox, HexyIRL como Hexy e o assassino-título, Layna Lazar como a enfermeira Layna, Runebee como Bee, Luna Arcana como Luna, Blairvira como Blair, FeFe como Fefe, Scaroline como Scaroline e KingWoolz como DJ Woolz. Vários são criadores em atividade com catálogos públicos — o guia de dubladores mapeia cada crédito.', 'Isso importa para a questão da IA porque a dublagem é onde a suspeita costuma cair. The Skin Stapler é totalmente dublado em inglês — a Steam lista áudio completo em inglês —, e cada papel principal corresponde a um intérprete nomeado que divulga o trabalho nos próprios canais. O elenco de criadores ainda é estratégia de marketing deliberada: a editora nota que o jogo foi feito com apoio de criadores de conteúdo, o oposto de um pipeline anônimo e gerado.'] },
      { title: 'Um desenvolvedor, construindo em público', paragraphs: ['A Tainted Pact é um estúdio solo dos Estados Unidos, e o desenvolvimento aconteceu em público: o canal do YouTube publicou Dev Logs em dezembro de 2025, e a presença no itch.io documenta a trilha de projetos que levou a The Skin Stapler. Desenvolvimento solo não descarta ferramentas auxiliares, mas significa que cada asset passou por um autor responsável, cujos quatro jogos anteriores de horror — Suffer the Night, Terror at Oakheart, Massacre at the Mirage e Flesh Made Fear — mostram um estilo artesanal consistente evoluindo até este lançamento.', 'As sequências FMV tornam o caso artesanal visível. A crítica elogia o full-motion vídeo estilo VHS como destaque de apresentação; essas cenas são encenadas, interpretadas e montadas no registro grindhouse do jogo e carregam a mesma estética low-poly de era PSX do resto do build. O guia da desenvolvedora apresenta o estúdio e a editora em detalhe.'] },
      { title: 'Como checar o status de IA de qualquer jogo em três passos', paragraphs: [], bullets: ['Leia a lista de destaques da página da loja: a Steam exige divulgação de conteúdo de IA quando aplicável; a página de The Skin Stapler em vez disso estampa a produção handmade — as seções de divulgação são o sinal oficial mais rápido', 'Confira créditos e elenco: intérpretes nomeados, um pôster publicado e canais públicos de criadores — como o pôster de dez pessoas deste jogo — são impressões digitais humanas que conteúdo gerado não falsifica de forma convincente', 'Assista às imagens reais: consistência de estilo no catálogo de um desenvolvedor solo é difícil de fingir; compare as cenas FMV com os jogos anteriores e os dev logs do estúdio e a história da produção se conta sozinha'] },
      { title: 'Isso importa para como o jogo se joga?', paragraphs: ['Para The Skin Stapler, a questão do handmade é sobretudo uma questão de valores, e a resposta apoia o próprio pitch do jogo: a comédia grindhouse de uma desenvolvedora solo com elenco de criadores é exatamente o tipo de produção que os jogadores têm em mente quando pedem jogos feitos por humanos. O sentimento do lançamento na loja — cerca de 90% positivas entre aproximadamente 340 análises — sugere que o público leu da mesma forma.', 'Os limites honestos: listas de papéis nos créditos finais além do pôster nunca foram capturadas por completo, e nenhum documento oficial detalha cada ferramenta usada no desenvolvimento. O que o registro público sustenta é a própria declaração da loja — horror artesanal, sem atalhos — aplicada à arte, às vozes e à história do jogo. O guia da Steam cobre a listagem da loja se você quiser ler a declaração no lugar.'] }
    ],
    faq: [
      { question: 'The Skin Stapler usa arte gerada por IA?', answer: 'A página oficial da loja vende o jogo como horror handmade sem atalhos, e a arte low-poly e as cenas FMV batem com o catálogo artesanal de uma desenvolvedora solo. Nenhum canal oficial anuncia arte de IA para este título.' },
      { question: 'As vozes são de IA?', answer: 'Não. Dez intérpretes nomeados constam no pôster oficial do elenco, a Steam lista áudio completo em inglês, e os criadores divulgam os papéis nos próprios canais — o guia do elenco lista todos.' },
      { question: 'Quem fez The Skin Stapler?', answer: 'A desenvolvedora solo Tainted Pact, com publicação da Assemble Entertainment. O jogo estreou em 6 de agosto de 2026 para Windows PC.' },
      { question: 'Por que a página da loja diz "handmade horror"?', answer: 'É a declaração de produção da desenvolvedora — "A HANDCRAFTED HORROR EXPERIENCE — handmade horror, with no shortcuts" —, e bate com o histórico público de desenvolvimento e a abordagem de elenco criador.' },
      { question: 'O roteiro é gerado por IA?', answer: 'Os diálogos carregam as vozes dos intérpretes do pôster e o humor grindhouse da desenvolvedora em uma história de autor único; nenhuma fonte oficial descreve ferramentas de escrita por IA. O guia da história mostra o quanto o enredo é construído em torno de uma única revelação.' }
    ],
    sources: sourceSets['ai-generated']
  },
  developer: {
    id: 'developer', keyword: 'desenvolvedor de The Skin Stapler',
    title: 'The Skin Stapler: quem fez — Tainted Pact e Assemble Entertainment',
    description: 'The Skin Stapler é da Tainted Pact, desenvolvedora solo dos EUA, com publicação da Assemble Entertainment — quinto horror do estúdio, lançado a 14,99 euros.',
    eyebrow: 'Estúdio e publicação',
    directAnswer: 'The Skin Stapler foi feito pela Tainted Pact, desenvolvedora solo dos Estados Unidos, e publicado pela Assemble Entertainment, editora alemã por trás de Sticky Business, Roadwarden e da série Endzone. O jogo estreou em 6 de agosto de 2026 no Windows PC por 14,99 euros na Steam e é o quinto título de horror do estúdio.',
    date: '2026-09-03',
    sections: [
      { title: 'Estúdio e editora em resumo', paragraphs: ['O lado da editora é incomum de tão estabelecido para um projeto solo de horror: a Assemble Entertainment publicou mais de 50 jogos desde 2016, num catálogo que vai de sucessos aconchegantes como Sticky Business a RPGs narrativos como Roadwarden e à série de sobrevivência Endzone:'], bullets: ['Desenvolvedora: Tainted Pact — desenvolvedor solo, Estados Unidos (Califórnia)', 'Editora: Assemble Entertainment — Alemanha, mais de 50 jogos publicados', 'Lançamento: 6 de agosto de 2026, Windows PC', 'Preço de lançamento: 14,99 euros na Steam', 'Catálogo anterior: Suffer the Night, Terror at Oakheart, Massacre at the Mirage, Flesh Made Fear', 'Canais oficiais: itch.io (taintedpact88) e YouTube (@TaintedPactGames)'] },
      { title: 'Quem é a Tainted Pact?', paragraphs: ['A Tainted Pact é o estúdio solo por trás de cinco jogos de horror, e o anúncio de lançamento da editora descreve a desenvolvedora como uma operação de uma só pessoa na Califórnia. O estúdio constrói horror grindhouse deliberadamente nichado: durações curtas, visuais low-poly de era PSX, elencos dublados de criadores de conteúdo e roteiro de slasher movido a piadas.', 'A pegada pública do estúdio é pequena: uma conta no itch.io sob o nome taintedpact88 e um canal no YouTube, @TaintedPactGames, que publicou Dev Logs de The Skin Stapler em dezembro de 2025 — Dev Log #1 em 1º de dezembro e Dev Log #2 em 2 de dezembro —, documentando a construção em público antes do lançamento. O estúdio não publica nomes de fundadores nem detalhes pessoais; sua identidade pública é a marca, os jogos e as colaborações com criadores.'] },
      { title: 'Os quatro jogos anteriores a The Skin Stapler', paragraphs: ['O catálogo anterior é confirmado tanto pelo anúncio da editora quanto pelo catálogo do GOG:'], bullets: ['Suffer the Night — a estreia de analog horror do estúdio, construída em torno de um computador retrô assombrado', 'Terror at Oakheart — um slasher num acampamento, com a mesma violência estilizada', 'Massacre at the Mirage — um slasher confinado a um hotel, com ritmo cena a cena', 'Flesh Made Fear — o predecessor direto: história de serial killer com cenas dubladas e ponta grindhouse'] },
      { title: 'A editora: Assemble Entertainment', paragraphs: ['A Assemble Entertainment é uma editora alemã fundada em 2016, com mais de 50 jogos publicados. Seu alcance vai além do horror: Sticky Business é um hit aconchegante, Roadwarden é um RPG narrativo elogiado pela crítica, e a série Endzone ancora seu lado de estratégia de sobrevivência. The Skin Stapler fica no corredor grindhouse da editora, junto ao trabalho dela com projetos de horror curtos.', 'Para jogadores, a editora importa na prática: o esforço de imprensa do lançamento, a presença da Steam no evento Tiny Teams durante a janela da demo e a presença nas lojas Steam e GOG passam todos pela Assemble. A listagem da loja carrega a linha de copyright Assemble Entertainment GmbH, e o anúncio da editora é a fonte dos fatos de lançamento acima.'] },
      { title: 'O modelo de elenco criador', paragraphs: ['A editora descreve o jogo como construído com apoio de alguns dos seus criadores de conteúdo favoritos, e o pôster do elenco reforça com dez intérpretes nomeados: RJ Green, Daniel Suraci, HexyIRL, Layna Lazar, Runebee, Luna Arcana, Blairvira, FeFe, Scaroline e KingWoolz. Vários personagens são modelados e dublados pelos próprios criadores — Scaroline e o Underworld VHS são o exemplo mais claro.', 'Esse modelo é a assinatura do estúdio. Transforma um projeto solo em lançamento colaborativo, dá ao jogo um público embutido pelos canais dos criadores e mantém a apresentação totalmente dublada viável para um jogo de 2,5 horas. O guia de dubladores mapeia cada crédito de personagem para intérprete.'] },
      { title: 'Como acompanhar a desenvolvedora em três passos', paragraphs: [], bullets: ['Adicione à lista de desejos e siga na Steam: a página da desenvolvedora é o canal principal de patches e anúncios futuros, e a página de The Skin Stapler linka os outros trabalhos do estúdio', 'Confira o canal do YouTube: @TaintedPactGames é onde os Dev Logs aparecem — dois só em dezembro de 2025 — e é o lugar mais provável para anúncios de projetos futuros', 'Acompanhe a conta do itch.io: a página taintedpact88 hospeda a presença independente do estúdio e documenta a trilha de projetos que levou a The Skin Stapler'] }
    ],
    faq: [
      { question: 'Quem fez The Skin Stapler?', answer: 'A desenvolvedora solo Tainted Pact, dos Estados Unidos, com publicação da Assemble Entertainment, da Alemanha.' },
      { question: 'Que jogos a Tainted Pact já fez?', answer: 'Quatro títulos anteriores de horror — Suffer the Night, Terror at Oakheart, Massacre at the Mirage e Flesh Made Fear — mais The Skin Stapler como o quinto.' },
      { question: 'A Tainted Pact é uma pessoa só?', answer: 'Sim — o anúncio de lançamento da editora descreve um desenvolvedor solo, e o perfil artesanal de produção bate com um estúdio de uma pessoa trabalhando com um elenco de criadores.' },
      { question: 'Quem publica The Skin Stapler?', answer: 'A Assemble Entertainment, editora alemã fundada em 2016 com mais de 50 jogos, incluindo Sticky Business, Roadwarden e a série Endzone.' },
      { question: 'Onde posso acompanhar o estúdio?', answer: 'Listas de desejos na Steam, o canal @TaintedPactGames no YouTube e a página taintedpact88 no itch.io são os canais oficiais.' },
      { question: 'Quando o jogo saiu?', answer: 'Em 6 de agosto de 2026, na Steam e no GOG para Windows PC, por 14,99 euros — o guia de data de lançamento tem a linha do tempo completa, e o guia da Steam cobre a listagem da loja.' }
    ],
    sources: sourceSets.developer
  },
  'janker-edition': {
    id: 'janker-edition', keyword: 'The Skin Janker Edition',
    title: 'The Skin Janker Edition: o nome errado por trás do DLC real',
    description: 'Não existe "The Skin Janker Edition" — o nome mistura The Skin Jankers, o DLC de 3 skins. Veja a estrutura real de produtos na Steam e no GOG.',
    eyebrow: 'DLC e edições',
    directAnswer: 'Não existe produto chamado The Skin Janker Edition — o nome é uma leitura errada de The Skin Jankers, o DLC cosmético de The Skin Stapler. O produto real é The Skin Stapler: The Skin Jankers, um DLC lançado junto com o jogo em 6 de agosto de 2026 com três skins de super-heróis. Não há bundle de edição especial, versão de colecionador nem SKU com sufixo "Edition" do jogo base na Steam ou no GOG.',
    date: '2026-09-03',
    sections: [
      { title: 'A estrutura real de produtos', paragraphs: ['Três entradas na loja, nenhuma edição. Se você buscou por uma Janker Edition, a segunda linha da tabela é o produto que realmente quer — e as seções abaixo explicam exatamente o que ela contém:'], bullets: ['The Skin Stapler (jogo base): o jogo completo de 14 capítulos, App 4310610 — sem sufixo de edição; Steam e GOG', 'The Skin Jankers DLC: três skins cosméticas inspiradas em super-heróis, Steam App 4919860, lançado em 6 de agosto de 2026; DLC separado na Steam, incluído na compra do GOG', 'Soundtrack DLC: o áudio do jogo, Steam App 4919810, lançado em 6 de agosto de 2026; DLC separado na Steam'] },
      { title: 'O que o DLC Skin Jankers inclui', paragraphs: ['A descrição oficial do GOG é específica: o DLC Skin Jankers entrega três skins cosméticas gloriosamente ridículas inspiradas em super-heróis para os personagens principais do jogo. A redação entrega o tema (paródia de super-heróis), a contagem (três) e o alcance (só cosmético) — nada no DLC muda jogabilidade, capítulos ou história.', 'Os três designs individuais de skin não têm nome em nenhuma página de loja, então qualquer nome específico de skin citado por aí vai além da descrição oficial. Da mesma forma, o preço avulso do DLC na Steam não aparece no material que fundamenta este guia — confira a página própria do DLC pelo preço atual na sua região.'] },
      { title: 'Edition vs. DLC: por que a confusão acontece', paragraphs: ['A leitura errada segue um padrão previsível. Jogos de horror frequentemente vendem edições especiais, e "Jankers" no plural parece nome de edição numa barra de busca. Some o vocabulário do próprio jogo — a comunidade usa jank com carinho, e uma conquista da Steam se chama literalmente Jank Ya Later! — e uma fictícia Janker Edition soa plausível o bastante para os buscadores a sugerirem.', 'A estrutura da loja encerra a questão: uma edição real apareceria como SKU de bundle separado na Steam, e a loja de The Skin Stapler lista apenas o jogo base mais dois DLCs. O GOG vai um passo além e inclui o conteúdo Skin Jankers na compra base — o que um produto travado atrás de edição não faria.'] },
      { title: 'Como comprar a coisa certa em três passos', paragraphs: [], bullets: ['Decida primeiro a loja: o GOG inclui as três skins com o jogo base; a Steam vende o jogo base e o DLC Skin Jankers separados — se quer as skins na Steam, adicione o DLC explicitamente', 'Confira a página do DLC antes de fechar: The Skin Stapler: The Skin Jankers é o App 4919860 na Steam — confirme que o título bate exatamente, porque o DLC da trilha sonora (App 4919810) fica ao lado na loja', 'Ignore qualquer coisa rotulada como edição: não existe Janker Edition, Deluxe Edition nem Collector’s Edition deste jogo — loja ou site de chaves usando esses nomes está rotulando errado o jogo base ou revendendo o DLC sob um selo inventado'] },
      { title: 'O que as skins fazem no jogo', paragraphs: ['DLC cosmético num jogo de história de 2,5 horas faz exatamente o que diz: troca a aparência dos personagens principais enquanto cada fala, capítulo e conquista permanece idêntico. As 16 conquistas do jogo base, a história única e a estrutura de capítulos não são tocadas pela posse do DLC — o guia de conquistas lista o conjunto completo, e nenhum item exige as skins.', 'O tema de paródia de super-heróis combina com o registro de comédia grindhouse do jogo: o marketing da própria editora promete um último riso antes de morrer, e vestir o elenco da Carrion City de super-heróis gloriosamente ridículos é extensão da mesma piada, não um modo novo. O guia de análise cobre o quanto esse humor é central para o apelo do jogo.'] }
    ],
    faq: [
      { question: 'Existe uma The Skin Janker Edition do jogo?', answer: 'Não. O nome mistura The Skin Jankers — o DLC cosmético de três skins — com uma edição do jogo base. Nenhum SKU de edição existe na Steam ou no GOG.' },
      { question: 'O que é o DLC Skin Jankers?', answer: 'Três skins cosméticas inspiradas em super-heróis para os personagens principais, lançadas em 6 de agosto de 2026. Vende-se separado na Steam e vem incluído na versão do GOG.' },
      { question: 'Quanto custa o DLC?', answer: 'O preço avulso não consta do material que fundamenta este guia — confira a página do DLC na Steam pelo preço regional atual.' },
      { question: 'O DLC muda a história ou adiciona capítulos?', answer: 'Não. As skins são só cosméticas; a história de 14 capítulos e todas as 16 conquistas são idênticas com ou sem ele.' },
      { question: 'O DLC está no GOG?', answer: 'Sim — o GOG agrega as skins Skin Jankers à compra do jogo base, então compradores do GOG recebem as skins sem compra separada.' },
      { question: 'Qual é o outro DLC?', answer: 'A trilha sonora, lançada no mesmo dia do jogo e do pacote de skins. Contém a trilha synth que a crítica apontou como parte central da apresentação.' }
    ],
    sources: sourceSets['janker-edition']
  },
  'turkish-patch': {
    id: 'turkish-patch', keyword: 'The Skin Stapler em turco',
    title: 'The Skin Stapler em turco: sem patch oficial Türkçe',
    description: 'Steam e GOG listam só inglês — até setembro de 2026 não há patch Türkçe oficial nem anúncio de localização turca para The Skin Stapler.',
    eyebrow: 'Status de idioma',
    directAnswer: 'The Skin Stapler não tem opção de idioma turco. As páginas da Steam da versão completa (App 4310610) e da demo (App 4343530) listam inglês como único idioma — interface, legendas e dublagem —, e a oferta do GOG confirma: inglês na interface, nas legendas e no áudio. Como o jogo é totalmente dublado, uma versão turca exigiria regravar cada fala com um elenco de dublagem — e até setembro de 2026 nem a Tainted Pact nem a Assemble Entertainment anunciaram localização turca ou um Türkçe yama oficial.',
    date: '2026-09-03',
    sections: [
      { title: 'Status de idioma em resumo', paragraphs: ['Três listagens de loja, um idioma. Cada coluna vem direto das listas oficiais de idioma das lojas — a única fonte com autoridade sobre o que uma versão suporta:'], bullets: ['Steam — jogo completo (App 4310610): interface inglês, legendas inglês, áudio inglês; patch turco oficial: nenhum anunciado', 'Steam — demo (App 4343530): a mesma tabela em inglês da versão completa', 'GOG — jogo completo: o mesmo build só-em-inglês', 'Dica da demo: a demo espelha o jogo completo — nenhum download revela suporte turco escondido'] },
      { title: 'Por que não há patch turco oficial', paragraphs: ['The Skin Stapler é um jogo de horror FMV totalmente dublado. Cada fala é áudio gravado por dez dublês nomeados, então localizar não é trocar texto: uma versão turca exigiria legendas traduzidas e uma dublagem completa gravada para cada cena. É um pedido pesado para um desenvolvedor solo — The Skin Stapler é o quinto título de horror da Tainted Pact, construído em cerca de um ano e publicado pela Assemble Entertainment a 14,99 euros.', 'A combinação de duração curta, elenco totalmente dublado e produção de uma pessoa explica por que o lançamento veio só em inglês. Anúncios de localização para jogos desse tamanho, quando acontecem, costumam chegar depois do lançamento em notícias da página da loja ou patch notes. Tal anúncio para o turco não existe até setembro de 2026, e nada nas listagens das lojas sugere preparação.'] },
      { title: 'Patches turcos da comunidade', paragraphs: ['Este guia acompanha só canais oficiais e não linka downloads de terceiros. A existência de um Türkçe yama de fãs não é documentada em nenhum canal oficial: o jogo não tem página de workshop, sem suporte oficial de modding e sem endosso da desenvolvedora para arquivos de idioma de terceiros.', 'Se você procurar mesmo assim, pese os riscos de costume de patches não oficiais num jogo comprado em loja. Arquivos não oficiais podem quebrar em atualizações, não passam por triagem da Steam ou do GOG, e um arquivo ruim pode alcançar mais que a pasta do jogo. Isso não prova que um patch específico não funcione — mas cada link de download, post de fórum e descrição de vídeo merece desconfiança até você saber exatamente o que o arquivo modifica.'] },
      { title: 'Como verificar o suporte turco você mesmo', paragraphs: [], bullets: ['Abra a tabela de idiomas da Steam: role a página do jogo completo até a seção de idiomas e leia as colunas de interface, legendas e áudio para o turco; a página da demo (App 4343530) mostra a mesma tabela', 'Fique de olho no feed de notícias: anúncios de localização ou patch da Tainted Pact ou da Assemble Entertainment aparecem primeiro na área de notícias da Steam — é ali que um patch turco seria anunciado', 'Cruze com o GOG e a página da desenvolvedora: a listagem do GOG e a página do itch.io repetem o suporte oficial de idiomas — uma contradição entre as lojas apareceria ali'] },
      { title: 'Jogar em inglês enquanto espera', paragraphs: ['O inglês do jogo não é prosa densa — é diálogo grindhouse em cenas curtas, objetivos claros na tela e clipes FMV estilo VHS, e os quebra-cabeças reais (como o código 1979 do quadro de fotos) estão documentados no guia de soluções. Se inglês é sua segunda língua, a demo gratuita da Steam é o teste mais barato: ela embala três trechos jogáveis — delegacia, Quick Fix e Gutters End — em 30 a 45 minutos, para você avaliar a barreira do idioma antes dos 14,99 euros.', 'A única troca a saber de antemão: a história é entregue quase inteira por diálogos falados e sequências FMV, não por texto. Legendas existem, mas transcrevem as performances em inglês — não há interruptor de idioma por trás delas.'] }
    ],
    faq: [
      { question: 'Existe patch turco para The Skin Stapler?', answer: 'Nenhum oficial até setembro de 2026. Steam e GOG listam só inglês para o jogo completo e a demo, e nenhuma localização turca foi anunciada.' },
      { question: 'O turco chega depois?', answer: 'Nada foi anunciado. Se mudar, aparece primeiro no feed de notícias da Steam e nos canais da desenvolvedora — nunca em silêncio numa atualização aleatória.' },
      { question: 'A demo está em turco?', answer: 'Não. A demo (App 4343530) lista o mesmo idioma único do jogo completo: inglês em interface, legendas e áudio.' },
      { question: 'A versão do GOG tem legendas em turco?', answer: 'Não. O GOG distribui o mesmo build só-em-inglês da Steam, sem interruptores de idioma além do inglês.' },
      { question: 'Por que uma dublagem turca é tão improvável?', answer: 'O jogo é totalmente dublado. Uma dublagem significa regravar cada fala com um elenco turco — um compromisso muito maior que traduzir legendas, e nem legendas estão em discussão.' }
    ],
    sources: sourceSets['turkish-patch']
  },
  'korean-patch': {
    id: 'korean-patch', keyword: 'The Skin Stapler em coreano',
    title: 'The Skin Stapler em coreano: sem patch oficial ou tradução',
    description: 'Sem opção de coreano: Steam e GOG listam apenas inglês — até setembro de 2026 não há 패치 oficial nem 한국어 번역 anunciados para The Skin Stapler.',
    eyebrow: 'Status de idioma',
    directAnswer: 'The Skin Stapler não tem opção de idioma coreano. As listagens da Steam do jogo completo (App 4310610) e da demo (App 4343530) mostram inglês como único idioma suportado — interface, legendas e áudio —, e o build do GOG é o mesmo pacote de idioma único. Se você chegou de uma busca coreana por um The Skin Stapler 패치 ou uma 한국어 번역, essa é toda a resposta até setembro de 2026: não existe suporte coreano oficial, e nada foi anunciado.',
    date: '2026-09-03',
    sections: [
      { title: 'Status de idioma em resumo', paragraphs: ['Três listagens de loja, um idioma. Cada linha vem direto das tabelas oficiais de idioma das lojas — a única fonte com autoridade sobre o que uma versão suporta:'], bullets: ['Steam — jogo completo (App 4310610): interface inglês, legendas inglês, áudio inglês; patch coreano oficial: nenhum anunciado', 'Steam — demo (App 4343530): a mesma tabela em inglês da versão completa', 'GOG — jogo completo: o mesmo build só-em-inglês', 'Nota da demo: a demo espelha o jogo completo — o download gratuito não esconde suporte a coreano'] },
      { title: 'Por que não há patch coreano oficial', paragraphs: ['The Skin Stapler é um jogo de horror FMV totalmente dublado, com dez intérpretes nomeados no pôster do elenco. Uma versão coreana exigiria as duas coisas ao mesmo tempo: legendas traduzidas para cada fala e uma dublagem completa em coreano gravada sobre as sequências de vídeo estilo VHS. É uma carga de localização pesada para um desenvolvedor solo — a Tainted Pact construiu o jogo em cerca de um ano, e a editora Assemble Entertainment o lançou em 6 de agosto de 2026 por 14,99 euros com presença de loja só em inglês.', 'Horrors curtos e cheios de diálogo de equipes pequenas rotineiramente estreiam só em inglês, e o suporte coreano, quando vem, tipicamente aparece como anúncio pós-lançamento no feed de notícias da loja. Tal anúncio não existe para este jogo até setembro de 2026.'] },
      { title: 'Os termos de busca coreanos, explicados', paragraphs: ['Duas buscas coreanas dominam o tema. 패치 significa patch — quem procura um The Skin Stapler 패치 quer um patch de idioma ou uma tradução de fãs. 번역 significa tradução, geralmente combinado com 한국어 (coreano) para pedir uma versão localizada. Nenhuma das buscas traz resultado oficial porque nenhum dos dois produtos existe: as listagens das lojas são o registro com autoridade, e elas listam um idioma.', 'Cuidado com o que essas buscas trazem no resto: páginas de patch de fãs, builds reenviados e links em descrições de vídeo são arquivos de terceiros sem triagem da Steam ou do GOG. Este guia não linka nenhum deles.'] },
      { title: 'Patches coreanos da comunidade', paragraphs: ['Se uma tradução coreana de fãs existe, isso não é documentado em nenhum canal oficial — o jogo não tem suporte a workshop, não tem ferramentas oficiais de modding e não tem endosso da desenvolvedora para arquivos de idioma de terceiros. Quem avaliar um mesmo assim carrega os riscos de costume de patches não oficiais: podem quebrar em atualizações do jogo, mexer em arquivos bem além da pasta do jogo e colidir com termos de serviço que modificações não oficiais nem sempre respeitam.'] },
      { title: 'Como verificar o suporte coreano você mesmo', paragraphs: [], bullets: ['Leia a tabela de idiomas da Steam: na página do jogo completo (App 4310610), role até a lista de idiomas e confira a linha do coreano em interface, legendas e áudio; a página da demo mostra a mesma tabela', 'Observe o feed de notícias: notícias de localização aparecem primeiro na área de notícias da Steam, da Tainted Pact ou da Assemble Entertainment — é o canal a vigiar', 'Cruze com o GOG: a listagem do GOG espelha o suporte oficial de idiomas, e um anúncio futuro de coreano apareceria lá também'] },
      { title: 'Jogar em inglês enquanto espera', paragraphs: ['O inglês do jogo é diálogo grindhouse, não prosa densa: cenas curtas, falas diretas e objetivos claros na tela carregam a rota. Os quebra-cabeças reais — o código 1979 do quadro de fotos, a balança de carne da Flesh Pit, as fitas danificadas — estão documentados passo a passo e tiram dos capítulos de investigação a maior parte do risco do idioma.', 'Quem quiser testar a barreira do idioma de graça: a demo cobre em 30 a 45 minutos exatamente os formatos que você encontrará no jogo completo — diálogos de entrevista, trabalho de atendimento e uma perseguição roteirizada. A história em si vem por performances faladas em inglês e clipes FMV; legendas sozinhas não carregam uma jogada em outro idioma.'] }
    ],
    faq: [
      { question: 'Existe patch coreano para The Skin Stapler?', answer: 'Nenhum oficial até setembro de 2026. Steam e GOG listam só inglês, e nenhuma localização coreana foi anunciada.' },
      { question: 'Legendas em coreano chegam depois?', answer: 'Nada foi anunciado. Suporte futuro apareceria primeiro no feed de notícias da Steam e nos canais da desenvolvedora.' },
      { question: 'A demo está em coreano?', answer: 'Não. A demo (App 4343530) traz a mesma tabela só-em-inglês do jogo completo.' },
      { question: 'Steam e GOG diferem no idioma?', answer: 'Não. As duas lojas distribuem o mesmo build só-em-inglês para interface, legendas e áudio.' },
      { question: 'Por que uma dublagem coreana é improvável?', answer: 'O jogo é totalmente dublado com dez intérpretes. Uma dublagem significa regravar o jogo inteiro — um compromisso muito maior que traduzir legendas, e nem legendas foram anunciadas.' }
    ],
    sources: sourceSets['korean-patch']
  },
  'press-kit': {
    id: 'press-kit', keyword: 'The Skin Stapler press kit',
    title: 'The Skin Stapler press kit: assets oficiais e onde encontrá-los',
    description: 'Não há press kit oficial de The Skin Stapler — no lugar dele, release de lançamento, trailer e galerias das lojas. Todos os assets oficiais listados.',
    eyebrow: 'Imprensa e criadores',
    directAnswer: 'The Skin Stapler não tem press kit oficial. Até setembro de 2026, a Tainted Pact e a Assemble Entertainment não publicaram um ZIP de imprensa, um pacote de logos nem um portal de imprensa com login. O que existe é um conjunto de assets públicos e oficiais que cobre o que resenhistas, streamers e editores precisam na prática: o release de lançamento no Games Press, o trailer oficial de 27 de janeiro de 2026 e as galerias completas de capturas na Steam e no GOG.',
    date: '2026-09-03',
    sections: [
      { title: 'O que existe no lugar do press kit', paragraphs: ['Essa combinação é o press kit prático. Tudo na lista é oficial, acessível sem credenciais e seguro para citar ou incorporar — exatamente aquilo para o que um press kit existe:'], bullets: ['Release de lançamento: Games Press, manchete "The Skin Stapler Is Ready for Its Next Victim" (6 de agosto de 2026) — preço, fatos do estúdio, clima da demo, texto citável', 'Trailer oficial: YouTube, publicado em 27 de janeiro de 2026 (ID do vídeo 5tEJiy8FJbY) — incorporável no original', 'Galeria da Steam: página da loja (App 4310610) — capturas de tela, capa, descrição da loja', 'Galeria do GOG: as mesmas capturas e o mesmo texto de loja', 'Loja da desenvolvedora: a página do jogo no itch.io'] },
      { title: 'O que o release de lançamento confirma', paragraphs: ['O release de 6 de agosto de 2026 no Games Press é o documento mais útil do conjunto, porque trava em um texto os fatos que a maioria das coberturas precisa: 14,99 euros no PC; desenvolvido pelo solo Tainted Pact, publicado pela Assemble Entertainment sob o selo Tiny Teams operado pela Yogscast; The Skin Stapler como quinto título de horror do estúdio; a demo gratuita da Steam com nota Very Positive no lançamento; CaseOh e MoistCr1TiKaL jogando o jogo antes do lançamento.', 'As duas descrições oficiais do jogo vêm do mesmo release. A logline: "Enter Carrion City and hunt a serial killer through a short, story-driven horror nightmare". A tagline: "NO ONE LEAVES CARRION CITY IN ONE PIECE." Quem escreve sobre o jogo recorre com segurança a essas duas linhas, porque vêm do texto da própria editora em vez de um parafraseio — e o release as acompanha dos números concretos acima, então uma notícia curta e uma análise longa têm o que precisam.'] },
      { title: 'Por que um jogo pequeno dispensa o press kit', paragraphs: ['Nada está faltando aqui — é assim que horror de equipe pequena normalmente chega ao mercado. Um desenvolvedor solo não mantém portal de imprensa, e o release de lançamento da editora faz o mesmo trabalho: fatos, citações e posicionamento vão às redações numa passada só. As galerias das lojas servem então como o lar permanente e sempre atual dos assets visuais — o que um ZIP estático jamais é.', 'Do lado dos criadores vale o mesmo. As jogadas do CaseOh e do MoistCr1TiKaL citadas no release são vídeos públicos, e a nota Very Positive da demo é visível para qualquer um na página da loja — dois sinais de reputação que se podem citar sem qualquer acesso de imprensa.'] },
      { title: 'Como reunir os assets em três passos', paragraphs: [], bullets: ['Puxe primeiro as galerias das lojas: a página da Steam (App 4310610) guarda o conjunto atual de capturas e a capa; a listagem do GOG repete o mesmo material e te dá uma segunda fonte oficial', 'Incorpore o trailer original: o trailer do YouTube publicado em 27 de janeiro de 2026 (ID 5tEJiy8FJbY) é o oficial — incorpore o upload original, nunca um reenvio, para que créditos e visualizações fiquem com a editora', 'Cite o release para os fatos: o release do Games Press entrega preço, créditos da equipe, nota da demo e as duas taglines oficiais sem nenhum parafraseio no meio'] },
      { title: 'Contatos de imprensa sem portal', paragraphs: ['Não existe contato de imprensa publicado para o jogo em si. A Assemble Entertainment é a editora de registro — o site da editora é o caminho sensato para perguntas de imprensa. Para tudo que é visível, o conjunto público basta: galeria, trailer e release. Um sistema separado de credenciais não existe e não é exigido; os assets listados cobrem por completo análises, notícias e preparação de stream.'] }
    ],
    faq: [
      { question: 'Existe um press kit oficial de The Skin Stapler?', answer: 'Não. Até setembro de 2026 nenhum ZIP de imprensa, pacote de logos ou portal de imprensa foi publicado para o jogo.' },
      { question: 'Onde consigo capturas de tela oficiais?', answer: 'Nas galerias das lojas Steam e GOG. Elas carregam as mesmas capturas oficiais que a editora usa para vender o jogo e ficam sempre atualizadas.' },
      { question: 'Quem contato para acesso de imprensa?', answer: 'Nenhum contato de imprensa está publicado para o jogo. A Assemble Entertainment é a editora de registro — o site da editora é o caminho certo para perguntas de imprensa.' },
      { question: 'Posso usar o trailer na minha cobertura?', answer: 'Sim. O trailer oficial (ID do YouTube 5tEJiy8FJbY) é público e feito para compartilhar — incorpore o upload original, não um reenvio.' },
      { question: 'Quais são as taglines oficiais do jogo?', answer: 'A logline é "Enter Carrion City and hunt a serial killer through a short, story-driven horror nightmare", e a tagline é "NO ONE LEAVES CARRION CITY IN ONE PIECE." Ambas vêm do release de lançamento.' }
    ],
    sources: sourceSets['press-kit']
  },
  'final-aftermath': {
    id: 'final-aftermath', keyword: 'The Skin Stapler Final Aftermath',
    title: 'The Skin Stapler Final Aftermath: posição, conquista e final',
    description: 'O Final Aftermath explicado: o quinto interlúdio Aftermath entre Lazar’s Blood Bank e Closing In, com a conquista "Nine, Ten, Never Jank Again.".',
    eyebrow: 'Guia de capítulos',
    directAnswer: 'The Final Aftermath é o quinto e último interlúdio Aftermath de The Skin Stapler — o capítulo que fecha as histórias das vítimas antes do trecho final em duas partes. Na rota, fica depois de Lazar’s Blood Bank, que termina em 01:58:34 numa run de referência, e antes de Closing In, que abre às 02:18:29. Completá-lo desbloqueia a conquista "Nine, Ten, Never Jank Again." e fecha a conta dos 14 capítulos: nove capítulos de locações, quatro partes de Aftermath e o próprio Final Aftermath.',
    date: '2026-09-03',
    sections: [
      { title: 'Posição na rota', paragraphs: ['Esses marcos vêm da lista oficial de conquistas e dos horários de uma run de referência — eles localizam o capítulo com exatidão, mesmo sem documento granular de level design:'], bullets: ['Nome do capítulo: The Final Aftermath', 'Posição: depois de Lazar’s Blood Bank (01:58:34 na run de referência), antes de Closing In (02:18:29)', 'Conquista: "Nine, Ten, Never Jank Again." — Complete The Final Aftermath Chapter', 'Conta dos capítulos: 9 capítulos de locações + 4 partes de Aftermath + o Final Aftermath = 14 capítulos', 'O que vem depois: Closing In (02:18:29), então o final na Flesh Pit (02:34:00)'] },
      { title: 'Por que a posição importa exatamente', paragraphs: ['Quem segue a rota pelo relógio precisa dessa localização: Lazar’s Blood Bank — o capítulo da Layna e o último das locações de vítimas — termina perto do minuto 01:58 de uma run completa de referência. O Final Aftermath vem em seguida, e Closing In abre às 02:18:29. Sobram para o interlúdio cerca de vinte minutos na linha do tempo, dentro de uma run que termina na Flesh Pit por volta de 02:34 e se acomoda na duração oficial de aproximadamente duas horas e meia.', 'A Steam confirma a mesma ordem pelo outro lado: a lista de conquistas enumera os interlúdios em sequência, e o último item, "Nine, Ten, Never Jank Again.", senta exatamente no Final Aftermath. Ler a lista de conquistas de cima a baixo é ler a ordem da rota.'] },
      { title: 'A conquista por trás do capítulo', paragraphs: ['A conquista da Steam se lê "Nine, Ten, Never Jank Again." com o requisito "Complete The Final Aftermath Chapter." Não há condição escondida nem elemento perdível: a conquista cai quando o capítulo termina. O nome é a resolução de uma cantiga de contagem que o jogo estende pelas conquistas dos interlúdios — Aftermath Part 3 carrega "Five, six, grab your crucifix...", e a sequência aterrissa aqui no "nine, ten", no interlúdio final.', 'Para uma lista de conquistas limpa, este item é impossível de perder contanto que você termine a rota. O desbloqueio genuinamente perdível do jogo é o bilhete de agradecimento no escritório — item próprio, coberto em separado no guia de conquistas.'] },
      { title: 'O que acontece no Final Aftermath', paragraphs: ['Os capítulos Aftermath existem para devolver a história de cada vítima ao dossiê de Dick Slater. Os capítulos de vítimas são turnos comuns de trabalho — servir cachorro-quente, rechear donuts, rebobinar fitas — que terminam nas mãos do assassino; as partes Aftermath reenquadram essas mortes como evidências, conexões e uma contagem que só sobe. O Final Aftermath fecha esse fio: a última história de vítima entra na investigação, e o caso fica completo o bastante para Slater partir para cima do assassino.', 'Como o capítulo se parece momento a momento — interlúdio estilo cutscene ou trecho com interações próprias — é um detalhe para verificar no jogo. O material oficial registra o nome do capítulo, a posição na ordem de progressão e a conquista, e nada mais granular que isso.'] },
      { title: 'Como ele prepara o trecho final', paragraphs: ['Depois do Final Aftermath restam dois capítulos, e ambos são investigação. Closing In, abrindo às 02:18:29 na run de referência, converge o caso sobre um suspeito. A Flesh Pit — o restaurante de barbecue de Elias Crow e a resposta à pergunta do título — recebe o final às 02:34:00. A partir do Final Aftermath não existem mais capítulos de vítimas nem turnos para trabalhar: os últimos vinte minutos são a história fechando as mandíbulas. O que acontece no final é coberto pela página de final explicado; a identidade e o motivo do assassino ficam no guia de quem é o Skin Stapler, para o momento em que você tiver visto.'] }
    ],
    faq: [
      { question: 'O que é o Final Aftermath em The Skin Stapler?', answer: 'O quinto e último interlúdio Aftermath — o capítulo que fecha o fio das vítimas antes do trecho final em duas partes, Closing In e Flesh Pit.' },
      { question: 'Que conquista ele desbloqueia?', answer: '"Nine, Ten, Never Jank Again.", por completar The Final Aftermath Chapter; ela cai automaticamente no fim do capítulo.' },
      { question: 'O Final Aftermath é um capítulo jogável?', answer: 'O formato exato — interlúdio estilo cutscene ou seção interativa — não é documentado em separado. Oficialmente conta como um dos 14 capítulos e fica na rota entre Lazar’s Blood Bank e Closing In.' },
      { question: 'Em que ponto do jogo ele acontece?', answer: 'Perto da marca de duas horas: Lazar’s Blood Bank termina perto de 01:58:34 na run de referência, e Closing In abre às 02:18:29 — o interlúdio fica entre eles.' },
      { question: 'O jogo termina depois do Final Aftermath?', answer: 'Não. Closing In e o final na Flesh Pit ainda vêm — o interlúdio fecha as histórias das vítimas, e os dois últimos capítulos entregam o desfecho.' }
    ],
    sources: sourceSets['final-aftermath']
  },
  'aftermath-3': {
    id: 'aftermath-3', keyword: 'The Skin Stapler Aftermath 3',
    title: 'The Skin Stapler Aftermath 3: posição, conquista e função',
    description: 'Aftermath Part 3 explicado: o terceiro interlúdio entre a donut shop da Luna e o Underworld VHS, com a conquista "Five, six, grab your crucifix...".',
    eyebrow: 'Guia de capítulos',
    directAnswer: 'Aftermath 3 — na Steam, The Aftermath Part 3 — é o terceiro dos quatro interlúdios Aftermath de The Skin Stapler e fica no meio da passagem das vítimas para a investigação: depois de Luna’s Cream Filled Donuts, que termina perto de 01:15:37 numa run de referência, e antes de Underworld VHS, que abre às 01:34:10. Completá-lo desbloqueia a conquista "Five, six, grab your crucifix...", a terceira linha da cantiga de contagem espalhada pelas conquistas dos interlúdios.',
    date: '2026-09-03',
    sections: [
      { title: 'Posição na rota', paragraphs: ['Os dois horários emolduram o interlúdio com precisão — tudo entre eles é o interlúdio mais o começo do capítulo seguinte, dentro de uma rota completa de aproximadamente duas horas e meia:'], bullets: ['Nome do capítulo: The Aftermath Part 3', 'Posição: depois de Luna’s Cream Filled Donuts (01:15:37), antes de Underworld VHS (01:34:10)', 'Conquista: "Five, six, grab your crucifix..." — Complete The Aftermath Part 3 Chapter', 'Função: devolve as histórias das vítimas à investigação de Dick Slater', 'Janela de tempo: o trecho 01:15–01:34 de uma run de referência'] },
      { title: 'O que o capítulo faz pela história', paragraphs: ['A fórmula Aftermath é o tecido conjuntivo da estrutura do jogo. Cada capítulo de vítima termina do mesmo jeito — um turno comum que desaba nas mãos do assassino —, e cada parte Aftermath puxa essa morte de volta ao dossiê de Slater: os quadros de evidências crescem, as conexões se multiplicam, a contagem sobe. A Part 3 é onde o ritmo da segunda metade se firma. Ela segue o capítulo da Luna na ordem de progressão, e a cena da Luna carrega o fio da VHS que o próximo capítulo de locação puxa: Underworld VHS é a loja de Scaroline, e a ligação entre a donut shop e a locadora está documentada no guia de quem é o Skin Stapler.', 'O conteúdo cena a cena do capítulo — quais vítimas ele toca e como o dossiê as enquadra — não é documentado em separado no material oficial. O que o registro oficial fixa são o nome do capítulo, a posição na ordem de progressão e a conquista, e esses três fatos bastam para localizá-lo com exatidão.'] },
      { title: 'O padrão da cantiga nas conquistas', paragraphs: ['A posição explica também a rima. Os interlúdios carregam as conquistas de contagem do jogo em sequência — a "Five, six, grab your crucifix..." da Part 3 é a terceira linha, e o conjunto se resolve com "Nine, Ten, Never Jank Again." no Final Aftermath. Ler a lista de conquistas de cima a baixo é ler a própria ordem dos interlúdios; é assim que a posição na rota acima fica fixada: a ordem de conquistas da Steam põe The Aftermath Part 3 diretamente entre o desbloqueio do capítulo da Luna e o trecho de Underworld VHS.'] },
      { title: 'Como chegar ao Aftermath 3', paragraphs: [], bullets: ['Complete Luna’s Cream Filled Donuts: trabalhe o turno de atendimento até o fim — o capítulo em que Luna e o chefe O’Brien encontram o destino —, e a história passa ao interlúdio automaticamente', 'Deixe o interlúdio rolar: a conquista "Five, six, grab your crucifix..." cai quando o capítulo termina; não há escolha, condição escondida nem colecionável ligado ao desbloqueio', 'Siga para Underworld VHS: o próximo capítulo de locação abre às 01:34:10 na run de referência — a locadora de Scaroline, um capítulo de aproximadamente 24 minutos pela linha do tempo da rota'] },
      { title: 'Contexto no percurso total', paragraphs: ['Saber o que cerca o interlúdio ajuda a situá-lo no mapa: antes dele, a rota já jogou cinco capítulos de locações, com Luna’s Cream Filled Donuts como o quinto; depois da locadora, resta apenas a Lazar’s Blood Bank antes dos capítulos finais assumirem. Aftermath Part 3 é a dobradiça entre o acorde final da donut shop e o capítulo da locadora que recolhe o fio da VHS plantado pela cena da Luna — o momento em que o jogo para de apresentar vítimas e começa a fechar o caso.'] }
    ],
    faq: [
      { question: 'O que é o Aftermath 3 em The Skin Stapler?', answer: 'O terceiro dos quatro interlúdios Aftermath — o capítulo que carrega as histórias das vítimas de volta à investigação de Slater entre a donut shop da Luna e a locadora Underworld VHS.' },
      { question: 'Que conquista ele desbloqueia?', answer: '"Five, six, grab your crucifix...", por completar The Aftermath Part 3 Chapter — a terceira linha da cantiga de contagem das conquistas dos interlúdios.' },
      { question: 'Onde o Aftermath 3 cai na rota?', answer: 'Entre Luna’s Cream Filled Donuts (fim perto de 01:15:37) e Underworld VHS (abertura às 01:34:10) na ordem de progressão.' },
      { question: 'O Aftermath 3 é jogável?', answer: 'O grau exato de interação dos interlúdios não é documentado em separado. Oficialmente é um dos 14 capítulos, e a conquista cai ao completá-lo, independentemente do formato.' },
      { question: 'Quantos capítulos Aftermath existem?', answer: 'Quatro partes numeradas mais o Final Aftermath — cinco interlúdios dentro do total de 14 capítulos, cada um com conquista própria de conclusão.' }
    ],
    sources: sourceSets['aftermath-3']
  }
};
