import type { BatchThreeArticleId, LocalizedArticle } from './types';

const sourceSets: Record<BatchThreeArticleId, Array<{ label: string; url: string }>> = {
  review: [
    { label: 'Bloody Disgusting — veröffentlichter Test zu The Skin Stapler', url: 'https://bloody-disgusting.com/video-games/3962809/the-skin-stapler-review-psx-horror-throwback-favors-humor-over-gameplay/' },
    { label: 'Steam — offizielle Vollversion', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'Steam — offizielle Demo', url: 'https://store.steampowered.com/app/4343530/The_Skin_Stapler_Demo/' }
  ],
  story: [
    { label: 'Steam — offizielle Vollversion', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'CaseOh — kompletter Spieldurchlauf', url: 'https://www.youtube.com/watch?v=EcgnRprUU5k' },
    { label: 'GabeHype — 100%-Durchlauf', url: 'https://www.youtube.com/watch?v=1kEFUOGxgjE' },
    { label: 'Steam Community — offizielle Erfolgsliste', url: 'https://steamcommunity.com/stats/4310610/achievements' }
  ],
  'games-like': [
    { label: 'Bloody Disgusting — veröffentlichter Test mit Vergleichstiteln', url: 'https://bloody-disgusting.com/video-games/3962809/the-skin-stapler-review-psx-horror-throwback-favors-humor-over-gameplay/' },
    { label: 'Steam — offizielle Vollversion', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'GOG — offizielle Storeseite', url: 'https://www.gog.com/en/game/the_skin_stapler' },
    { label: 'Tainted Pact — offizielle itch.io-Seite', url: 'https://taintedpact88.itch.io/the-skin-stapler' }
  ],
  uncensored: [
    { label: 'Steam — offizielle Vollversion', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'GOG — offizielle Storeseite', url: 'https://www.gog.com/en/game/the_skin_stapler' },
    { label: 'Steam — offizielle Demo', url: 'https://store.steampowered.com/app/4343530/The_Skin_Stapler_Demo/' }
  ],
  'donut-shop': [
    { label: 'Steam Community — offizielle Erfolgsliste', url: 'https://steamcommunity.com/stats/4310610/achievements' },
    { label: 'GabeHype — 100%-Durchlauf', url: 'https://www.youtube.com/watch?v=1kEFUOGxgjE' },
    { label: 'Steam — offizielle Vollversion', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' }
  ],
  'all-tapes': [
    { label: 'Steam — offizielle Vollversion', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'Steam Community — offizielle Erfolgsliste', url: 'https://steamcommunity.com/stats/4310610/achievements' },
    { label: 'CaseOh — kompletter Spieldurchlauf', url: 'https://www.youtube.com/watch?v=EcgnRprUU5k' }
  ],
  'ai-generated': [
    { label: 'Steam — offizielle Vollversion mit Handmade-Aussage', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'Tainted Pact — offizielle itch.io-Seite', url: 'https://taintedpact88.itch.io/the-skin-stapler' },
    { label: 'Tainted Pact — offizieller YouTube-Kanal', url: 'https://www.youtube.com/@TaintedPactGames' }
  ],
  developer: [
    { label: 'Tainted Pact — offizielle itch.io-Seite', url: 'https://taintedpact88.itch.io/the-skin-stapler' },
    { label: 'Tainted Pact — offizieller YouTube-Kanal', url: 'https://www.youtube.com/@TaintedPactGames' },
    { label: 'Steam — offizielle Vollversion', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'GOG — offizielle Storeseite', url: 'https://www.gog.com/en/game/the_skin_stapler' }
  ],
  'janker-edition': [
    { label: 'Steam — The Skin Jankers DLC (App 4919860)', url: 'https://store.steampowered.com/app/4919860/' },
    { label: 'Steam — Soundtrack-DLC (App 4919810)', url: 'https://store.steampowered.com/app/4919810/' },
    { label: 'GOG — Storeseite mit Skin-Jankers-Bündel', url: 'https://www.gog.com/en/game/the_skin_stapler' }
  ],
  'turkish-patch': [
    { label: 'Steam — Sprachtabelle der Vollversion', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'Steam — Sprachtabelle der Demo', url: 'https://store.steampowered.com/app/4343530/The_Skin_Stapler_Demo/' },
    { label: 'GOG — offizielle Storeseite', url: 'https://www.gog.com/en/game/the_skin_stapler' }
  ],
  'korean-patch': [
    { label: 'Steam — Sprachtabelle der Vollversion', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'Steam — Sprachtabelle der Demo', url: 'https://store.steampowered.com/app/4343530/The_Skin_Stapler_Demo/' },
    { label: 'GOG — offizielle Storeseite', url: 'https://www.gog.com/en/game/the_skin_stapler' }
  ],
  'press-kit': [
    { label: 'Steam — offizielle Screenshot-Galerie', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' },
    { label: 'YouTube — offizieller Trailer (5tEJiy8FJbY, 27. Januar 2026)', url: 'https://www.youtube.com/watch?v=5tEJiy8FJbY' },
    { label: 'GOG — offizielle Galerie', url: 'https://www.gog.com/en/game/the_skin_stapler' }
  ],
  'final-aftermath': [
    { label: 'Steam Community — offizielle Erfolgsliste', url: 'https://steamcommunity.com/stats/4310610/achievements' },
    { label: 'GabeHype — 100%-Durchlauf', url: 'https://www.youtube.com/watch?v=1kEFUOGxgjE' },
    { label: 'Steam — offizielle Vollversion', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' }
  ],
  'aftermath-3': [
    { label: 'Steam Community — offizielle Erfolgsliste', url: 'https://steamcommunity.com/stats/4310610/achievements' },
    { label: 'GabeHype — 100%-Durchlauf', url: 'https://www.youtube.com/watch?v=1kEFUOGxgjE' },
    { label: 'Steam — offizielle Vollversion', url: 'https://store.steampowered.com/app/4310610/The_Skin_Stapler/' }
  ]
};

export const batchThreeDe: Record<BatchThreeArticleId, LocalizedArticle> = {
  review: {
    id: 'review', keyword: 'The Skin Stapler Test',
    title: 'The Skin Stapler Test: Urteil, Stärken und Schwächen',
    description: 'Der Test zu The Skin Stapler: 2,5 Stunden Grindhouse-Horror, starke Opferkapitel, dünne Mechanik — und für wen sich der Kauf bei 14,99 Euro lohnt.',
    eyebrow: 'Test und Kaufentscheidung',
    directAnswer: 'The Skin Stapler ist ein 2,5-stündiger Grindhouse-Horror mit 14 kurzen Kapiteln, dessen Stärke in den gespannten Opferkapiteln liegt und dessen Schwäche die leichte Mechanik ist. Bloody Disgusting empfiehlt ihn Fans von Sniper Killer und Rewind or Die klar und allen anderen eher nicht. Die Steam-Bewertungen lagen zum Start bei etwa 90 % Positiv aus rund 340 Rezensionen.',
    date: '2026-09-03',
    sections: [
      { title: 'Das Urteil auf einen Blick', paragraphs: ['Der veröffentlichte Test von Bloody Disgusting prüft die Vollversion und fasst das Spiel als kurzen, bewusst groben Grindhouse-Titel zusammen. Diese Punkte sind für deine Kaufentscheidung die wichtigsten:'], bullets: ['Länge: etwa 2,5 Stunden über 14 kurze Kapitel', 'Struktur: Kapitel wechseln zwischen Ermittlungs- und Mordzug-Perspektive', 'Stärkster Moment: die Opferkapitel, besonders die Fefe-Eröffnung', 'Schwächster Punkt: dünne, stellenweise wiederholte Mechanik', 'Präsentation: VHS-FMV-Sequenzen und das Carrion City von 1984 überzeugen', 'Wertung: Schädel-Skala statt Zahl — Sniper-Killer- und Rewind-or-Die-Fans rechnen einen Schädel drauf, alle anderen einen ab', 'Steam-Stimmung: rund 90 % Positiv aus etwa 340 Rezensionen im Startfenster'] },
      { title: 'Was für ein Spiel wird getestet?', paragraphs: ['The Skin Stapler ist ein kurzes, storygetriebenes Horrorspiel im Carrion City des Jahres 1984, einer Stadt voller absurder Sonderlinge. Du spielst abwechselnd den ausgebrannten Detective Dick Slater bei der Ermittlung und die Verfolgerperspektive in den Mordzug-Kapiteln. Der eigene Verlagspitch — einen Serienkiller durch einen kurzen, storygetriebenen Horror-Albtraum jagen — bildet den Rahmen.', 'Vierzehn kurze Kapitel füllen die 2,5 Stunden. Neun sind spielbare Schauplatz-Kapitel wie die Burrows Apartments, der Quick Fix und Lazar’s Blood Bank, der Rest sind Aftermath-Zwischenspiele, die jede Opfergeschichte zurück in Slaters Akte holen.'] },
      { title: 'Das lobt der Test', paragraphs: ['Die Opferkapitel sind der Höhepunkt. Der Tester nennt die Fefe-Eröffnung im Apartment das am deutlichsten angespannte Kapitel des Spiels, und die übrigen Arbeitsschichten halten dieses Niveau: gewöhnliche Schichten — Hotdogs servieren, Donuts befüllen, Kassetten zurückspulen — während eine maskierte Gestalt näherkommt. Diese dramatische Ironie ist der beste Trick des Designs.', 'Die Präsentation bekommt die zweite Runde Lob: die VHS-artigen FMV-Sequenzen, der synthlastige Retro-Soundtrack und die vollständig gesprochene Besetzung geben dem Spiel seine Grindhouse-Identität. Auch das Schreiben überzeugt — Carrion City ist absichtlich voller grotesker Sonderlinge, und laut Verlags-Tagline kommt vor dem Tod noch ein letzter Lacher.'] },
      { title: 'Das kritisiert der Test', paragraphs: ['Beide Spielweisen bleiben mechanisch dünn. Die Ermittlungskapitel reduzieren sich auf kurze Areale und Aufgaben, die Mordzug-Kapitel setzen auf kurze Interaktionsschleifen. Die Formulierung des Testers: die Mechanik wirkt ein wenig wiederholt — über 14 Kapitel wächst der Interaktionswortschatz kaum.', 'Genau deshalb landet das Urteil beim Geschmacksthema statt bei einer Allround-Empfehlung. Der Test behandelt die dünne Mechanik als Preis für Humor und Tempo, behauptet aber nicht, die Systeme seien tief.'] },
      { title: 'Die Score-Frage', paragraphs: ['Bloody Disgusting bewertet in Schädeln statt Zahlen, und das Urteil zu The Skin Stapler ist ein Witz mit Nutzwert: Fans von Sniper Killer oder Rewind or Die dürfen einen Schädel draufrechnen, alle anderen einen abziehen. Eine numerische Wertung existiert nicht — Wertungen anderer Seiten solltest du direkt auf deren Seite gegenprüfen.', 'Praktisch übersetzt: für die Zielgruppe liest sich der Test als klare Empfehlung, außerhalb als Vorbeigang. Der Tester erhält laut eigener Offenlegung einen vom Publisher gestellten Zugangscode — übliche Praxis, offengelegt im Test selbst.'] },
      { title: 'Was die Spielerzahlen hinzufügen', paragraphs: ['Das Startpublikum bestätigte den Ton des Spiels. CaseOhs kompletter Durchlauf erreichte 2.102.706 Aufrufe nach dem 9. August 2026, und Joe Bartolozzis Video passierte in der Folgewoche 1,37 Millionen Aufrufe — der Clip-Humor trägt weit über die 2,5 Stunden hinaus. Steam meldete im Startfenster nahezu 90 % positive Rezensionen aus etwa 340 Stimmen.', 'Zahlen beantworten die Geschmacksfrage nicht — eine Million Aufrufe einer Hotdog-Szene sind kein Test —, aber sie zeigen, welche Momente das Publikum trifft.'] },
      { title: 'So entscheidest du in drei Schritten', paragraphs: [], bullets: ['Spiel zuerst die kostenlose Demo: drei Abschnitte — Polizeiwache, Quick Fix und Gutters End — zeigen dir Ton und Tempo in 30–45 Minuten', 'Schau ein Opferkapitel: wenige Minuten einer Arbeitsschicht klären, ob Spannung plus Comedy für dich funktioniert; die CaseOh- und Joe-Bart-Videos sind die schnellste Probe ohne Finale-Spoiler', 'Kauf für die Story, nicht fürs System: bei 2,5 Stunden und 14,99 Euro auf Steam ist der Wert eine Grindhouse-Geschichte in einer Sitzung mit voller Vertonung — mit diesem Rahmen verlieren die Kritikpunkte an Gewicht'] }
    ],
    faq: [
      { question: 'Wie lange dauert The Skin Stapler?', answer: 'Etwa 2,5 Stunden für die 14-Kapitel-Hauptstrecke; aufgezeichnete Durchläufe mit Erkundung landen zwischen rund 2:46 und 3 Stunden.' },
      { question: 'Ist The Skin Stapler gruselig oder lustig?', answer: 'Beides, by Design. Die Opferkapitel spielen Spannung, während Dialoge, FMV-Einlagen und groteske Nebenfiguren die Lacher liefern — der Test nennt die Mischung gruselig und komisch zugleich.' },
      { question: 'Haben Tester ein kostenloses Exemplar bekommen?', answer: 'Ja. Bloody Disgusting legt offen, dass der Testcode vom Publisher gestellt wurde — übliche Praxis, die im Test selbst steht.' },
      { question: 'Gibt es eine numerische Wertung?', answer: 'Nein. Die Seite bewertet in Schädeln: für Sniper-Killer- und Rewind-or-Die-Fans einen höher, für alle anderen einen niedriger.' },
      { question: 'Was sagen Spieler im Vergleich zu Kritikern?', answer: 'Dieselbe Spaltung: rund 90 % positive Steam-Rezensionen im Startfenster, häufigste Kritik wie im Test — leichte Mechanik und kurze Spieldauer.' }
    ],
    sources: sourceSets.review
  },
  story: {
    id: 'story', keyword: 'The Skin Stapler Story',
    title: 'The Skin Stapler Story: Handlung und Ende erklärt',
    description: 'Die Story von The Skin Stapler: Dick Slater jagt 1984 den Skin Stapler durch Carrion City — Motiv, Identität, Kassetten und das eine Ende im Flesh Pit.',
    eyebrow: 'Handlung mit Spoilern',
    directAnswer: '1984 jagt Detective Dick Slater einen Serienkiller durch Carrion City, während das Spiel zwischen den Opfern und dem Killer selbst wechselt. Der Killer ist Elias Crow, Besitzer des Flesh-Pit-Grillrestaurants, und sein Motiv ist Rache: Slater erschoss seinen Zwillingsbruder Silus Kain. Die Geschichte läuft etwa 2,5 bis 4 Stunden über 14 kurze Kapitel und hat genau ein Ende.',
    date: '2026-09-03',
    sections: [
      { title: 'Die Story auf einen Blick', paragraphs: ['Diese Fakten bilden das Gerüst der Handlung — die Abschnitte unten bauen sie im Detail aus:'], bullets: ['Schauplatz: Carrion City, 1984', 'Ermittler: Detective Dick Slater, mit Rookie Robbie Knox', 'Killer: Elias Crow, Besitzer des Flesh-Pit-Grillrestaurants', 'Motiv: Rache für den Zwillingsbruder Silus Kain, erschossen von Slater', 'Struktur: 9 spielbare Schauplatz-Kapitel + 4 Aftermath-Teile + das Final Aftermath', 'Laufzeit: etwa 2,5 Stunden direkt; längere Durchläufe Richtung 4 Stunden', 'Enden: ein Hauptlinien-Ende, keine Verzweigungen'] },
      { title: 'Die Prämisse', paragraphs: ['Die offizielle Store-Prämisse startet die Geschichte mit einem grimmigen Muster: Opfer werden gehäutet, ihr Fleisch an nahe Wände getackert, und verzerrte Audiokassetten an den Tatorten höhnen die Polizei aus. Slater, ein ausgebrannter Detective, bekommt den Fall — und der Hook ist, dass du nicht nur die Ermittlung spielst, sondern Kapitel lang in den Leben der Verfolgten sitzt.', 'Diese Doppelstruktur ist der Motor der Story. Ein Kapitel setzt dich an Slaters Schreibtisch im Carrion City Police Department, das nächste in ein Apartment, einen Laden oder eine Bowlingbahn, während der Verfolger näherkommt. Die Aftermath-Zwischenspiele falten jede Opfergeschichte zurück in die Akte, bis die Ermittlung einen Verdächtigen benennt.'] },
      { title: 'Wie die 14 Kapitel die Story erzählen', paragraphs: ['Die spielbare Route: Burrows Apartments mit Fefe am Anfang, Carrion City Police Department mit Slater, Quick Fix mit Hexy, Gutters End mit Blair, Lunas Donutladen, Underworld VHS mit Scaroline und Lazar’s Blood Bank mit Nurse Layna. Vier Aftermath-Teile liegen zwischen den Schauplatz-Kapiteln, das Final Aftermath verbindet die Ermittlung mit dem Endspiel. Dann folgt Closing In, und The Flesh Pit schließt die Geschichte ab.', 'Steams Erfolgsliste bestätigt genau diese Kapitelfolge, und der Referenz-Walkthrough setzt Zeitstempel: Burrows Apartments bei 00:03:06 bis The Flesh Pit bei 02:34:00.'] },
      { title: 'Die Identität des Killers: Elias Crow', paragraphs: ['Die Ermittlung läuft auf eine einzige Enthüllung zu: Der Skin Stapler ist Elias Crow, der öffentliche Besitzer des Flesh Pit, im Spiel als beste Barbecue der Stadt beworben. Der Name steht von Anfang an sichtbar im Raum — die Flesh-Pit-Werbung erscheint früh, und späte Dialoge sagen direkt, dass Elias Crow das Restaurant besitzt.', 'Die Enthüllung trägt, weil das Spiel die Teile über alle Perspektiven verteilt: Verdächtigenakten, die Flesh-Pit-Anzeige, Tatort-Kassetten und die Aftermath-Segmente halten je ein Fragment, und die Detectives setzen sie im Bild zusammen statt in einem einzigen Expositionsblock.'] },
      { title: 'Zwillings-Ursprung und Motiv', paragraphs: ['Das Motiv ist das emotionale Rückgrat: Slater erschoss Elias’ Zwillingsbruder Silus Kain, und Elias baut seine Mordserie darauf, Slater einen gleichwertigen Verlust zuzufügen. Ein später Dialog bringt es auf den Punkt: Dick, du hast seinen Bruder getötet, und jetzt will Elias Rache.', 'Eine Waisenhaus-Aufnahme in der Stimme von Father Omani erklärt, wie zwei Brüder auf gegenüberliegende Seiten desselben Falls gerieten: Die Zwillinge wurden bei der Geburt getrennt, einer zur Familie Ken gebracht und Silus genannt, der andere zur Familie Crow und Elias genannt. Automatische Untertitel schreiben den Nachnamen stellenweise Kane oder Ken; diese Seite standardisiert auf Kain, die Schreibweise der Walkthrough- und Ending-Seiten.'] },
      { title: 'Wie die Kassetten die Handlung treiben', paragraphs: ['Die verzerrten Audiokassetten sind das Bindegewebe der Story. Der Killer hinterlässt sie an Tatorten, um die Polizei zu verspotten, und das Reparieren und Auswerten wird zur laufenden Ermittlungsaufgabe — der Steam-Erfolg Jank Ya Later! löst sogar speziell für das Reparieren der Skin-Stapler-Kassetten aus. Die Waisenhaus-Aufnahme, der tiefste Hinweis der Story, kommt ebenfalls über eine Kassette.', 'Einzelkapitel füttern den Kassettenfaden mit: eine VHS aus Lunas Tatort fließt in den Fall ein, und Scarolines Underworld-VHS-Kapitel spielt genau dort, wo Kassettenhandling zum Job gehört.'] },
      { title: 'Das Ende: eine Konfrontation im Flesh Pit', paragraphs: ['Die Geschichte hat ein Ende, und zwei unabhängige Komplett-Durchläufe bestätigen dieselbe Sequenz. Slater verfolgt den Killer bis ins Flesh Pit, sein eigenes Restaurant. Elias verschafft sich zuerst die Oberhand: Robbie Knox wird niedergestreckt, und Elias drängt Slater, Robbies Waffe aufzunehmen. Slater tut es, schießt auf Elias und verlässt Carrion City.', 'Es gibt kein Moral-Menü, keine verzweigten Dialoge und kein alternatives Finale. Was danach mit Elias passiert — Tod am Ort oder Festnahme — bleibt in den geprüften Aufzeichnungen offen. In jedem Fall verlässt der Detective die Stadt, und die Story endet dort, wo die Prämisse begann: Slater, der Fall und eine Stadt, die beiden Brüdern alles nahm.'] },
      { title: 'Wie du die Story erlebst', paragraphs: [], bullets: ['Spiel die Schauplatz-Kapitel in Routenreihenfolge: Das Spiel ist linear, und jede Kapitelwende fließt direkt in die nächste; eine Kapitelauswahl gibt es für Wiederholungen', 'Behandle jede Kassetten-Interaktion: Reparierte Kassetten sind zuerst Plotgeräte, dann Erfolge — die Waisenhaus-Aufnahme und die Tatort-Kassetten sind die zwei größten Enthüllungen', 'Überspringe keine Aftermath-Teile: Die vier Aftermath-Teile und das Final Aftermath verbinden die Opferkapitel mit Slaters Fall; ohne sie bricht die Erzählkette'] }
    ],
    faq: [
      { question: 'Wer ist der Skin Stapler in der Story?', answer: 'Elias Crow, Besitzer des Flesh-Pit-Grillrestaurants. Die Ermittlung enthüllt seine Identität spät, das Finale stellt ihn im Restaurant.' },
      { question: 'Warum tötet der Skin Stapler seine Opfer?', answer: 'Rache. Slater erschoss seinen Zwillingsbruder Silus Kain, und Elias inszeniert seine Morde als Antwort — gehäutete Opfer, getackertes Fleisch und höhnische Kassetten an die Polizei.' },
      { question: 'Wie lang ist die Story?', answer: 'Etwa 2,5 Stunden für einen direkten Durchlauf über 14 kurze Kapitel; aufgezeichnete Läufe mit mehr Erkundung liegen näher an 3 Stunden, langsamere Erstdurchläufe Richtung 4.' },
      { question: 'Fasst Slater den Killer?', answer: 'Ja. Die Story endet im Flesh Pit: Nachdem Robbie niedergestreckt wurde, schießt Slater auf Elias und verlässt Carrion City.' },
      { question: 'Ist die Story mit der Demo verbunden?', answer: 'Die drei Demo-Abschnitte — Polizeiwache, Quick Fix und Gutters End — sind die Kapitel 2 bis 4 in verkürzter Form. Das Vollspiel beginnt von vorn mit Fefes Apartment.' }
    ],
    sources: sourceSets.story
  },
  'games-like': {
    id: 'games-like', keyword: 'Spiele wie The Skin Stapler',
    title: 'Spiele wie The Skin Stapler: 6 Titel, die wirklich passen',
    description: 'Spiele wie The Skin Stapler: Sniper Killer, Rewind or Die und die vier Tainted-Pact-Horrorspiele — mit dem Grund, warum jeder Titel hier passt.',
    eyebrow: 'Vergleichstitel',
    directAnswer: 'Die nächsten Spiele wie The Skin Stapler sind Sniper Killer und Rewind or Die — die beiden direkten Vergleichspunkte eines Bloody-Disgusting-Tests — plus die vier früheren Horrorspiele desselben Entwicklers Tainted Pact: Suffer the Night, Terror at Oakheart, Massacre at the Mirage und Flesh Made Fear. Alle sechs teilen kurze Laufzeit, Grindhouse-Humor und Low-Poly-Horror-Präsentation.',
    date: '2026-09-03',
    sections: [
      { title: 'Die Vergleichstitel auf einen Blick', paragraphs: ['Die Liste kommt aus zwei Richtungen: dem Test, der Sniper Killer und Rewind or Die beim Namen nennt, und den Katalogen von Entwickler und Publisher, die die vier Tainted-Pact-Titel führen:'], bullets: ['Sniper Killer — vom Test als nächster Vergleich genannt: Serienkiller-Prämisse, Job-Sim-Tempo, PSX-Optik', 'Rewind or Die — ebenfalls vom Test genannt: VHS-Ästhetik, Kassetten-Mechanik, Grindhouse-Humor', 'Suffer the Night — Tainted Pacts erstes Horrorspiel: Analog-Horror um einen gruseligen Retro-Computer', 'Terror at Oakheart — Tainted Pact: Slasher am Camp, gleiche stilisierte Gewalt, B-Movie-Ton', 'Massacre at the Mirage — Tainted Pact: Hotel-Slasher mit szenenbasierter Struktur', 'Flesh Made Fear — Tainted Pact: direkter Vorgänger, Serienkiller-Story mit vertonten Szenen'] },
      { title: 'Warum Sniper Killer die Nummer eins ist', paragraphs: ['Sniper Killer kombiniert eine Serienkiller-Jagd mit banalen Job-Aufgaben und einer absichtlich hässlichen PSX-Ästhetik — dasselbe Skelett, auf dem The Skin Stapler baut. Kritiker greifen beim Testen namentlich zu ihm, womit er die sicherste erste Anschaffung für den nächsten Carrion-City-Fall ist.', 'Der Ton trifft ebenfalls: beide Spiele spielen ihr grobes Material mit ernster Miene und einem Grinsen gleichzeitig, setzen auf vollständig vertonte Dialoge und wickeln eine kurze Story um einfache Interaktionen. War dein Liebsteil die Ermittlung, ist Sniper Killer der nächste Stopp; waren es die Arbeitskapitel, passt der Tainted-Pact-Katalog besser.'] },
      { title: 'Warum Rewind or Die immer wieder auftaucht', paragraphs: ['Rewind or Die teilt die Retro-Videoladen-DNA, die The Skin Stapler offen trägt: VHS-Ästhetik, Kassetten-Mechanik und ein auf Witze getrimmtes Slasher-Skript. Der Test zitiert es neben Sniper Killer als Publikumstest: Fans eines der beiden Spiele sind das Profil, das The Skin Stapler einen Schädel höher wertet.', 'Für alle, die Scarolines Underworld-VHS-Kapitel am besten fanden, ist es ohnehin der richtige Treffer — Laden-Setting, Zurückspulen und Analog-Video-Humor zeigen in dieselbe Richtung.'] },
      { title: 'Die vier früheren Tainted-Pact-Horrorspiele', paragraphs: ['Tainted Pact hat The Skin Stapler als Solo-Entwickler gebaut; der Katalog listet vier frühere Horrortitel, bestätigt sowohl über die Release-Ankündigung des Publishers als auch über den GOG-Katalog: Suffer the Night als Analog-Horror-Debüt um einen verfluchten Retro-Computer, Terror at Oakheart als Camp-Slasher mit kurzer Struktur und stilisierter Gewalt, Massacre at the Mirage als Hotel-Slasher mit szenweisem Tempo und schwarzem Humor, und Flesh Made Fear als direktester Vorgänger — eine Serienkiller-Story mit vertonten Szenen und Grindhouse-Kante.', 'Gespielt in Release-Reihenfolge zeigt der Katalog die Linie: Jedes Spiel rückt näher an das vollständig vertonte, FMV-gefärbte Perspektivwechsel-Format, das The Skin Stapler liefert.'] },
      { title: 'Was diese Spiele gemeinsam haben', paragraphs: [], bullets: ['Kurze Laufzeiten: The Skin Stapler läuft etwa 2,5 Stunden über 14 Kapitel; alle Vergleichstitel sind Ein-Sitzung-Spiele', 'Job-Sim-Schleifen und QTE-Interaktionen: Hotdogs servieren, Donuts befüllen, Kassetten zurückspulen — die banale Aufgabe als Horror-Motor ist die Genre-Signatur', 'Vollständig vertonte Besetzungen: The Skin Stapler nennt zehn Sprecher; die Vergleichsreihe setzt ebenfalls auf komplette Vertonung', 'Synthlastige Retro-Scores: Carpenter-artige Synththemes ziehen sich durch den ganzen Katalog', 'FMV- und Videoformat-Einlagen: VHS-artige Full-Motion-Video-Sequenzen sind der Präsentationskleber', 'Absichtlich plumper Humor: die Verlags-Tagline — vor dem Tod ein letzter Lacher — beschreibt das gemeinsame Register'] },
      { title: 'So wählst du dein nächstes Spiel', paragraphs: [], bullets: ['Pass das Kapitel an, das dir am besten gefiel: Ermittlung → Sniper Killer; Videoladen → Rewind or Die; Arbeitskapitel → Flesh Made Fear und die früheren Tainted-Pact-Spiele', 'Prüf die Laufzeit: Alle sechs Titel sind kurz — für eine weitere 2-bis-4-Stunden-Geschichte passt jeder; wer länger investieren will, findet hier nichts', 'Kauf in den offiziellen Stores: Der Tainted-Pact-Katalog liegt auf Steam und GOG; der PC-Download-Ratgeber listet die offiziellen Kanäle für den neuesten Titel'] }
    ],
    faq: [
      { question: 'Gibt es ein Sequel oder ein Spiel genau wie The Skin Stapler?', answer: 'Kein direktes Sequel. Flesh Made Fear ist das nächste frühere Spiel desselben Entwicklers, Sniper Killer der nächste Treffer von außerhalb des Studios.' },
      { question: 'Sind die Tainted-Pact-Spiele inhaltlich verbunden?', answer: 'Kein bestätigtes geteiltes Universum über die vier früheren Titel und The Skin Stapler. Die Verbindung ist Ton, Format und Entwickler, nicht Handlung.' },
      { question: 'Welches Spiel sollte ich zuerst spielen?', answer: 'Sniper Killer — Kritiker nennen es als direkten Vergleich, und seine Serienkiller-Ermittlungsschleife spiegelt Slaters Kapitel am nächsten.' },
      { question: 'Haben die Spiele denselben Humor?', answer: 'Ja — Grindhouse-Witze, groteske Nebenfiguren und B-Movie-Inszenierung sind das gemeinsame Register, das die Verlags-Tagline für die ganze Reihe zusammenfasst.' },
      { question: 'Erscheinen diese Spiele im Game Pass oder in Abo-Diensten?', answer: 'Abo-Verfügbarkeit wechselt je Dienst und Region — prüfe die aktuelle Store-Seite. Steam und GOG bleiben die bestätigten Kaufkanäle des Tainted-Pact-Katalogs.' }
    ],
    sources: sourceSets['games-like']
  },
  uncensored: {
    id: 'uncensored', keyword: 'The Skin Stapler Uncensored',
    title: 'The Skin Stapler Uncensored: Eine Version, überall ungeschnitten',
    description: 'The Skin Stapler ungeschnitten: Steam und GOG verkaufen dieselbe ungeschnittene Fassung — ohne Zensur-SKU, Regionalschnitt oder Gewalt-Schalter.',
    eyebrow: 'Fassungs-Check',
    directAnswer: 'The Skin Stapler erscheint nicht in einer zensierten Version: Steam und GOG vertreiben jeweils genau einen ungeschnittenen Build mit voller Gewalt — ohne separate Uncut-SKU, Regionalschnitt oder Inhaltsschalter. Die offizielle Beschreibung der Killermethode steht unzensiert auf den Store-Seiten selbst.',
    date: '2026-09-03',
    sections: [
      { title: 'Was eine einzige Version praktisch bedeutet', paragraphs: ['Diese Punkte beantworten die üblichen Fassungsfragen im Überblick:'], bullets: ['Steam: ein Basisspiel (App 4310610) plus zwei DLCs — keine separate Schnittfassung', 'GOG: ein Vollspiel; die Skin-DLCs sind im GOG-Kauf enthalten', 'Inhaltsschalter: keiner auf den Store-Seiten beworben', 'Regionalschnitte: keine angeboten oder dokumentiert', 'Alterskennzeichnung: weder PEGI noch ESRB auf einer der Store-Seiten angezeigt', 'Intensität: gehäutete Opfer, getackertes Fleisch, verzerrte Kassetten, sexuelle Inhalte, groteske Figuren'] },
      { title: 'Was der Uncut-Inhalt umfasst', paragraphs: ['Die Titel-Mechanik des Spiels ist zugleich die Inhaltswarnung: Opfer werden gehäutet und ihr Fleisch an nahe Wände getackert — die offizielle Store-Beschreibung nennt das als Signatur des Killers, und die Tatorte im Spiel sind um diese Methode herum inszeniert. Die vernähten Hautmotive in der offiziellen Galerie zeigen, was die Engine darstellt.', 'Der Bloody-Disgusting-Test ergänzt das Intensitätsprofil: grafische Gewalt, sexuelle Inhalte und absichtlich groteske Figuren. Das Marketing des Publishers spielt denselben Ton — die Pressematerialien versprechen einen letzten Lacher vor dem Tod, und die Witze liegen auf derselben Frequenz wie die Gewalt. Wer eine Uncut-Version sucht, sucht in die falsche Richtung: zurückgestutzt wurde nie etwas.'] },
      { title: 'Warum es keine separate Uncut-SKU gibt', paragraphs: ['Die Steam-Produktstruktur beantwortet das strukturell: Der Store listet eine Basis-App plus zwei DLCs — ein Kosmetik-Skinpack und einen Soundtrack — ohne alternative Builds. GOG spiegelt das mit einem einzelnen Spiel, das die Skin-DLCs bündelt. Eine zensierte Variante bräuchte einen zweiten Store-Eintrag, einen Startschalter oder einen regionalen Release-Vermerk — keins davon existiert.', 'Diese Struktur gilt auch für Suchen nach Uncut-Patch oder restaurierten Inhalten: Es gibt nichts Entferntes zum Restaurieren. Der eine Build des Entwicklers ist der komplette Build, und der PC-Download-Ratgeber listet die beiden offiziellen Stores.'] },
      { title: 'Alterskennzeichnung und Store-Schranken', paragraphs: ['Weder die Steam- noch die GOG-Seite zeigt eine PEGI- oder ESRB-Einstufung — üblich bei kleinen Indie-Releases ohne Handelsvertrieb. Die Stores ziehen stattdessen eigene Altersschranken beim Kauf. Wenn eine Einstufung für deinen Haushalt oder deine Region zählt, prüfe die Store-Seite deines Landes vor dem Kauf; die Inhaltsangaben oben sind die ehrlichste Vorschau.', 'Die Demo folgt derselben Linie: kostenlos, dieselbe stilisierte Gewalt, keine separate Kennzeichnung auf ihrer Store-Seite. Was ihre drei Abschnitte enthalten, deckt der Demo-Ratgeber ab.'] },
      { title: 'So prüfst du den Inhalt selbst', paragraphs: [], bullets: ['Öffne die Steam-Galerie: Die offiziellen Screenshots zeigen die echte Renderqualität — vernähte Hautporträts, Tatorte, das Handwerk des Killers — ohne redaktionelle Glättung', 'Schau ein aufgezeichnetes Kapitel: Komplett-Durchläufe der Fefe-Eröffnung und des Quick Fix zeigen, wie die Gewalt inszeniert ist und wie oft sie auftaucht', 'Lies die Store-Beschreibung: Gehäutete Opfer, getackertes Fleisch, höhnische Kassetten — der offizielle Pitch ist die ehrlichste Inhaltswarnung, beide Stores zeigen sie auf der Kaufseite'] }
    ],
    faq: [
      { question: 'Ist The Skin Stapler auf Steam zensiert?', answer: 'Nein. Steam verkauft genau einen ungeschnittenen Build, und die eigene Store-Beschreibung beschreibt die Signatur-Gewalt ungeschönt.' },
      { question: 'Ist die GOG-Fassung anders als die Steam-Fassung?', answer: 'Nein — dasselbe ungeschnittene Spiel, und der GOG-Kauf schließt das Skin-Jankers-Kosmetik-DLC ein, das Steam separat verkauft. Einen anderen Inhaltsschnitt gibt es in keinem Store.' },
      { question: 'Gibt es einen Schalter, um die Gewalt abzuschalten?', answer: 'Nein. Kein Store listet einen Inhaltsschalter; die Gewalt ist Kern der Identität des Spiels.' },
      { question: 'Warum finde ich keine Altersfreigabe?', answer: 'Keine PEGI- oder ESRB-Einstufung wird auf den Store-Seiten angezeigt. Digital erstveröffentlichte Indie-Titel überspringen formale Freigaben oft und setzen auf die Altersschranken der Stores — prüfe die Store-Seite deiner Region.' },
      { question: 'Enthält die Demo denselben Inhalt?', answer: 'Ja. Die kostenlose Demo zeigt in ihren drei spielbaren Abschnitten dieselbe stilisierte Gewalt — genau deshalb funktioniert sie als Inhaltsvorschau vor dem Kauf.' }
    ],
    sources: sourceSets.uncensored
  },
  'donut-shop': {
    id: 'donut-shop', keyword: 'The Skin Stapler Donut Shop Code',
    title: 'The Skin Stapler Donut Shop Code: Den gibt es nicht',
    description: 'Donut-Shop-Code in The Skin Stapler gesucht? Lunas Cream Filled Donuts ist eine Servier-Station ohne Code — der echte Code im Spiel lautet 1979.',
    eyebrow: 'Mythos-Check',
    directAnswer: 'Einen Donut-Shop-Code in The Skin Stapler gibt es nicht. Lunas Cream Filled Donuts ist ein spielbares Arbeitssim-Kapitel, in dem du Donut- und Kaffeebestellungen Schritt für Schritt abarbeitest — kein Tresor, kein Keypad, kein Rätsel. Ein echtes vierstelliges Code-Rätsel existiert im Spiel, gehört aber zur Ermittlungslinie: der Bilderrahmen-Code 1979.',
    date: '2026-09-03',
    sections: [
      { title: 'Was das Donut-Shop-Kapitel verlangt', paragraphs: ['Steams Erfolgsliste bestätigt Name und Position des Kapitels, Komplett-Videos bestätigen das Format — eine Servierschleife nach dem Muster von Hexys Hotdog-Sequenz im Quick Fix, kein Rätselkästchen:'], bullets: ['Kapitelname: Luna’s Cream Filled Donuts (laut offizieller Steam-Erfolgsliste)', 'Spielbare Figur: Luna, Besitzerin des Ladens', 'Position in der Route: zwischen Gutters End und Underworld VHS — das fünfte Schauplatz-Kapitel', 'Aufgabentyp: mehrstufige Servierarbeit — Donuts und Kaffee in Sequenz', 'Code oder Passwort: keiner — der Fortschritt kommt über die Servierschritte', 'Verwandter Erfolg: LunaArcana - Glazed and Confused für den Kapitelabschluss'] },
      { title: 'Warum Spieler nach einem Donut-Shop-Code suchen', paragraphs: ['In den Suchanfragen verschmelzen zwei Spiele. Das erste ist The Skin Stapler selbst: Ein Horrorspiel voller Code-naher Bildsprache — Keypads, Beweise, verschlossene Schubladen — legt nahe, dass jeder benannte Ort ein Passwort versteckt. Das zweite ist die Genre-Gewohnheit: PSX-artige Horrorspiele nutzen oft Zahlencodes, also vervollständigen Suchmaschinen das Muster, obwohl genau dieses Spiel an dieser Stelle ein solches Rätsel nicht hat.', 'Der echte Zahlencode im Spiel gehört woanders hin: zum Bilderrahmen-Schloss der Ermittlungslinie, dessen Lösung 1979 lautet. Diese Antwort ist im Rätsel-Ratgeber dokumentiert — wenn du eine vierstellige Lösung suchst, ist 1979 der Code, den das Spiel tatsächlich verwendet.'] },
      { title: 'Wie das Kapitel abläuft', paragraphs: [], bullets: ['Beginne die Schicht: Lunas Kapitel öffnet an der Ladentheke, und die Zielführung führt dich in den Servierablauf — die Bildschirmziele sind das einzige Tutorial, das du brauchst', 'Fülle jede Bestellung in Sequenz: Donuts und Kaffee folgen der mehrstufigen Zubereitung, die das Spiel vorführt; eine fertige Bestellung aktiviert den nächsten Kunden, genau wie die Hotdog-Schleife im Quick Fix', 'Beende die Schicht für die Story: Das Kapitel endet, wenn die Servierarbeit durch ist und der Story-Beat landet — kein versteckter Code, kein optionales Schloss. Der Erfolg springt beim Kapitelabschluss'] },
      { title: 'Codes, die im Spiel wirklich existieren', paragraphs: ['Die belegten Rätselantworten sind wenige und dokumentiert: der 1979er Bilderrahmen-Code in den Ermittlungskapiteln, das Fleischwaagen-Rätsel im Flesh Pit und die beschädigten Kassetten-Interaktionen, die die Story speisen und den Kassetten-Reparatur-Erfolg freischalten. Keines davon hängt an Lunas Donutladen, und keines nutzt einen einlösbaren Textcode.', 'Einen globalen Skip-Code gibt es ebenfalls nicht. Der komplette Walkthrough notiert: Behauptungen über Master-Passwörter oder universelle Kapitelsprünge stützt kein einziges Komplett-Video — die Route geht nur über erledigte Ziele weiter.'] }
    ],
    faq: [
      { question: 'Was ist der Donut-Shop-Code in The Skin Stapler?', answer: 'Es gibt keinen. Luna’s Cream Filled Donuts ist ein Servierkapitel ohne Code. Der einzige vierstellige Code des Spiels ist 1979 am Bilderrahmen-Schloss der Ermittlung.' },
      { question: 'Ist das Donut-Shop-Kapitel in der Demo?', answer: 'Nein. Die kostenlose Demo umfasst Polizeiwache, Quick Fix und Gutters End. Lunas Laden ist Vollspiel-Inhalt.' },
      { question: 'Wie bekomme ich Glazed and Confused?', answer: 'Schließe Luna’s Cream Filled Donuts ab — der Erfolg springt beim Kapitelende. Keine versteckte Bedingung, keine geheime Bestellreihenfolge, kein Code.' },
      { question: 'Wer ist Luna?', answer: 'Luna betreibt den Donut- und Kaffeeladen und ist eine der spielbaren Perspektiven des Spiels; der Luna-Charakter-Ratgeber deckt Rolle, Sprecherin und Story-Ort ab.' },
      { question: 'Warum schlägt Google einen Donut-Shop-Code vor?', answer: 'Suchmaschinen vermischen die Keypad-und-Codes-Bildsprache des Spiels mit Genre-Gewohnheiten anderer PSX-Horrorspiele. Das Autocomplete-Muster spiegelt kein echtes Rätsel dieses Spiels.' }
    ],
    sources: sourceSets['donut-shop']
  },
  'all-tapes': {
    id: 'all-tapes', keyword: 'The Skin Stapler Kassetten',
    title: 'The Skin Stapler Kassetten: Rolle, Reparatur und Reveals',
    description: 'Die Kassetten in The Skin Stapler: Spott-Töne der Polizei, Reparaturaufgaben, der Jank-Ya-Later-Erfolg und die Waisenhaus-Aufnahme mit dem Zwillings-Geheimnis.',
    eyebrow: 'Kassetten und Story-Belege',
    directAnswer: 'Die Kassetten sind die Stimme des Killers: verzerrte Aufnahmen an Tatorten, mit denen er die Polizei höhnt, plus Ermittlungs-Aufnahmen, die den Fall zusammensetzen. Du sammelst, reparierst und wertest sie auf der gesamten Route aus, und der Steam-Erfolg Runebee’s Jank Ya Later! löst speziell für das Reparieren der Skin-Stapler-Kassetten aus. Einen Gesamtzähler zeigt das Spiel nicht — die exakte Anzahl ist eine Angabe, die du im Spiel prüfen musst.',
    date: '2026-09-03',
    sections: [
      { title: 'Was die Kassetten leisten', paragraphs: ['Sechs Zeilen, drei Jobs: Die Kassetten sind gleichzeitig Atmosphäre, Beweis und Plotgerät:'], bullets: ['Offizielle Rolle: Audioaufnahmen, die an Tatorten die Polizei höhnen (Store-Beschreibung)', 'Gameplay-Rolle: Sammelobjekte, die du als Ermittlungsbeweis reparierst und auswertest', 'Story-Rolle: tragen die Stimme des Killers und den Zwillings-Ursprungshinweis', 'Reparatur-Mechanik: beschädigte Kassetten werden auf der Route repariert; ein universeller Reparatur-Code existiert nicht', 'Erfolg: Jank Ya Later! — Fix The Skin Stapler Tapes', 'Gesamtzahl: weder im Spiel noch im offiziellen Material angezeigt'] },
      { title: 'Die Spott-Kassetten: der Killer spricht zur Polizei', paragraphs: ['Die offizielle Prämisse sagt es klar: Opfer werden gehäutet und an Wände getackert, und verzerrte Audiokassetten an den Tatorten höhnen die Polizei aus. Diese Aufnahmen geben dem Killer eine Stimme, ohne ihn zu zeigen — das frühe Audio ist bewusst widerlich und rahmt die Ermittlung als ein Gespräch, das der Killer per Tatort mit Slater führt.', 'Die Spott-Kassetten setzen auch den Ton des Spiels. Tester benennen den schwarzen Humor als Kennzeichen, und das Kassetten-Audio ist die lauteste Stelle dieses Registers: Der Killer gibt eine Show für die Ermittler, und die verzerrte VHS-Ära-Delivery macht die Witze kälter.'] },
      { title: 'Die Ermittlungs-Kassetten: die Akte als Audio', paragraphs: ['Jenseits der Spott-Töne macht der Reparatur-und-Auswertungs-Loop die Kassetten zu Beweisen. Beschädigte Kassetten tauchen über die Kapitel verteilt auf, und das Spiel verlangt, sie zu reparieren oder anzuhören, bevor die Ermittlung weitergeht — Steams Erfolgsliste benennt die Tätigkeit direkt, und Komplett-Videos zeigen Slater bei der Kassettenreparatur im späten Abschnitt bei DJ Woolz’ Radiosender.', 'Dieser Reparatur-Durchgang ist die mechanische Auszahlung des Kassettenfadens: Das Reparieren der Skin-Stapler-Kassetten ist eine namentlich genannte Erfolgsvoraussetzung, und die reparierten Aufnahmen speisen die Enthüllungen, die den Fall beenden. Hakt eine Kassetten-Interaktion, ist der Grund fast immer ein nicht beendetes Gespräch oder ein unbearbeitetes Ziel im selben Raum — der Walkthrough listet die Interaktions-Sperren der Route in Reihenfolge.'] },
      { title: 'Die Waisenhaus-Kassette: die größte Enthüllung', paragraphs: ['Eine Aufnahme wiegt mehr als alle anderen. Das Waisenhaus-Audio in der Stimme von Father Omani offenbart, dass der Killer und sein Bruder Zwillinge waren, die bei der Geburt getrennt wurden — einer zur Familie Ken gebracht und Silus genannt, der andere zur Familie Crow und Elias genannt. Diese einzelne Aufnahme verwandelt die Serienkiller-Story in eine Rache-Story, die auf Slater selbst zielt.', 'Der Kassettenfaden läuft dadurch durch jeden großen Beat: eine VHS aus Lunas Tatort, die Kassette, die Scaroline bei Underworld VHS bearbeitet, die späte Come-find-me-Aufnahme und Slaters eigene private Aufnahme — alles speist dieselbe Enthüllungskette.'] },
      { title: 'Wo die Kassettenarbeit in der Route sitzt', paragraphs: [], bullets: ['Ermittlungskapitel: Slaters CCPD-Abschnitte öffnen den Kassetten-Loop — Tatort-Aufnahmen wandern in die Akte, die Reparaturaufgaben beginnen', 'Arbeitskapitel: Lunas Laden und Scarolines Underworld VHS binden physische Kassetten an die Story — eine wird Tatort-Beweis, die andere macht Kassettenhandling zum spielbaren Job', 'Späte Reparatur-Session: Die Closing-In-Strecke enthält den Radiosender-Besuch, an dem die beschädigten Kassetten repariert werden — das erfüllt die Jank-Ya-Later-Voraussetzung und schließt die Beweiskette vor dem Finale'] },
      { title: 'Community-Behauptungen zu den Kassetten', paragraphs: ['Ein Fan-Wiki berichtet von kleinen Epilog-Unterschieden je nachdem, welche Kassetten du hörst — eine Behauptung, die bei jedem Horrorspiel mit Sammel-Audio kursiert. Abgeglichene Komplett-Läufe mit unterschiedlichen Enden sind nie aufgetaucht; zwei unabhängige Komplett-Durchläufe zeigen dasselbe Finale, egal wie du mit Kassetten umgehst. Solange niemand zwei abgeglichene, abweichende Läufe veröffentlicht, gilt die Ein-Ende-Struktur als maßgeblicher Fakt.', 'Dasselbe Misstrauen gilt für Kassettenzählungen. Ohne In-Game-Zähler und offizielle Angabe ist jede Total im Netz bestenfalls eine Spielerschätzung — die ehrliche Antwort ist, dass das Spiel keine anzeigt.'] }
    ],
    faq: [
      { question: 'Wie viele Kassetten gibt es in The Skin Stapler?', answer: 'Das Spiel zeigt keine Gesamtzahl, und das offizielle Material veröffentlicht keine — die exakte Anzahl verrät erst der Spielverlauf. Bestätigt ist die Mechanik: sammeln, reparieren, auswerten, so oft die Route es verlangt.' },
      { question: 'Welcher Erfolg hängt an den Kassetten?', answer: 'Runebee - Jank Ya Later!, der laut offiziellem Steam-Anforderungstext für das Reparieren der Skin-Stapler-Kassetten freigeschaltet wird.' },
      { question: 'Ändern die Kassetten das Ende?', answer: 'Ein Fan-Wiki behauptet kleine Epilog-Variationen, aber abgeglichene Läufe, die das zeigen, fehlen. Zwei Komplett-Durchläufe bestätigen dasselbe eine Ende; der Ending-Ratgeber deckt das Finale ab.' },
      { question: 'Wo repariere ich die Kassetten?', answer: 'Die späte Route bringt die beschädigten Kassetten zu DJ Woolz’ Radiosender während Closing In — im Referenz-Durchlauf liegt dieser Abschnitt bei etwa 02:18:29.' },
      { question: 'Sind die Kassetten die Stimme des Killers?', answer: 'Ja — die Store-Beschreibung sagt, dass verzerrte Audiokassetten die Polizei höhnen, und die zentrale Waisenhaus-Aufnahme legt den Zwillings-Ursprung offen, der das Motiv erklärt.' }
    ],
    sources: sourceSets['all-tapes']
  },
  'ai-generated': {
    id: 'ai-generated', keyword: 'The Skin Stapler KI',
    title: 'Ist The Skin Stapler KI-generiert? Nein — und so lautet der Beleg',
    description: 'The Skin Stapler ist kein KI-Spiel: Handmade-Aussage der Store-Seite, zehn namentliche Sprecher und ein Jahr öffentliche Entwicklung zeigen die handgemachte Produktion.',
    eyebrow: 'Produktions-Check',
    directAnswer: 'Nein — The Skin Stapler ist kein KI-generiertes Spiel. Die Store-Seite trägt die Schlagzeile A HANDCRAFTED HORROR EXPERIENCE — handmade horror, with no shortcuts, dahinter steht ein Solo-Entwickler mit einem Jahr öffentlicher Entwicklung, zehn namentlich genannte Sprecher auf dem offiziellen Cast-Poster und handgebaute FMV-Sequenzen, die der Test lobt.',
    date: '2026-09-03',
    sections: [
      { title: 'Was das offizielle Material zeigt', paragraphs: ['Jede Zeile dieser Übersicht lässt sich direkt gegenprüfen:'], bullets: ['Store-Schlagzeile: „A HANDCRAFTED HORROR EXPERIENCE — handmade horror, with no shortcuts“', 'Entwicklung: Solo-Entwickler Tainted Pact (USA)', 'Sprecher: 10 namentlich genannte Performer auf dem offiziellen Cast-Poster', 'Präsentation: VHS-artige FMV-Sequenzen, von der Testberichterstattung gelobt', 'Store-Publisher: Assemble Entertainment GmbH (Copyright-Zeile)', 'Startdaten: 16 Erfolge; rund 90 % Positiv aus etwa 340 Rezensionen'] },
      { title: 'Die offizielle Handmade-Aussage', paragraphs: ['Die Steam-Seite führt „handmade horror, with no shortcuts“ als Feature-Aussage auf dem ersten Bildschirm. Marketingzeilen sind allein kein Beweis, aber diese ist für einen Storefront-Text ungewöhnlich konkret: Sie verpflichtet den Entwickler auf handgefertigte Assets und passt zur Produktions-Spur drumherum — ein Entwickler, ein Creator-Cast, ein Jahr öffentlicher Dev-Logs.', 'Das Pressematerial des Publishers wiederholt den Handmade-Rahmen, und kein offizieller Kanal zum Spiel wirbt mit KI-generierter Grafik, KI-Stimmen oder KI-Texten. Für ein kleines Release, das auf seiner Grindhouse-Persönlichkeit verkauft wird, ist diese Konsistenz über alle Kanäle das stärkste öffentliche Signal.'] },
      { title: 'Zehn namentlich genannte Menschen sprechen die Rollen', paragraphs: ['Das offizielle Cast-Poster nennt zehn Sprecher: RJ Green als Dick Slater, Daniel Suraci als Robbie Knox, HexyIRL als Hexy und den Titelkiller, Layna Lazar als Nurse Layna, Runebee als Bee, Luna Arcana als Luna, Blairvira als Blair, FeFe als Fefe, Scaroline als Scaroline und KingWoolz als DJ Woolz. Mehrere sind arbeitende Creator mit öffentlichen Kanälen — der Sprecher-Ratgeber ordnet jede Rolle zu.', 'Genau deshalb ist die KI-Frage beantwortbar: Die Sprachperformance ist der Ort, an dem KI-Verdacht üblicherweise landet. Das Spiel ist vollständig auf Englisch vertont — Steam listet volle englische Sprachausgabe — und jede Hauptrolle mappt auf eine namentlich genannte Person, die die Rolle auf eigenen Kanälen bewirbt. Der Creator-Cast-Ansatz ist zusätzlich eine bewusste Marketing-Strategie: der Publisher notiert, das Spiel sei mit Unterstützung von Content-Creators gebaut — das Gegenteil einer anonymen Generierungs-Pipeline.'] },
      { title: 'Ein Entwickler, der öffentlich baut', paragraphs: ['Tainted Pact ist ein Solo-Studio aus den USA, und die Entwicklung lief öffentlich: Der YouTube-Kanal veröffentlichte Dev-Log-Einträge im Dezember 2025, und die itch.io-Präsenz dokumentiert die Projektspur bis zu The Skin Stapler. Solo-Entwicklung schließt Werkzeugunterstützung nicht aus, aber sie bedeutet, dass jedes Asset durch eine verantwortliche Hand ging — und die vier früheren Horrorspiele zeigen einen konsistenten handgebauten Stil, der auf dieses Release zuläuft.', 'Die FMV-Sequenzen machen den Handmade-Fall sichtbar: Die Testberichterstattung lobt das VHS-artige Full-Motion-Video als Präsentationshöhepunkt. Diese Sequenzen sind inszeniert, gespielt und im Grindhouse-Register des Spiels geschnitten — mit derselben Low-Poly-PSX-Ästhetik wie der Rest des Builds.'] },
      { title: 'KI-Status in drei Schritten prüfen', paragraphs: [], bullets: ['Lies die Featureliste der Store-Seite: Steam verlangt KI-Inhaltsangaben, wo sie zutreffen — die Seite dieses Spiels stattdessen mit Handmade-Produktion; die Angabensektion ist das schnellste offizielle Signal', 'Prüfe Credits und Cast: Namentliche Sprecher, ein veröffentlichtes Cast-Poster und öffentliche Creator-Kanäle — wie das Zehn-Personen-Poster dieses Spiels — sind menschliche Fingerabdrücke', 'Schau das echte Material: Stil-Konsistenz über den Katalog eines Solo-Entwicklers ist schwer zu faken — vergleiche die FMV-Szenen mit den früheren Spielen und Dev-Logs'] },
      { title: 'Spielt es sich deshalb anders?', paragraphs: ['Für The Skin Stapler ist die Handmade-Frage vor allem eine Werte-Frage, und die Antwort stützt den eigenen Pitch: Grindhouse-Comedy eines Solo-Entwicklers mit Creator-Cast ist genau die Produktion, die Spieler meinen, wenn sie nach menschgemachten Spielen fragen. Die Start-Stimmung von rund 90 % Positiv aus etwa 340 Rezensionen legt nahe, dass das Publikum es genauso las.', 'Die ehrlichen Grenzen: Abspann-Rollen jenseits des Cast-Posters wurden nie vollständig erfasst, und kein offizielles Dokument listet jedes während der Entwicklung genutzte Werkzeug. Was der öffentliche Beleg trägt, ist die Aussage der Store-Seite selbst — handgemachter Horror, keine Abkürzungen — angewandt auf Grafik, Vertonung und Story.'] }
    ],
    faq: [
      { question: 'Nutzt The Skin Stapler KI-generierte Grafik?', answer: 'Nein. Die offizielle Store-Seite vermarktet das Spiel als handmade horror with no shortcuts, und die Low-Poly-Grafik samt FMV-Sequenzen passt zum handgebauten Katalog eines Solo-Entwicklers. Kein offizieller Kanal wirbt mit KI-Grafik für diesen Titel.' },
      { question: 'Sind die Stimmen KI?', answer: 'Nein. Zehn namentliche Sprecher stehen auf dem offiziellen Cast-Poster, Steam listet volle englische Sprachausgabe, und die Creator bewerben ihre Rollen auf eigenen Kanälen — der Cast-Ratgeber listet alle.' },
      { question: 'Wer hat The Skin Stapler gemacht?', answer: 'Der Solo-Entwickler Tainted Pact, veröffentlicht von Assemble Entertainment. Erschienen am 6. August 2026 für Windows-PC.' },
      { question: 'Warum sagt die Store-Seite „handmade horror“?', answer: 'Das ist die Produktions-Aussage des Entwicklers — „A HANDCRAFTED HORROR EXPERIENCE — handmade horror, with no shortcuts“ — und sie passt zur öffentlichen Entwicklungsgeschichte und zum Creator-Cast.' },
      { question: 'Ist das Schreiben KI-generiert?', answer: 'Nein. Die Dialoge tragen die Stimmen der Cast-Poster-Performer und den Grindhouse-Humor des Entwicklers über eine einzelne, autorgesetzte Storyline; keine offizielle Quelle beschreibt KI-Schreibwerkzeuge.' }
    ],
    sources: sourceSets['ai-generated']
  },
  developer: {
    id: 'developer', keyword: 'The Skin Stapler Entwickler',
    title: 'The Skin Stapler Entwickler: Tainted Pact und Assemble Entertainment',
    description: 'Wer hinter The Skin Stapler steckt: Solo-Entwickler Tainted Pact aus den USA, Publisher Assemble Entertainment, der Back-Katalog und die offiziellen Kanäle.',
    eyebrow: 'Studio und Publisher',
    directAnswer: 'The Skin Stapler stammt von Tainted Pact, einem Solo-Entwickler aus den USA, und wurde von Assemble Entertainment veröffentlicht — dem deutschen Publisher hinter Sticky Business, Roadwarden und der Endzone-Reihe. Das Spiel erschien am 6. August 2026 für Windows-PC zum Preis von 14,99 Euro auf Steam und ist der fünfte Horrortitel des Studios.',
    date: '2026-09-03',
    sections: [
      { title: 'Studio und Publisher im Überblick', paragraphs: ['Die Publisher-Seite ist für ein Solo-Horrorprojekt ungewöhnlich etabliert — diese Fakten sind die wichtigsten:'], bullets: ['Entwickler: Tainted Pact — Solo-Entwickler, USA (Kalifornien)', 'Publisher: Assemble Entertainment — Deutschland, mehr als 50 veröffentlichte Spiele', 'Start: 6. August 2026, Windows-PC', 'Startpreis: 14,99 Euro auf Steam', 'Back-Katalog: Suffer the Night, Terror at Oakheart, Massacre at the Mirage, Flesh Made Fear', 'Offizielle Kanäle: itch.io (taintedpact88) und YouTube (@TaintedPactGames)'] },
      { title: 'Wer ist Tainted Pact?', paragraphs: ['Tainted Pact ist das Solo-Studio hinter fünf Horrorspielen, und die Release-Ankündigung des Publishers beschreibt die Entwicklung als Ein-Personen-Betrieb in Kalifornien. Das Studio baut bewusst nischige Grindhouse-Horror: kurze Laufzeiten, PSX-artige Low-Poly-Optik, vollständig vertonte Creator-Besetzungen und auf Witze getrimmte Slasher-Skripte.', 'Die öffentliche Fußspur ist klein: ein itch.io-Konto unter dem Namen taintedpact88 und ein YouTube-Kanal @TaintedPactGames, der im Dezember 2025 zwei Dev-Logs zu The Skin Stapler veröffentlichte — Dev Log #1 am 1. Dezember, Dev Log #2 am 2. Dezember. Gründernamen oder persönliche Details veröffentlicht das Studio nicht; seine öffentliche Identität ist die Marke, die Spiele und die Creator-Kooperationen.'] },
      { title: 'Die vier Spiele vor The Skin Stapler', paragraphs: ['Der Back-Katalog ist sowohl über die Ankündigung des Publishers als auch über den GOG-Katalog bestätigt:'], bullets: ['Suffer the Night — das Analog-Horror-Debüt um einen verfluchten Retro-Computer', 'Terror at Oakheart — ein Camp-Slasher mit derselben stilisierten Gewalt', 'Massacre at the Mirage — ein Hotel-Slasher mit szenenweisem Tempo', 'Flesh Made Fear — der direkte Vorgänger: eine Serienkiller-Story mit vertonten Szenen und Grindhouse-Kante'] },
      { title: 'Der Publisher: Assemble Entertainment', paragraphs: ['Assemble Entertainment ist ein deutscher Publisher, gegründet 2016, mit mehr als 50 veröffentlichten Spielen. Die Bandbreite reicht über Horror hinaus: Sticky Business ist ein gemütlicher Überraschungshit, Roadwarden ein kritisch gelobtes Narrative-RPG, und die Endzone-Reihe bildet das Survival-Strategy-Fundament. The Skin Stapler liegt in dessen Grindhouse-Spur.', 'Für Spieler ist der Publisher praktisch sichtbar: der Launch-Pressepush, die Tiny-Teams-Steam-Platzierung im Demo-Fenster und die Store-Präsenz auf Steam und GOG laufen über Assemble. Die Store-Seite trägt die Copyright-Zeile Assemble Entertainment GmbH, und die Publisher-Ankündigung ist die Quelle der Startfakten oben.'] },
      { title: 'Das Creator-Cast-Produktionsmodell', paragraphs: ['Der Publisher beschreibt das Spiel als mit Unterstützung beliebter Content-Creators gebaut, und das Cast-Poster belegt es mit zehn namentlichen Sprechern: RJ Green, Daniel Suraci, HexyIRL, Layna Lazar, Runebee, Luna Arcana, Blairvira, FeFe, Scaroline und KingWoolz. Mehrere Figuren sind nach den Creators modelliert und von ihnen gesprochen — Scaroline und Underworld VHS sind das klarste Beispiel.', 'Dieses Modell ist die Signatur des Studios: Es macht aus einem Solo-Projekt einen kollaborativen Launch, bringt über die Creator-Kanäle ein eingebautes Publikum mit und hält die vollständig vertonte Präsentation für ein 2,5-Stunden-Spiel bezahlbar.'] },
      { title: 'Dem Entwickler in drei Schritten folgen', paragraphs: [], bullets: ['Wunschliste und Steam-Follow: Die Store-Seite ist der Hauptkanal für Patches und Ankündigungen; die Seite des Spiels verlinkt die anderen Arbeiten des Studios direkt', 'Prüf den YouTube-Kanal: @TaintedPactGames ist die Heimat der Dev-Logs — allein zwei im Dezember 2025 — und der wahrscheinlichste Ort für künftige Projektankündigungen', 'Beobachte das itch.io-Konto: Die taintedpact88-Seite hostet die unabhängige Präsenz des Studios und dokumentiert die Projektspur bis zu The Skin Stapler'] }
    ],
    faq: [
      { question: 'Wer hat The Skin Stapler gemacht?', answer: 'Der Solo-Entwickler Tainted Pact aus den USA, veröffentlicht von Assemble Entertainment aus Deutschland.' },
      { question: 'Welche Spiele hat Tainted Pact gemacht?', answer: 'Vier frühere Horrortitel — Suffer the Night, Terror at Oakheart, Massacre at the Mirage und Flesh Made Fear — plus The Skin Stapler als fünftes.' },
      { question: 'Ist Tainted Pact eine Ein-Personen-Firma?', answer: 'Ja — die Release-Ankündigung des Publishers beschreibt einen Solo-Entwickler, und das handgemachte Produktionsprofil passt zu einem Ein-Personen-Studio mit Creator-Cast.' },
      { question: 'Wer veröffentlicht The Skin Stapler?', answer: 'Assemble Entertainment, ein deutscher Publisher aus dem Jahr 2016 mit über 50 Spielen, darunter Sticky Business, Roadwarden und die Endzone-Reihe.' },
      { question: 'Wo kann ich dem Studio folgen?', answer: 'Über Steam-Wunschlisten, den @TaintedPactGames-YouTube-Kanal und die taintedpact88-Seite auf itch.io — das sind die offiziellen Kanäle.' },
      { question: 'Wann ist das Spiel erschienen?', answer: 'Am 6. August 2026 auf Steam und GOG für Windows-PC zum Preis von 14,99 Euro — der Release-Date-Ratgeber hat die komplette Launch-Timeline.' }
    ],
    sources: sourceSets.developer
  },
  'janker-edition': {
    id: 'janker-edition', keyword: 'The Skin Stapler Skin Jankers',
    title: 'The Skin Stapler: The Skin Jankers — kein „Janker Edition“',
    description: 'The Skin Janker Edition existiert nicht: Der echte Name ist The Skin Jankers, ein Kosmetik-DLC mit drei Superhelden-Skins — hier die Kaufstruktur.',
    eyebrow: 'Produkt-Check',
    directAnswer: 'Ein Produkt namens The Skin Janker Edition gibt es nicht — der Name ist eine verbreitete Falschlesung von The Skin Jankers, dem Kosmetik-DLC zu The Skin Stapler. Das echte Produkt ist The Skin Stapler: The Skin Jankers, ein DLC zum Release am 6. August 2026 mit drei Superhelden-inspirierten kosmetischen Skins. Eine Special Edition, Sammlerversion oder Edition-SKU des Basisspiels gibt es auf Steam und GOG nicht.',
    date: '2026-09-03',
    sections: [
      { title: 'Die echte Produktstruktur', paragraphs: ['Drei Store-Einträge, keine Editionen. Wenn du nach einer Janker Edition gesucht hast, ist die zweite Zeile das Produkt, das du eigentlich willst:'], bullets: ['The Skin Stapler (Basisspiel): das volle 14-Kapitel-Spiel, App 4310610 — ohne Editionszusatz, auf Steam und GOG', 'The Skin Jankers DLC: drei Superhelden-inspirierte Kosmetik-Skins, Steam-App 4919860, erschienen 6. August 2026 — separates DLC auf Steam, im GOG-Kauf enthalten', 'Soundtrack-DLC: der Sound des Spiels, Steam-App 4919810, erschienen 6. August 2026 — separates DLC auf Steam'] },
      { title: 'Was das Skin-Jankers-DLC enthält', paragraphs: ['GOGs offizielle Beschreibung ist konkret: Das Skin-Jankers-DLC liefert drei glorreich absurde, Superhelden-inspirierte kosmetische Skins für die Hauptfiguren des Spiels. Die Formulierung nennt das Thema (Superhelden-Parodie), die Anzahl (drei) und den Umfang (nur kosmetisch) — nichts im DLC ändert Gameplay, Kapitel oder Story.', 'Die drei einzelnen Skin-Designs werden auf keiner der Store-Seiten namentlich genannt — jede konkret zitierte Skin-Bezeichnung geht über die offizielle Beschreibung hinaus. Auch der eigenständige Steam-Preis des DLCs ist nicht Teil der geprüften Angaben: Der aktuelle Regionalpreis steht auf der Store-Seite des DLCs.'] },
      { title: 'Edition vs. DLC: warum die Verwechslung passiert', paragraphs: ['Die Falschlesung folgt einem bekannten Muster. Horrorspiele verkaufen oft Special Editions, und Jankers in der Mehrzahl sieht in einer Suchleiste wie ein Editionsname aus. Dazu kommt das Vokabular des Spiels selbst: Die Community sagt jank liebevoll, und ein Steam-Erfolg heißt buchstäblich Jank Ya Later! — eine fiktive Janker Edition klingt plausibel genug, dass Suchmaschinen sie vorschlagen.', 'Die Store-Struktur entscheidet: Eine echte Edition wäre eine separate Bundle-SKU auf Steam, und der Store von The Skin Stapler listet nur das Basisspiel plus zwei DLCs. GOG geht weiter und packt die Skin-Jankers-Inhalte in den Basiskauf — was ein editions-gebundenes Produkt nicht täte.'] },
      { title: 'So kaufst du das Richtige', paragraphs: [], bullets: ['Entscheide dich zuerst für den Store: GOG enthält die drei Skins mit dem Basisspiel; Steam verkauft Basisspiel und Skin-Jankers-DLC getrennt — für die Skins auf Steam das DLC explizit dazunehmen', 'Prüf die DLC-Seite vor dem Kauf: The Skin Stapler: The Skin Jankers ist App 4919860 auf Steam — den Titel exakt gegenprüfen, weil das Soundtrack-DLC (App 4919810) daneben liegt', 'Ignoriere alles mit Edition im Namen: Keine Janker Edition, Deluxe Edition oder Collector’s Edition existiert — Seiten oder Key-Shops mit diesen Namen beschriften das Basisspiel falsch oder verkaufen das DLC unter erfundenem Banner'] },
      { title: 'Was die Skins im Spiel bewirken', paragraphs: ['Kosmetik-DLC in einem 2,5-Stunden-Story-Spiel tut genau das Angekündigte: Es tauscht das Aussehen der Hauptfiguren, während jede Zeile, jedes Kapitel und jeder Erfolg identisch bleibt. Die 16 Erfolge des Basisspiels, die einzelne Storyline und die Kapitelstruktur bleiben von DLC-Besitz unberührt — der Erfolgs-Ratgeber listet das komplette Set, keiner der Einträge verlangt die Skins.', 'Das Superhelden-Parodie-Thema passt ins Grindhouse-Comedy-Register des Spiels: Das Marketing des Publishers verspricht einen letzten Lacher vor dem Tod, und die Carrion-City-Besetzung als glorreich absurde Superhelden einzukleiden ist eine Verlängerung desselben Witzes, kein neuer Modus.'] }
    ],
    faq: [
      { question: 'Gibt es eine The-Skin-Janker-Edition des Spiels?', answer: 'Nein. Der Name vermischt The Skin Jankers — das Drei-Skins-Kosmetik-DLC — mit einer Edition des Basisspiels. Eine Edition-SKU existiert auf Steam und GOG nicht.' },
      { question: 'Was ist das Skin-Jankers-DLC?', answer: 'Drei Superhelden-inspirierte Kosmetik-Skins für die Hauptfiguren, erschienen am 6. August 2026. Es verkauft sich auf Steam separat und ist in der GOG-Fassung enthalten.' },
      { question: 'Was kostet das DLC?', answer: 'Der Eigenpreis ist nicht Teil der geprüften Angaben — der aktuelle Regionalpreis steht auf der Steam-Seite des DLCs.' },
      { question: 'Ändert das DLC Story oder Kapitel?', answer: 'Nein. Die Skins sind rein kosmetisch; die 14-Kapitel-Story und alle 16 Erfolge sind mit und ohne DLC identisch.' },
      { question: 'Gibt es das DLC auf GOG?', answer: 'Ja — GOG bündelt die Skin-Jankers-Skins mit dem Basisspielkauf, GOG-Käufer bekommen die Skins ohne separaten Kauf.' },
      { question: 'Was ist das andere DLC?', answer: 'Der Soundtrack, erschienen am selben Tag wie Spiel und Skin-Pack. Er enthält den Synth-Score, den Tester als Kern der Präsentation hervorheben.' }
    ],
    sources: sourceSets['janker-edition']
  },
  'turkish-patch': {
    id: 'turkish-patch', keyword: 'The Skin Stapler Türkçe',
    title: 'The Skin Stapler Türkçe: Kein offizielles türkisches Patch',
    description: 'The Skin Stapler auf Türkisch: Steam und GOG listen nur Englisch — Stand September 2026 gibt es kein offizielles Türkçe yama und keine Ankündigung.',
    eyebrow: 'Sprachstatus',
    directAnswer: 'The Skin Stapler hat keine türkische Sprachoption. Die Steam-Seiten der Vollversion (App 4310610) und der Demo (App 4343530) listen Englisch als einzige Sprache, und das GOG-Angebot passt dazu: englische Oberfläche, englische Untertitel, englische Vertonung. Weil das Spiel vollständig gesprochen ist, würde eine türkische Fassung eine komplette Synchronisation bedeuten — und weder Tainted Pact noch Assemble Entertainment haben bis September 2026 eine türkische Lokalisierung oder ein offizielles Türkçe yama angekündigt.',
    date: '2026-09-03',
    sections: [
      { title: 'Sprachstatus auf einen Blick', paragraphs: ['Drei Store-Einträge, eine Sprache. Jede Spalte stammt direkt aus den offiziellen Sprachlisten der Stores — der einzigen verbindlichen Quelle dafür, was eine Fassung unterstützt:'], bullets: ['Steam — Vollversion (App 4310610): Oberfläche Englisch, Untertitel Englisch, Vertonung Englisch, offizielles türkisches Patch: keines angekündigt', 'Steam — Demo (App 4343530): dieselbe englische Tabelle wie die Vollversion', 'GOG — Vollversion: derselbe nur-englische Build', 'Demo-Tipp: Die Demo spiegelt die Vollversion — ein Download deckt keine versteckte Türkisch-Unterstützung auf'] },
      { title: 'Warum es kein offizielles türkisches Patch gibt', paragraphs: ['The Skin Stapler ist ein vollständig vertontes FMV-Horrorspiel. Jede Dialogzeile ist aufgezeichnetes Audio, gesprochen von zehn namentlichen Sprechern — Lokalisierung ist deshalb kein Texttausch: Eine türkische Fassung bräuchte übersetzte Untertitel und einen kompletten Dub für jede Szene. Das ist eine große Anforderung an einen Solo-Entwickler: The Skin Stapler ist Tainted Pacts fünfter Horrortitel, in etwa einem Jahr gebaut und von Assemble Entertainment für 14,99 Euro veröffentlicht.', 'Die Kombination aus kurzer Laufzeit, vollständigem Sprecher-Cast und Ein-Personen-Produktion erklärt, warum der Start nur englisch kam. Lokalisierungsankündigungen bei Spielen dieser Größe erscheinen, wenn überhaupt, nach dem Start in Store-News oder Patch-Notes. Eine solche Ankündigung für Türkisch existiert bis September 2026 nicht, und nichts in den Store-Listen deutet auf eine Vorbereitung.'] },
      { title: 'Community-Türkçe-Yamas', paragraphs: ['Dieser Ratgeber verfolgt nur offizielle Kanäle und verlinkt keine Drittanbieter-Downloads. Ob ein Fan-Türkçe-yama existiert, ist in keinem offiziellen Kanal dokumentiert: Das Spiel hat keine Workshop-Seite, keine offizielle Modding-Unterstützung und keine Entwickler-Genehmigung für Fremdsprachendateien.', 'Wenn du trotzdem suchst, wäge die üblichen Risiken inoffizieller Patches für ein Store-Spiel ab. Inoffizielle Dateien können bei Spiel-Updates brechen, werden weder von Steam noch von GOG geprüft, und eine schlechte Datei kann über den Spielordner hinausreichen. Das beweist nicht, dass ein bestimmter Patch nicht funktioniert — aber jeder Download-Link, Forumsbeitrag und jede Videobeschreibung gehört kritisch geprüft, bevor du weißt, was die Datei wirklich verändert.'] },
      { title: 'Türkische Unterstützung selbst prüfen', paragraphs: [], bullets: ['Öffne die Steam-Sprachtabelle: Scrolle auf der Vollversions-Seite zur Sprachsektion und lies die Spalten Oberfläche, Untertitel und Vertonung für Türkisch; die Demo-Seite (App 4343530) zeigt dieselbe Tabelle', 'Prüf den News-Feed: Im Steam-News-Bereich erscheinen Lokalisierungs- oder Patch-Ankündigungen von Tainted Pact oder Assemble Entertainment — dort würde ein türkisches Patch zuerst angekündigt', 'Gegenprüfe GOG und die Entwicklerseite: Die GOG-Listung und die itch.io-Seite des Entwicklers wiederholen die offizielle Sprachunterstützung — ein Widerspruch zwischen den Stores würde dort auffallen'] },
      { title: 'Auf Englisch spielen, während du wartest', paragraphs: ['Das Englisch des Spiels ist keine dichte Prosa — es ist Grindhouse-Dialog um kurze Szenen, klare Bildschirmziele und VHS-artige FMV-Clips, und die echten Rätsel (wie der 1979er Bilderrahmen-Code) sind im Rätsel-Ratgeber dokumentiert. Wenn Englisch deine Zweitsprache ist, ist die kostenlose Steam-Demo der günstigste Test: Sie packt drei spielbare Abschnitte — Polizeiwache, Quick Fix und Gutters End — in 30 bis 45 Minuten, sodass du die Sprachhürde vor 14,99 Euro bewerten kannst.', 'Der eine Trade-off vorab: Die Story läuft fast vollständig über gesprochene Dialoge und FMV-Sequenzen, nicht über Text. Untertitel existieren, aber sie transkribieren die englischen Performances — dahinter steht kein Sprachschalter zum Umschalten.'] }
    ],
    faq: [
      { question: 'Gibt es ein türkisches Patch für The Skin Stapler?', answer: 'Nein, bis September 2026 keines. Steam und GOG listen für Vollversion und Demo nur Englisch, und keine türkische Lokalisierung ist angekündigt.' },
      { question: 'Kommt Türkisch später?', answer: 'Nichts ist angekündigt. Falls sich das ändert, erscheint es zuerst im Steam-News-Feed und auf den Entwicklerkanälen — nicht still in einem zufälligen Update.' },
      { question: 'Ist die Demo auf Türkisch?', answer: 'Nein. Die Demo (App 4343530) listet dieselbe einzige Sprache wie die Vollversion: Englisch für Oberfläche, Untertitel und Audio.' },
      { question: 'Hat die GOG-Fassung türkische Untertitel?', answer: 'Nein. GOG liefert denselben nur-englischen Build wie Steam, ohne Sprachschalter jenseits von Englisch.' },
      { question: 'Warum ist ein türkischer Dub so unwahrscheinlich?', answer: 'Das Spiel ist vollständig vertont. Ein Dub bedeutet, jede Zeile mit einer türkischen Besetzung neu aufzunehmen — ein weit größerer Aufwand als Untertitel-Übersetzung, und noch nicht mal Untertitel sind angekündigt.' }
    ],
    sources: sourceSets['turkish-patch']
  },
  'korean-patch': {
    id: 'korean-patch', keyword: 'The Skin Stapler Koreanisch',
    title: 'The Skin Stapler Koreanisch: Kein offizielles koreanisches Patch',
    description: 'The Skin Stapler auf Koreanisch: Steam und GOG listen nur Englisch — Stand September 2026 existiert kein offizielles koreanisches Patch und keine Ankündigung.',
    eyebrow: 'Sprachstatus',
    directAnswer: 'The Skin Stapler hat keine koreanische Sprachoption. Die Steam-Seiten der Vollversion (App 4310610) und der Demo (App 4343530) listen Englisch als einzige Sprache — Oberfläche, Untertitel und Vertonung —, und der GOG-Build ist dasselbe einsprachige Paket. Wer über eine koreanische Suche nach einem The Skin Stapler 패치 oder einer 한국어 번역 ankommt, erhält bis September 2026 genau diese Antwort: Es gibt keine offizielle koreanische Fassung, und keine wurde angekündigt.',
    date: '2026-09-03',
    sections: [
      { title: 'Sprachstatus auf einen Blick', paragraphs: ['Drei Store-Einträge, eine Sprache. Jede Zeile stammt direkt aus den offiziellen Sprachtabellen der Stores — der einzigen verbindlichen Quelle dafür, was eine Fassung unterstützt:'], bullets: ['Steam — Vollversion (App 4310610): Oberfläche Englisch, Untertitel Englisch, Vertonung Englisch, offizielles koreanisches Patch: keines angekündigt', 'Steam — Demo (App 4343530): dieselbe englische Tabelle wie die Vollversion', 'GOG — Vollversion: derselbe nur-englische Build', 'Demo-Hinweis: Die Demo spiegelt die Vollversion — der kostenlose Download enthält keine versteckte Koreanisch-Unterstützung'] },
      { title: 'Warum es kein offizielles koreanisches Patch gibt', paragraphs: ['The Skin Stapler ist ein vollständig vertontes FMV-Horrorspiel mit zehn namentlichen Sprechern auf dem Cast-Plakat. Eine koreanische Fassung bräuchte beides gleichzeitig: übersetzte Untertitel für jede Dialogzeile und einen kompletten koreanischen Dub über die VHS-artigen Videosequenzen. Das ist eine schwere Lokalisierungslast für einen Solo-Entwickler — Tainted Pact baute das Spiel in etwa einem Jahr, und Publisher Assemble Entertainment startete es am 6. August 2026 für 14,99 Euro mit rein englischer Store-Präsenz.', 'Kurze, dialoglastige Horrorspiele kleiner Teams starten routinemäßig nur auf Englisch, und koreanische Unterstützung erscheint, wenn überhaupt, als Ankündigung nach dem Start im Store-News-Feed. Eine solche Ankündigung existiert für dieses Spiel bis September 2026 nicht.'] },
      { title: 'Die koreanischen Suchbegriffe, erklärt', paragraphs: ['Zwei koreanische Anfragen dominieren das Thema. 패치 heißt Patch — wer einen The Skin Stapler 패치 sucht, will einen Sprachpatch oder eine Fanübersetzung. 번역 heißt Übersetzung, meist kombiniert mit 한국어 (Koreanisch), um nach einer lokalisierten Fassung zu fragen. Keine der beiden Suchen liefert ein offizielles Ergebnis, weil keines der beiden Produkte existiert: Die Store-Einträge sind die maßgebliche Aufzeichnung, und sie listen eine Sprache.', 'Vorsicht bei dem, was diese Suchen sonst auftun: Fan-Patch-Seiten, neu hochgeladene Builds und Videobeschreibungs-Links sind Drittanbieter-Dateien ohne Prüfung durch Steam oder GOG. Dieser Ratgeber verlinkt keine davon.'] },
      { title: 'Community-Koreanisch-Patches', paragraphs: ['Ob eine von Fans erstellte koreanische Übersetzung existiert, ist in keinem offiziellen Kanal dokumentiert — das Spiel hat keine Workshop-Unterstützung, keine offiziellen Modding-Werkzeuge und keine Entwickler-Genehmigung für Fremdsprachendateien. Wer trotzdem eine prüft, trägt die üblichen Risiken inoffizieller Patches: Sie können bei Spiel-Updates brechen, Dateien weit über den Spielordner hinaus verändern und kollidieren mit Nutzungsbedingungen, die inoffizielle Modifikationen nicht immer respektieren.'] },
      { title: 'Koreanische Unterstützung selbst prüfen', paragraphs: [], bullets: ['Lies die Steam-Sprachtabelle: Auf der Vollversions-Seite (App 4310610) zur Sprachliste scrollen und die Koreanisch-Zeile über Oberfläche, Untertitel und Vertonung prüfen; die Demo-Seite zeigt dieselbe Tabelle', 'Beobachte den News-Feed: Lokalisierungsnews erscheinen zuerst im Steam-News-Bereich von Tainted Pact oder Assemble Entertainment — das ist der Kanal, den du im Auge behältst', 'Gegenprüfe GOG: Die GOG-Listung spiegelt die offizielle Sprachunterstützung, eine künftige Koreanisch-Ankündigung würde auch dort auftauchen'] },
      { title: 'Auf Englisch spielen, während du wartest', paragraphs: ['Das Englisch des Spiels ist Grindhouse-Dialog, keine dichte Prosa: kurze Szenen, knappe Zeilen und klare Bildschirmziele tragen die Route. Die echten Rätsel — der 1979er Bilderrahmen-Code, die Flesh-Pit-Fleischwaage, die beschädigten Kassetten — sind Schritt für Schritt dokumentiert und nehmen den Ermittlungskapiteln den größten Teil des Sprachrisikos.', 'Wer die Sprachhürde kostenlos testen will: Die Demo deckt in 30 bis 45 Minuten genau die Formate ab, die dir in der Vollversion begegnen — Interview-Dialoge, Servierarbeit und eine scriptete Verfolgungsjagd. Die Story selbst läuft über gesprochene englische Performances und FMV-Clips; Untertitel allein tragen einen Nicht-Englisch-Durchlauf nicht.'] }
    ],
    faq: [
      { question: 'Gibt es ein koreanisches Patch für The Skin Stapler?', answer: 'Kein offizielles, Stand September 2026. Steam und GOG listen nur Englisch, eine koreanische Lokalisierung ist nicht angekündigt.' },
      { question: 'Kommen koreanische Untertitel später?', answer: 'Nichts ist angekündigt. Künftige Unterstützung würde zuerst im Steam-News-Feed und auf den Entwicklerkanälen erscheinen.' },
      { question: 'Ist die Demo auf Koreanisch?', answer: 'Nein. Die Demo (App 4343530) liefert dieselbe nur-englische Sprachtabelle wie die Vollversion.' },
      { question: 'Unterscheiden sich Steam und GOG bei der Sprache?', answer: 'Nein. Beide Stores verteilen denselben nur-englischen Build für Oberfläche, Untertitel und Audio.' },
      { question: 'Warum ist ein koreanischer Dub unwahrscheinlich?', answer: 'Das Spiel ist mit zehn Sprechern vollständig vertont. Ein Dub bedeutet, das komplette Spiel neu aufzunehmen — ein weit größerer Aufwand als Untertitel-Übersetzung, und nicht einmal Untertitel sind angekündigt.' }
    ],
    sources: sourceSets['korean-patch']
  },
  'press-kit': {
    id: 'press-kit', keyword: 'The Skin Stapler Press Kit',
    title: 'The Skin Stapler Press Kit: Offizielle Assets und Fundorte',
    description: 'Kein offizielles Press Kit für The Skin Stapler — stattdessen Launch-Pressemitteilung, Trailer und Store-Galerien. Alle offiziellen Assets im Überblick.',
    eyebrow: 'Presse und Creator',
    directAnswer: 'The Skin Stapler hat kein offizielles Press Kit. Stand September 2026 haben Tainted Pact und Assemble Entertainment kein herunterladbares Presse-ZIP, kein Logo-Bündel und kein Login-Pressportal veröffentlicht. Was existiert, ist ein Satz öffentlicher, offizieller Assets, die abdecken, was Redakteure und Streamer praktisch brauchen: die Launch-Pressemitteilung auf Games Press, der offizielle Trailer vom 27. Januar 2026 und die vollständigen Screenshot-Galerien auf Steam und GOG.',
    date: '2026-09-03',
    sections: [
      { title: 'Was es statt eines Press Kits gibt', paragraphs: ['Diese Kombination ist das praktische Press Kit. Alles auf der Liste ist offiziell, ohne Zugangsdaten öffentlich zugänglich und sicher zu zitieren oder einzubetten — genau das, wofür ein Press Kit da ist:'], bullets: ['Launch-Pressemitteilung: Games Press, Schlagzeile "The Skin Stapler Is Ready for Its Next Victim" (6. August 2026) — Preis, Studio-Fakten, Demo-Stimmung, zitierfähige Texte', 'Offizieller Trailer: YouTube, veröffentlicht am 27. Januar 2026 (Video-ID 5tEJiy8FJbY) — original einbettbar', 'Steam-Galerie: Store-Seite (App 4310610) — Screenshots, Boxart, Store-Text', 'GOG-Galerie: dieselben Screenshots und derselbe Store-Text', 'Entwickler-Storefront: die itch.io-Seite von Tainted Pact'] },
      { title: 'Was die Launch-Mitteilung bestätigt', paragraphs: ['Die Mitteilung vom 6. August 2026 auf Games Press ist das nützlichste Einzeldokument des Sets, weil sie die Fakten bündelt, die die meisten Berichte brauchen: 14,99 Euro auf dem PC; entwickelt vom Solo-Entwickler Tainted Pact, veröffentlicht von Assemble Entertainment unter dem Tiny-Teams-Label von Yogscast; The Skin Stapler als fünfter Horrortitel des Studios; die kostenlose Steam-Demo mit Very-Positive-Bewertung zum Start; CaseOh und MoistCr1TiKaL, die das Spiel vor Release gespielt haben.', 'Die beiden offiziellen Selbstbeschreibungen stammen aus derselben Mitteilung. Die Logline: "Enter Carrion City and hunt a serial killer through a short, story-driven horror nightmare." Die Tagline: "NO ONE LEAVES CARRION CITY IN ONE PIECE." Wer über das Spiel schreibt, greift auf diese zwei Zeilen zurück, weil sie aus dem Publisher-Text stammen statt aus einer Nacherzählung — und die Mitteilung stellt sie neben die konkreten Zahlen, sodass kurze News und lange Tests gleichermaßen versorgt sind.'] },
      { title: 'Warum ein kleines Spiel aufs Press Kit verzichtet', paragraphs: ['Hier fehlt nichts — so erscheinen kleine Horrorspiele üblicherweise. Ein Solo-Entwickler betreibt kein Presseportal, und die Launch-Mitteilung des Publishers erledigt dieselbe Arbeit: Fakten, Zitate und Positionierung gehen in einem Durchgang an die Redaktionen. Die Store-Galerien sind dann die permanente, immer aktuelle Heimat der Bildassets — was ein statisches ZIP nie ist.', 'Auf der Creator-Seite gilt dasselbe. Die im Release genannten Durchläufe von CaseOh und MoistCr1TiKaL sind öffentliche Videos, und die Very-Positive-Bewertung der Demo sieht jeder auf der Store-Seite — zwei Reputationssignale, die sich ohne jeglichen Presse-Zugang zitieren lassen.'] },
      { title: 'Assets in drei Schritten sammeln', paragraphs: [], bullets: ['Zuerst die Store-Galerien: Die Steam-Seite (App 4310610) hält den aktuellen Screenshot-Satz und das Boxart; die GOG-Listung wiederholt dasselbe Material und gibt dir eine zweite offizielle Quelle', 'Trailer original einbetten: Der YouTube-Trailer vom 27. Januar 2026 (Video-ID 5tEJiy8FJbY) ist der offizielle Trailer — das Original-Upload einbetten, nicht einen Reupload, damit Credits und Aufrufe beim Publisher bleiben', 'Fakten aus dem Release zitieren: Die Games-Press-Mitteilung liefert Preis, Team-Credits, Demo-Bewertung und beide offiziellen Taglines ohne zwischengeschaltete Nacherzählung'] },
      { title: 'Presse-Anfragen ohne Portal', paragraphs: ['Einen Pressekontakt für das Spiel selbst gibt es nicht. Assemble Entertainment ist der Publisher of Record — Pressefragen laufen deshalb am sinnvollsten über die Publisher-Website. Für alles Sichtbare reicht das öffentliche Set: Galerie, Trailer, Mitteilung. Ein separates Credentials-System existiert nicht und wird nicht verlangt; die genannten Assets decken Reviews, News-Posts und die Stream-Vorbereitung vollständig ab.'] }
    ],
    faq: [
      { question: 'Gibt es ein offizielles Press Kit für The Skin Stapler?', answer: 'Nein. Stand September 2026 wurde kein Presse-ZIP, kein Logo-Bündel und kein Pressportal für das Spiel veröffentlicht.' },
      { question: 'Woher bekomme ich offizielle Screenshots?', answer: 'Aus den Steam- und GOG-Store-Galerien. Sie führen dieselben offiziellen Screenshots wie der Publisher und bleiben aktuell.' },
      { question: 'Wen kontaktiere ich für Presse-Zugang?', answer: 'Ein Pressekontakt ist für das Spiel nicht veröffentlicht. Assemble Entertainment ist der Publisher of Record — die Publisher-Website ist der sinnvolle Weg für Pressefragen.' },
      { question: 'Darf ich den Trailer in meiner Berichterstattung nutzen?', answer: 'Ja. Der offizielle Trailer (YouTube-ID 5tEJiy8FJbY) ist öffentlich und zum Teilen gemacht — das Original-Upload einbetten, keinen Reupload.' },
      { question: 'Was sind die offiziellen Taglines des Spiels?', answer: 'Die Logline ist "Enter Carrion City and hunt a serial killer through a short, story-driven horror nightmare", die Tagline "NO ONE LEAVES CARRION CITY IN ONE PIECE." Beide stammen aus der Launch-Mitteilung.' }
    ],
    sources: sourceSets['press-kit']
  },
  'final-aftermath': {
    id: 'final-aftermath', keyword: 'The Skin Stapler Final Aftermath',
    title: 'The Skin Stapler Final Aftermath: Position, Erfolg und Endspiel',
    description: 'The Final Aftermath erklärt: das fünfte Aftermath-Zwischenspiel zwischen Lazar’s Blood Bank und Closing In, mit dem Erfolg "Nine, Ten, Never Jank Again.".',
    eyebrow: 'Kapitelguide',
    directAnswer: 'The Final Aftermath ist das fünfte und letzte Aftermath-Zwischenspiel von The Skin Stapler — das Kapitel, das die Opfergeschichten abschließt, bevor das zweiteilige Endspiel beginnt. In der Route liegt es nach Lazar’s Blood Bank, die in einem Referenzdurchlauf bei 01:58:34 endet, und vor Closing In, das bei 02:18:29 öffnet. Der Abschluss schaltet den Steam-Erfolg "Nine, Ten, Never Jank Again." frei und vollendet die 14-Kapitel-Rechnung: neun Schauplatz-Kapitel, vier nummerierte Aftermath-Teile und das Final Aftermath.',
    date: '2026-09-03',
    sections: [
      { title: 'Position in der Route', paragraphs: ['Diese Eckdaten stammen aus der offiziellen Erfolgsliste und den Zeitstempeln eines Referenzdurchlaufs — sie verorten das Kapitel exakt, auch ohne granulares Level-Dokument:'], bullets: ['Kapitelname: The Final Aftermath', 'Position: nach Lazar’s Blood Bank (01:58:34 im Referenzdurchlauf), vor Closing In (02:18:29)', 'Erfolg: "Nine, Ten, Never Jank Again." — Complete The Final Aftermath Chapter', 'Kapitelrechnung: 9 Schauplatz-Kapitel + 4 Aftermath-Teile + das Final Aftermath = 14 Kapitel', 'Es folgt: Closing In (02:18:29), dann das Flesh-Pit-Finale (02:34:00)'] },
      { title: 'Warum die Position genau zählt', paragraphs: ['Wer der Route mit der Uhr folgt, braucht diese Einordnung: Lazar’s Blood Bank — Laynas Kapitel und das letzte der Opfer-Schauplatz-Kapitel — endet nahe Minute 01:58 eines Referenzdurchlaufs. Das Final Aftermath landet danach, und Closing In öffnet bei 02:18:29. Dem Zwischenspiel bleiben damit rund zwanzig Minuten auf der Zeitleiste, innerhalb eines Durchlaufs, der am Flesh Pit bei etwa 02:34 endet und auf die offizielle Kopfzeilenlänge von rund zweieinhalb Stunden zuläuft.', 'Steam bestätigt dieselbe Ordnung von der anderen Seite: Die Erfolgsliste zählt die Zwischenspiele in Reihenfolge durch, und der letzte Posten "Nine, Ten, Never Jank Again." sitzt exakt auf dem Final Aftermath. Wer die Erfolgsliste von oben liest, liest damit die Reihenfolge der Route.'] },
      { title: 'Der Erfolg hinter dem Kapitel', paragraphs: ['Der Steam-Erfolg lautet "Nine, Ten, Never Jank Again." mit der Anforderung "Complete The Final Aftermath Chapter." Es gibt keine versteckte Bedingung und kein verpassbares Element: Der Erfolg springt, wenn das Kapitel durch ist. Sein Name ist die Auflösung eines Zählreims, den das Spiel über seine Zwischenspiel-Erfolge fährt — Aftermath Part 3 trägt "Five, six, grab your crucifix...", und die Sequenz landet hier auf "nine, ten", beim letzten Zwischenspiel.', 'Für eine saubere Erfolgsliste ist dieser Posten unverlierbar, solange du die Route beendest. Das wirklich verpassbare Freischaltstück des Spiels ist die Thank-You-Notiz im Büro — ein eigener Eintrag, den der Erfolgsratgeber separat behandelt.'] },
      { title: 'Was im Final Aftermath passiert', paragraphs: ['Die Aftermath-Kapitel existieren, um jede Opfergeschichte zurück in Dick Slaters Fallakte zu holen. Die Opferkapitel sind gewöhnliche Arbeitsschichten — Hotdogs servieren, Donuts befüllen, Kassetten zurückspulen —, die im Zugriff des Killers enden; die Aftermath-Teile rahmen diese Tode dann als Beweise, Verbindungen und eine Zahl, die weiterklettert. Das Final Aftermath schließt diesen Faden: Die letzte Opfergeschichte geht in die Ermittlung ein, und der Fall ist vollständig genug, damit Slater dem Killer gegenübertreten kann.', 'Wie das Kapitel im Einzelnen aussieht — cutscene-artiges Zwischenspiel oder Abschnitt mit eigenen Interaktionen — ist ein Detail, das du im Spiel prüfen kannst. Offiziell dokumentiert sind der Kapitelname, seine Position in der Reihenfolge und sein Erfolg; granularer geht der Datensatz nicht.'] },
      { title: 'Wie es das Endspiel vorbereitet', paragraphs: ['Nach dem Final Aftermath bleiben zwei Kapitel, und beide sind Ermittlung. Closing In, ab 02:18:29 im Referenzdurchlauf, konvergiert den Fall auf einen Verdächtigen. The Flesh Pit — Elias Crows Barbecue-Restaurant und die Antwort auf die Titelfrage — trägt das Finale bei 02:34:00. Ab dem Final Aftermath gibt es keine Opferkapitel mehr und keine Schichten mehr zu arbeiten: Die letzten zwanzig Minuten sind die Geschichte, die ihre Kiefern schließt. Was im Finale passiert, behandelt die Ending-Seite; Identität und Motiv des Killers legt der Who-is-the-Skin-Stapler-Ratgeber für den Moment nach dem Abspann aus.'] }
    ],
    faq: [
      { question: 'Was ist das Final Aftermath in The Skin Stapler?', answer: 'Das fünfte und letzte Aftermath-Zwischenspiel — das Kapitel, das den Opferfaden vor dem zweiteiligen Endspiel aus Closing In und Flesh Pit abschließt.' },
      { question: 'Welchen Erfolg schaltet es frei?', answer: '"Nine, Ten, Never Jank Again." für den Abschluss von The Final Aftermath Chapter; der Erfolg springt automatisch bei Kapitelende.' },
      { question: 'Ist das Final Aftermath ein spielbares Kapitel?', answer: 'Das genaue Format — Cutscene-Zwischenspiel oder interaktiver Abschnitt — ist nicht separat dokumentiert. Offiziell zählt es als eines der 14 Kapitel und liegt in der Route zwischen Lazar’s Blood Bank und Closing In.' },
      { question: 'Wie weit ist es im Spiel fortgeschritten?', answer: 'Etwa bei der Zweistundenmarke: Lazar’s Blood Bank endet nahe 01:58:34 im Referenzdurchlauf, Closing In öffnet bei 02:18:29 — das Zwischenspiel liegt dazwischen.' },
      { question: 'Endet das Spiel nach dem Final Aftermath?', answer: 'Nein. Closing In und das Flesh-Pit-Finale folgen noch — das Zwischenspiel schließt die Opfergeschichten, die letzten beiden Kapitel liefern das Ende.' }
    ],
    sources: sourceSets['final-aftermath']
  },
  'aftermath-3': {
    id: 'aftermath-3', keyword: 'The Skin Stapler Aftermath 3',
    title: 'The Skin Stapler Aftermath 3: Position, Erfolg und Ablauf',
    description: 'Aftermath Part 3 erklärt: das dritte Zwischenspiel zwischen Lunas Donutladen und Underworld VHS, mit dem Erfolg "Five, six, grab your crucifix...".',
    eyebrow: 'Kapitelguide',
    directAnswer: 'Aftermath 3 — auf Steam The Aftermath Part 3 — ist das dritte der vier Aftermath-Zwischenspiele von The Skin Stapler und sitzt mitten in der Übergabe von den Opfern zur Ermittlung: nach Lunas Cream-Filled-Donuts-Kapitel, das im Referenzdurchlauf bei 01:15:37 endet, und vor Underworld VHS, das bei 01:34:10 öffnet. Der Abschluss schaltet den Erfolg "Five, six, grab your crucifix..." frei, die dritte Zeile des Zählreims über die Zwischenspiel-Erfolge.',
    date: '2026-09-03',
    sections: [
      { title: 'Position in der Route', paragraphs: ['Die beiden Zeitstempel rahmen das Zwischenspiel eng ein — alles dazwischen ist das Interlude plus der Start des nächsten Kapitels, innerhalb einer Gesamtroute von rund zweieinhalb Stunden:'], bullets: ['Kapitelname: The Aftermath Part 3', 'Position: nach Lunas Cream Filled Donuts (01:15:37), vor Underworld VHS (01:34:10)', 'Erfolg: "Five, six, grab your crucifix..." — Complete The Aftermath Part 3 Chapter', 'Funktion: faltet die Opfergeschichten zurück in Dick Slaters Ermittlung', 'Zeitfenster: die Spanne 01:15–01:34 eines Referenzdurchlaufs'] },
      { title: 'Was das Kapitel für die Story tut', paragraphs: ['Die Aftermath-Formel ist das Bindegewebe der Spielstruktur. Jedes Opferkapitel endet gleich — eine gewöhnliche Schicht kippt in die Hände des Killers —, und jeder Aftermath-Teil zieht diesen Tod zurück in Slaters Fallakte: Die Beweistafeln wachsen, die Verbindungen mehren sich, die Zahl steigt. Part 3 ist der Punkt, an dem sich der Rhythmus der zweiten Hälfte verfestigt. Er folgt Lunas Kapitel in der Reihenfolge, und Lunas Szene trägt den VHS-Faden, mit dem das nächste Schauplatz-Kapitel weiterläuft: Underworld VHS ist Scarolines Videoladen, und die Verbindung zwischen Donutladen und Videoladen dokumentiert der Who-is-the-Skin-Stapler-Ratgeber.', 'Die Szene-für-Szene-Inhalte des Kapitels — welche Opfer es berührt und wie die Fallakte sie rahmt — sind in den offiziellen Materialien nicht separat dokumentiert. Was der offizielle Datensatz festlegt, sind Name, Slot in der Reihenfolge und Erfolg; diese drei Fakten reichen, um das Kapitel exakt zu verorten.'] },
      { title: 'Das Zählreim-Muster der Erfolge', paragraphs: ['Die Platzierung erklärt auch den Reim. Die Zwischenspiele tragen die Zähl-Erfolge des Spiels in Sequenz — Part 3 mit "Five, six, grab your crucifix..." ist die dritte Zeile, und das Set löst sich mit "Nine, Ten, Never Jank Again." auf dem Final Aftermath auf. Wer die Erfolgsliste von oben nach unten liest, liest damit die Reihenfolge der Zwischenspiele selbst; genau so ist die Routenposition oben festgenagelt: Die Steam-Erfolgsreihenfolge setzt The Aftermath Part 3 direkt zwischen Lunas Freischaltung und die Underworld-VHS-Strecke.'] },
      { title: 'So erreichst du Aftermath 3', paragraphs: [], bullets: ['Schließe Lunas Cream Filled Donuts ab: Arbeite die Servierschicht bis zum Ende — das Kapitel, in dem Luna und Chief O’Brien ihr Schicksal treffen —, und die Story wechselt automatisch ins Zwischenspiel', 'Lass das Zwischenspiel durchlaufen: Der Erfolg "Five, six, grab your crucifix..." springt bei Kapitelabschluss; es gibt keine Wahl, keine versteckte Bedingung und kein Sammelobjekt an der Freischaltung', 'Lauf weiter in Underworld VHS: Das nächste Schauplatz-Kapitel öffnet bei 01:34:10 im Referenzdurchlauf — Scarolines Videoladen, ein rund 24-minütiges Kapitel laut Routen-Zeitleiste'] },
      { title: 'Einordnung im Gesamtverlauf', paragraphs: ['Was das Zwischenspiel umgibt, hilft beim Verorten: Davor hat die Route fünf Schauplatz-Kapitel gespielt, mit Lunas Cream Filled Donuts als dem fünften; nach dem Videoladen bleibt nur Lazar’s Blood Bank, bevor die Endspiel-Kapitel übernehmen. Aftermath Part 3 ist das Scharnier zwischen dem Schlussakkord des Donutladens und dem Videoladen-Kapitel, das den VHS-Faden aufnimmt, den Lunas Szene legt — der Moment, in dem das Spiel aufhört, Opfer vorzustellen, und anfängt, den Fall zu schließen.'] }
    ],
    faq: [
      { question: 'Was ist Aftermath 3 in The Skin Stapler?', answer: 'Das dritte von vier Aftermath-Zwischenspielen — das Kapitel, das die Opfergeschichten zwischen Lunas Donutladen und Underworld VHS zurück in Slaters Ermittlung trägt.' },
      { question: 'Welchen Erfolg schaltet es frei?', answer: '"Five, six, grab your crucifix..." für den Abschluss von The Aftermath Part 3 Chapter — die dritte Zeile des Zählreims über die Zwischenspiel-Erfolge.' },
      { question: 'Wo liegt Aftermath 3 in der Route?', answer: 'Zwischen Lunas Cream Filled Donuts (Ende nahe 01:15:37) und Underworld VHS (Beginn bei 01:34:10) in der Kapitelreihenfolge.' },
      { question: 'Ist Aftermath 3 spielbar?', answer: 'Der genaue Interaktionsgrad der Zwischenspiele ist nicht separat dokumentiert. Offiziell ist es eines der 14 Kapitel, und sein Erfolg springt bei Abschluss unabhängig vom Format.' },
      { question: 'Wie viele Aftermath-Kapitel gibt es?', answer: 'Vier nummerierte Teile plus das Final Aftermath — fünf Zwischenspiele innerhalb der 14 Kapitel, jedes mit eigenem Abschluss-Erfolg.' }
    ],
    sources: sourceSets['aftermath-3']
  }
};
